# Knowledge Graph RAG

<img src="./media/graph_start.png" width=600>

*[Improving Knowledge Graph Completion with Generative LM and neighbors](https://deeppavlov.ai/research/tpost/bn15u1y4v1-improving-knowledge-graph-completion-wit)*

In the evolving landscape of AI and information retrieval, knowledge graphs have emerged as a powerful way to represent complex, interconnected information. A knowledge graph is a knowledge base that uses a graph-structured data model or topology to represent and operate on data. Knowledge graphs are often used to store interlinked descriptions of entities – objects, events, situations or abstract concepts – while also encoding the free-form semantics or relationships underlying these entities. [Source: Wikipedia](https://en.wikipedia.org/wiki/Knowledge_graph)

What makes knowledge graphs particularly powerful is their ability to mirror human cognition in data. They more explicitly map the relationships between objects, concepts, or ideas together through both their semantic and relational connections. This approach closely parallels how our brains naturally understand and internalize information – not as isolated facts, but as a web of interconnected concepts and relationships.

<img src="./media/coffee_graph_ex.png" width=400>

Looking at a concept like "coffee," we don't just know it's a beverage; we automatically connect it to related concepts like beans, brewing methods, caffeine, morning routines, and social interactions. Knowledge graphs capture these natural associations in a structured way.

Traditional RAG systems, while effective at semantic similarity-based retrieval, often struggle to capture broader conceptual relationships across text chunks. Knowledge Graph RAG addresses this limitation by introducing a structured, hierarchical approach to information organization and retrieval. By representing data in a graph format, these systems can traverse relationships between concepts, enabling more sophisticated query understanding and response generation. This approach allows for targeted querying along specific relationship paths, handles complex multi-hop questions, and provides clearer reasoning through explicit connection paths. The result is a more nuanced and interpretable system that combines the structured reasoning of knowledge graphs with the natural language capabilities of large language models.

While [knowledge graphs are not a new concept](https://blog.google/products/search/introducing-knowledge-graph-things-not/), their creation has traditionally been a resource-intensive process. Early knowledge graphs were built either through manual curation by domain experts or by converting existing structured data from relational databases. This limited both their scale and adaptability to new domains.

<img src="./media/table_comp.png" width=600>

*[What is a Knowledge Graph (KG)?](https://zilliz.com/learn/what-is-knowledge-graph)*

The introduction of LLMs has transformed this landscape. LLMs' capabilities in NLP, reasoning, and relationship extraction now enable automated construction of knowledge graphs from unstructured text. These models can identify entities, infer relationships, and structure information in ways that previously required extensive manual labor. As a plus, this allows knowledge graphs to be dynamically updated and expanded as new information becomes available, making them more practical and scalable for real-world applications.

To see this in action ourselves, and compare it to traditional vector similarity techniques, we'll take a look at Microsoft's Open Source [GraphRAG](https://microsoft.github.io/graphrag/) and how it works behind the scenes.

---
## 3 Main Components of Knowledge Graphs

**Entity**

<img src="./media/entities.png" width=500>

An Entity is a distinct object, person, place, event, or concept that has been extracted from a chunk of text through LLM analysis. Entities form the nodes of the knowledge graph. During the creation of the knowledge graph, when duplicate entities are found they are merged while preserving their various descriptions, creating a comprehensive representation of each unique entity.

**Relationship**

<img src="./media/relationship.png" width=400>

A Relationship defines a connection between two entities in the knowledge graph. These connections are extracted directly from text units through LLM analysis, alongside entities. Each relationship includes a source entity, target entity, and descriptive information about their connection. When duplicate relationships are found between the same entities, they are merged by combining their descriptions to create a more complete understanding of the connection.

**Community**

<img src="./media/communities.png" width=400>

A Community is a cluster of related entities and relationships identified through hierarchical community detection, generally using the [Leiden Algorithm](https://en.wikipedia.org/wiki/Leiden_algorithm). Communities create a structured way to understand different levels of granularity within the knowledge graph, from broad overviews at the top level to detailed local clusters at lower levels. This hierarchical structure helps in organizing and navigating complex knowledge graphs.

---
## GraphRAG Creation Data Flow

<img src=./media/graph_building.png width=1000>

Indexxing in GraphRAG is an extensive process, where we load the document, split it into chunks, create sub graphs at a chunk level, combine these subgraphs into our final graph, algorithmically identify communities, then document the communities main features.

### **Loading and Splitting Our Text**

For our example, we'll be using [The Ultimate Guide to Fine-Tuning LLMs from Basics to Breakthroughs: An Exhaustive Review of Technologies, Research, Best Practices, Applied Research Challenges and Opportunities](https://arxiv.org/pdf/2408.13296).

This will be loaded as a text file (remove index, glossary, and references) and split into 1200 token, 100 token overlap chunks.

In [ ]:
import json
with open("../anchored_index_output.json", "r") as f:
    data = json.load(f)
headers=data["sheets"]['Salary List']["headers"]
anchors = data["sheets"]["Salary List"]["anchors"]
chunks=[]
for chunk_name, chunk_info in anchors.items():
    chunk_info['headers']=headers
    chunks.append(chunk_info)
print(f"Loaded {len(chunks)} chunks")
texts=chunks
chunks

Loaded 19 chunks

[{'range': 'A1:A20',
  'start_row': 1,
  'end_row': 20,
  'summary': 'This data chunk contains information about various companies, their roles, hourly rates, benefits, and years of employment.',
  'context': 'The data includes details on compensation and benefits for co-op positions and internships across different companies.',
  'table': ['Company / Role [A1]\tBye World [B1]\tBenefits [C1]\tYear [D1]\tPosition [E1]',
   '1password [A2]\t50/hr (4th coop) [B2]\t2023 [D2]',
   'Abbott ADD [A3]\t22.05/hr (2nd coop) [B3]',
   'Abnormal Security [A4]\t106k USD annual prorated (~$51/hr USD) [B4]\t5k relocation [C4]',
   'Accedo [A5]\t25-27/hr (3rd coop) [B5]',
   '20-25/hr [B6]',
   'Addepar [A7]\t40/hr, 48/hr (5th coop) [B7]',
   'AdHawk Microsystems [A8]\t40/hr (5th coop) [B8]\t2024 [D8]\tAlgorithms Developer [E8]',
   'less than 44/hr [B9]',
   'AGF Investments [A10]\t25/hr (2nd coop) [B10]\t2023 [D10]\tWeb Developer (Junior) [E10]',
   'AI Arena [A11]\t45/hr [B11]',
   'Akuna Capital [A12]\t65 USD/hour [B12]\treturn flight + corporate housing [C12]',
   'Altice USA [A13]\tmid 30s/hr (6th coop) [B13]',
   'Amazon [A14]\t9138 USD/month [B14]\t2425/month tax-free relocation stipend [C14]',
   'AMD [A15]\t27/hr, ~21.88/hr (4th coop), ~29.33/hr (6th coop) [B15]',
   'American Express [A16]\t34.5/hr [B16]',
   'ANSYS [A17]\tmath coop average + 10% [B17]',
   '(34/hr + 1300-1500 stipend/month), (37/hr + 1350 stipend for 3A term), (44/h + housing or 1k stipend. 4A Product Design) [B18]\tStipends listed [C18]',
   'Apple [A19]\t42/hr USD (3A) [B19]\t3335/mo pretax relocation (3A) [C19]\t2024 [D19]\tHardware [E19]',
   'Apple [A20]\t42/hr USD [B20]\t1k/mo stipend [C20]\t2024 [D20]\tSystem Level Test Engineer [E20]'],
  'formulas': [],
  'chunk_number': 0,
  'headers': ['Company / Role', 'Bye World', 'Benefits', 'Year', 'Position']},
 {'range': 'A21:A40',
  'start_row': 21,
  'end_row': 40,
  'summary': 'This data chunk contains information about various companies and their compensation rates for co-op positions.',
  'context': 'The data includes hourly rates, monthly stipends, and additional benefits for different co-op years across multiple companies.',
  'table': ['Arctic Wolf [A21]\t36/hr (3rd coop), 42/hr (4th coop) [B21]\t2023 [D21]',
   'Arctic Wolf [A22]\t38/hr (4th coop) [B22]\t2024 [D22]',
   'Aterlo Networks [A23]\t30/hr (4th coop) [B23]',
   'Athelas [A24]\t33/hr USD [B24]\t1200/mo USD housing stipend (2nd coop) + flights [C24]',
   'Athos [A25]\t5000 USD/mo [B25]',
   'Atolio [A26]\t34/hr (3rd coop), 38/hr (4th coop), 38/hr (5th coop), 42/hr (6th coop) [B26]',
   'ATS Corporation [A27]\t28/hr (5th year (4B?)) [B27]',
   '33/hr (4th coop) [B28]\t2023 [D28]',
   'Autodesk [A29]\t34/hr (5th coop) [B29]\t2024 [D29]',
   'Autonomic [A30]\t38-40/hr (4th coop), 41/hr (5th coop) [B30]',
   'Axonify [A31]\t1100/week (4th coop) [B31]\t2024 [D31]',
   'Bank of America [A32]\t22/hr (2nd coop) [B32]',
   'Bank of America (Merrill Lynch) [A33]\t20/hr (1st coop) [B33]',
   'BDO [A34]\t34.36/hr, 25/h (2nd coop), 32/h (3rd coop) [B34]',
   'Bentley Systems [A35]\t30/hr (1st coop), 33/hr (2nd coop) [B35]',
   'BETS Program [A36]\t3000 stipend [B36]',
   'BetterUp [A37]\t8500/mo [B37]',
   'Bitbuy [A38]\t20/hr (1st coop) [B38]',
   '10,000/mo [B39]',
   'Blackberry [A40]\t(about average), ~21/hr [B40]'],
  'formulas': [],
  'chunk_number': 1,
  'headers': ['Company / Role', 'Bye World', 'Benefits', 'Year', 'Position']},
 {'range': 'A41:A60',
  'start_row': 41,
  'end_row': 60,
  'summary': 'This data chunk contains information about various companies and their compensation offers for co-op positions.',
  'context': 'The data includes hourly rates, monthly salaries, stipends, and additional benefits for different roles across multiple companies.',
  'table': ['bld.ai [A41]\t7000/mo [B41]',
   'Bloomberg [A42]\t48/hr + 5100 stipend (5th coop) [B42]',
   'Bloq [A43]\t5.4k/mo (2nd coop), 6.2k/mo (3rd coop) [B43]\t950/mo benefits (2nd coop, 3rd coop) [C43]',
   'Bluescape [A44]\t34/hr (6th coop) [B44]',
   'BMO Business Analyst (2A) [A45]\t24/hr [B45]',
   'BMO Product Analyst [A46]\t28/hr (2nd coop) [B46]',
   'BMO Software Developer [A47]\t29.50/hr (1st coop) [B47]',
   'Bolt [A48]\t56 USD/hr [B48]',
   'Bonfire Interactive [A49]\t24/hr (2nd coop) [B49]',
   'Boosted.AI [A50]\t35/hr [B50]',
   'Borrowell [A51]\t(mobile dev) 35/hr (5h coop) [B51]',
   'Brookfield Annuity [A52]\t35/hr [B52]',
   'Brookfield Renewables [A53]\t26/hr [B53]',
   'BusPlanner [A54]\tcoop average [B54]\t2024 [D54]',
   'CAAT Pension Plan [A55]\t18/hr (2nd coop) [B55]',
   'Canadian Food Inspection Agency (Full Stack Dev) [A56]\t24.77/hr (5th coop) [B56]',
   '6400 USD/mo (+1000/mo relocation in-person) [B57]',
   '25-30/hr [B58]',
   'Capital1 [A59]\t40/hr (5th coop) [B59]\t$1000 signing bonus [C59]\t2025 [D59]',
   'Carta [A60]\t30.75/hr (4th coop), 1230-1400/week [B60]\tSWE [E60]'],
  'formulas': [],
  'chunk_number': 2,
  'headers': ['Company / Role', 'Bye World', 'Benefits', 'Year', 'Position']},
 {'range': 'A61:A80',
  'start_row': 61,
  'end_row': 80,
  'summary': 'This data chunk contains information about various companies and their compensation rates for co-op positions.',
  'context': 'The data includes hourly rates, monthly salaries, and additional benefits for co-op roles in different years and positions.',
  'table': ['Carta [A61]\t40/hr (4th coop), 47/hr (5th coop) [B61]\t2024 [D61]\tAndroid Engineering [E61]',
   'Carfax (Dev) [A62]\t26/hr (2nd coop) [B62]',
   'Castleton Commodities [A63]\t38/hr [B63]',
   'CEGN [A64]\tLow-Mid 20s [B64]',
   'C.E. McMahon Professional Corporation [A65]\t19/hr [B65]',
   'Cepton [A66]\t35/hr [B66]\t500/mo housing [C66]',
   'Cerebras Systems [A67]\t38/hr [B67]',
   'Ceridian [A68]\t32/hr (3rd coop) [B68]\t2023 [D68]',
   'Ceridian [A69]\t22/hr [B69]\t2022, 2023 [D69]\tMarketing Coordinator [E69]',
   'Certik [A70]\t7000 USD/month remote (4th coop) [B70]',
   'CGI [A71]\t18/hr (3rd coop) [B71]',
   'Chisel.ai [A72]\t40/hr (5th coop) [B72]',
   'Christie Digital Systems [A73]\t18/hr (1st coop), +2/hr every add. coop term [B73]',
   'CIBC [A74]\tcoop average + $1 [B74]',
   'Cisco (Ottawa Office) [A75]\t31-33/hr (1st coop) [B75]\t2000 CAD signing bonus (1st coop) [C75]\t2024 [D75]',
   'Cisco Meraki [A76]\t(up to) 67/hr + 10k signing bonus [B76]',
   'Citadel [A77]\t3365 USD/week [B77]',
   'Citibank [A78]\t44/hr [B78]\t2000 CAD housing stipend [C78]\t2024 [D78]',
   'Cockroach Labs [A79]\t8000/month + 1.5k signing bonus [B79]',
   'CodeWithChris [A80]\t20/hr (1st coop) [B80]'],
  'formulas': [],
  'chunk_number': 3,
  'headers': ['Company / Role', 'Bye World', 'Benefits', 'Year', 'Position']},
 {'range': 'A81:A100',
  'start_row': 81,
  'end_row': 100,
  'summary': 'This data chunk contains hourly and monthly compensation details for various companies, including co-op positions and stipends.',
  'context': 'The data includes information on pay rates for internships and co-op roles, with some entries specifying additional benefits and future years.',
  'table': ['Cohere [A81]\t20-50/hr based on experience [B81]',
   'Coherent Logix [A82]\t$1-3 above coop average [B82]',
   'Cohesity [A83]\t49/hr [B83]',
   'Coinbase [A84]\t50/hr [B84]',
   'Coinsquare [A85]\t28/hr (1st coop), 44/hr (5th coop, any dev role) [B85]',
   'Composer.trade [A86]\t9000/month [B86]\t500/month stipend [C86]\t2024 [D86]',
   'Compound [A87]\t$10,200/month [B87]',
   'Connected [A88]\t37/hr (6th coop) [B88]',
   'Constant Contact [A89]\t35/hr (4th coop) [B89]\t2023 [D89]',
   'The Co-operators [A90]\t~21/hr (1st coop) [B90]',
   'Core Avionics [A91]\t20/hr (1st coop), 30/hr [B91]',
   'Coursera [A92]\t7000/month [B92]',
   'Cover Technologies Inc [A93]\t30 USD/hr [B93]',
   'CPP Investments [A94]\t37/hr (2nd coop) [B94]\t4% of yearly salary (70k) as vacation pay [C94]\t2024 [D94]\tSWE [E94]',
   'CPP Investments [A95]\t34/hr (3rd coop) [B95]\t2024 [D95]\t"Intern Engineer" [E95]',
   'CPP Investments [A96]\t48/hr (4th coop) [B96]\t2024 [D96]\t"Intern Analyst" [E96]',
   'Crawford and Co [A97]\t20/hr [B97]\t2022 [D97]\tBusiness Analyst [E97]',
   'Cresta [A98]\t40/hr (5th coop) [B98]\t$25/day lunch [C98]\t2025 [D98]',
   'Creospark [A99]\t18/hr [B99]',
   'Crypto4a [A100]\t40/hr (remote, 6th coop) [B100]\t4 days PTO [C100]\t2024 [D100]\tSWE [E100]'],
  'formulas': [],
  'chunk_number': 4,
  'headers': ['Company / Role', 'Bye World', 'Benefits', 'Year', 'Position']},
 {'range': 'A101:A120',
  'start_row': 101,
  'end_row': 120,
  'summary': 'This data chunk contains hourly and salary information for various companies and positions.',
  'context': 'The data includes pay rates in different currencies, co-op averages, and specific conditions for compensation.',
  'table': ['Cube Group [A101]\t75/hr USD [B101]\t2024 [D101]',
   'Curinos [A102]\t34/hr (2b) [B102]',
   'Curvegrid (Japan) [A103]\t¥300,000/mo (2nd coop) [B103]',
   'D2L [A104]\t28/hr [B104]',
   'Databrick [A105]\t55 CAD/hr [B105]\t1.3k/mo housing [C105]',
   'Datadog [A106]\t40/hr [B106]\t2000 USD/mo housing [C106]',
   'data.world [A107]\t1400 USD/week [B107]\t100 USD remote stipend [C107]',
   'Deep Breathe [A108]\tco-op average + 20% [B108]',
   'Deep Genomics [A109]\t60k/yr [B109]',
   'DeepHaven [A110]\t32-38/hr (increases with work term) [B110]\t2024 [D110]',
   'Dejero [A111]\t1.15*coop average [B111]',
   'Deloitte [A112]\t25-28/hr [B112]',
   'Delphia Asset Management [A113]\t5-10% above the coop average [B113]',
   'Digitaled [A114]\tCoop average [B114]',
   'Digital Extremes (Marketing) [A115]\t20/hr (2nd coop) [B115]',
   'DocuSign [A116]\t52/hr  [B116]',
   'Draper [A117]\t1400/wk [B117]',
   'Dreamschools [A118]\t19-24/hr [B118]',
   'Dropbase (Castodia) [A119]\t(25-50/hr, +5 per work term), 29/hr for 3rd coop, 30-32/hr for 4/5th coop [B119]',
   'DRW [A120]\t35-37/hr [B120]'],
  'formulas': ['Row104: R1:D2'],
  'chunk_number': 5,
  'headers': ['Company / Role', 'Bye World', 'Benefits', 'Year', 'Position']},
 {'range': 'A121:A140',
  'start_row': 121,
  'end_row': 140,
  'summary': 'This data chunk contains hourly and monthly compensation rates for various companies and positions.',
  'context': 'The data includes information on different co-op positions, their pay rates, and some additional details about the roles.',
  'table': ['Durovac [A121]\t23/hr (4th coop) [B121]',
   'Ecobee [A122]\t36-41/hr (4th coop), 43/hr (5th coop) [B122]\t2024 [D122]',
   'Ecompliance [A123]\t26/hr (4th coop), couple dollars above coop average [B123]',
   'Elekta [A124]\t27/hr (2A) [B124]',
   'Embark Trucks [A125]\t10k/month (USD in person / CAD for remote) [B125]',
   'Enzuzo [A126]\t28/hr (3rd coop) [B126]\t2024 [D126]\tFullstack [E126]',
   'The Empire Life Insurance Company [A127]\t22-28/hr based on work term [B127]',
   'Enlighted Inc [A128]\t36/hr (5th coop) [B128]',
   'Eon Media [A129]\t3800/mo (3rd year) [B129]',
   'Equifax D&A [A130]\t22/hr (1st coop) [B130]',
   'Equitable Life Insurance Company [A131]\t20/hr, 23/hr (2nd coop) [B131]',
   'ESCRYPT [A132]\t26/hr (3rd coop), 30/hr (4th coop) [B132]',
   'eSentire [A133]\t24.50/hr [B133]',
   'ETHGlobal [A134]\t9000/month [B134]\t500/month stipend [C134]\t2024 [D134]',
   'EY [A135]\t28/hr (3rd coop) [B135]',
   'Faire [A136]\t44/hr (5th coop) [B136]\t2024 [D136]\tEngineering [E136]',
   'Fleet Complete [A137]\t26/hr (3rd coop), 32/hr (5th coop) [B137]',
   'Fleet Labs [A138]\t25-27/hr [B138]',
   '$5000/mo [B139]',
   'The Flight Deck [A140]\t23/hr [B140]'],
  'formulas': [],
  'chunk_number': 6,
  'headers': ['Company / Role', 'Bye World', 'Benefits', 'Year', 'Position']},
 {'range': 'A141:A160',
  'start_row': 141,
  'end_row': 160,
  'summary': 'This data chunk contains information about various companies and their compensation rates for co-op positions.',
  'context': 'The data includes hourly rates, monthly salaries, and additional notes about the positions and years.',
  'table': ['Flipp [A141]\t$1082/wk [B141]',
   'Float [A142]\t50/hr [B142]',
   'Ford [A143]\t27-35/hr (+~4% every add. coop term) [B143]\t2024 [D143]\tSWE [E143]',
   'Forethought AI [A144]\t6000-8000/month [B144]',
   'Freshbooks [A145]\t33/hr (5th coop), 70k/year [B145]',
   'Friendlier [A146]\t17/hr (4th coop) [B146]\t2024 [D146]',
   'Fuego Studios Inc. [A147]\t35/hr (1st coop) [B147]\t2024 [D147]',
   'Genesys Laboratories [A148]\t10% above the coop average [B148]',
   'Geotab [A149]\t30/hr (3rd coop) [B149]',
   'Get ResQ [A150]\t43/hr (5th coop) [B150]',
   'GIP (Green Infrastructure Program) [A151]\t31/hr (6th coop) [B151]\t2024 [D151]',
   'Glu [A152]\t30/hr (4th coop), 25/hr (2nd coop) [B152]',
   'GoDaddy [A153]\t43/hr USD [B153]\t2024 [D153]',
   'Google [A154]\tCanada: $1538/week, US: $1700 - $2100 USD/week based on location [B154]\t4k housing stipend (Canada),  6k USD housing stipend (USA) [C154]',
   'GPTZero [A155]\t40-55/hr CAD (Toronto), 7000-8000/month USD (NYC) [B155]\t2024 [D155]',
   'groq (Groq Inc) [A156]\t37/hr (1st coop), 35-42/hr - 42 is 6th coop [B156]',
   'Gsoft [A157]\t40/hr (4th coop) [B157]',
   'H2Analytics [A158]\t23/hr [B158]',
   'Halp [A159]\t38/hr (3rd coop) [B159]',
   'Hatch Credit [A160]\t8000-9000 USD/month [B160]'],
  'formulas': ['Row158: R1:H2'],
  'chunk_number': 7,
  'headers': ['Company / Role', 'Bye World', 'Benefits', 'Year', 'Position']},
 {'range': 'A161:A180',
  'start_row': 161,
  'end_row': 180,
  'summary': 'This data chunk contains information about various companies and their coop hourly rates for students.',
  'context': 'The data includes company names, hourly rates, coop levels, and some additional notes about the positions.',
  'table': ['Havas CX [A161]\t30/hr (4th coop) [B161]\t2024 [D161]\tSoftware Engineering [E161]',
   'HeadSpin [A162]\t32/hr (3rd coop) [B162]',
   'Healthcare Systems R&A [A163]\t16-20/hr [B163]\t2023 (WIDELY VARIES BASED ON FUNDING) [D163]',
   'High Q Technologies [A164]\t25/hr (3rd coop) [B164]',
   'Hockeystick [A165]\taround coop average, 21/hr (1st coop) [B165]',
   'Home Depot (Dev) [A166]\t20/hr (2nd coop) [B166]',
   'HomeX [A167]\t30/hr, 33/hr (3rd coop) [B167]',
   'HOOPP (Health Care of Ontario Pension Plan) [A168]\t22.25/hr (2nd coop) [B168]',
   'Horizon Studio [A169]\t27/hr (3rd coop) [B169]\t2023 [D169]',
   'Huawei [A170]\t36/hr (5th coop) [B170]\t2025 [D170]',
   'Hubdoc [A171]\t5% above the coop average [B171]',
   'HubSpot [A172]\t50-54/hr USD [B172]',
   'IBM [A173]\t26.50/hr (28-31/hr for 4th coop), 36/hr [B173]',
   'IBM [A174]\t32/hr (4th coop) [B174]\tIBM stock at a 15% discount off the market price [C174]\t2023 [D174]\tProduct Design [E174]',
   '21,24,26,29,31,33/hr for 1st to 6th coop [B175]',
   'Index Exchange [A176]\t30/hr or above [B176]',
   'Indus AI [A177]\t8500/month USD (5th coop) [B177]\tFlights included [C177]',
   '25/hr, 26.5/hr (4th coop) [B178]',
   '50/hr [B179]',
   'Intact [A180]\t43/hr (5th coop) [B180]\t2025 [D180]'],
  'formulas': [],
  'chunk_number': 8,
  'headers': ['Company / Role', 'Bye World', 'Benefits', 'Year', 'Position']},
 {'range': 'A181:A200',
  'start_row': 181,
  'end_row': 200,
  'summary': 'This data chunk contains hourly and monthly compensation details for various companies and positions.',
  'context': 'The data includes information on co-op positions, stipends, and salary ranges for internships and jobs in the tech and engineering sectors.',
  'table': ['Intact Labs [A181]\t30.5/hr (3rd coop), Data Science 32/hr (2nd coop), 39/hr (5/6th coop) [B181]',
   'Intel [A182]\t33/hr, 35/hr (6th coop) [B182]',
   '20-25/hr [B183]',
   'Instinet Canada [A184]\t36/hr (2nd coop, sre analyst) [B184]\t3k stipend (2nd coop, sre analyst) [C184]',
   'Integrate.ai [A185]\t1550/week [B185]',
   'Intuit [A186]\t30-37/hr, 47/hr (3rd coop) [B186]\t5k USD stipend [C186]',
   'iS5 Communications [A187]\t32/hr (6th coop) [B187]',
   'ISARA [A188]\t1228/week (3rd coop) [B188]',
   'Itipack Systems [A189]\t23/hr (2nd coop) [B189]\t2022 [D189]\tMechanical Design [E189]',
   'Jane Street [A190]\t16,667 USD/mo [B190]\t2.1k USD/mo housing stipend + 10k USD signing bonus [C190]',
   'Jays Care Foundation (TBJ) [A191]\t18/hr (1st coop) [B191]',
   'Jobox.ai [A192]\t5700 USD/mo (3rd coop) [B192]',
   'Kaleidescape  [A193]\t785/week [B193]\t2022 [D193]\tAll positions [E193]',
   'Kambeo [A194]\t20-30/hr [B194]',
   'KeepTruckin [A195]\t30/hr  [B195]',
   'KGS research [A196]\tI would rather KMS than KGS  [B196]',
   'Kiavi [A197]\t$9000/mo [B197]',
   'Kinaxis [A198]\t24/hr, 34/hr (1st+2nd coop), 28-30/hr (4th coop) [B198]',
   'Kodiak Robotics [A199]\t8k-9k USD/mo (6th coop?) [B199]',
   'Konrad Group [A200]\t6000/mo [B200]'],
  'formulas': ['Row187: R1:S5'],
  'chunk_number': 9,
  'headers': ['Company / Role', 'Bye World', 'Benefits', 'Year', 'Position']},
 {'range': 'A201:A220',
  'start_row': 201,
  'end_row': 220,
  'summary': 'This data chunk contains information about various companies and their compensation rates for different roles and co-op positions.',
  'context': 'The data includes hourly rates, monthly salaries, stipends, and specific roles for co-op students across multiple organizations.',
  'table': ['LCBO [A201]\t1100/wk (PM role) [B201]',
   'League [A202]\t33/hr (4th coop), 41/hr (6th coop) [B202]',
   'Level [A203]\t13,000/mo [B203]\t200 for equipment + 100/mo UberEats allowance [C203]',
   'LifeWorks [A204]\t22.5/hr [B204]',
   'Lifion by Adp [A205]\t40-44/hr [B205]',
   '55 USD/hr [B206]\tCorporate housing(/ 7K stipend) [C206]',
   'Loblaw [A207]\t31/hr (2nd coop) [B207]\tData Science [E207]',
   'Loblaw Digital [A208]\t30/hr (2nd coop) [B208]\t2023 [D208]\tData Analyst [E208]',
   'Mastercard Foundation [A209]\t19.5/hr (1st coop) [B209]',
   '29/hr, 35/hr (5th coop PM), 45/hr (6th coop PM) [B210]',
   'Manulife [A211]\t25/hr, 26/hr (3rd year) [B211]',
   'Mach7 Technologies [A212]\t25/hr (3rd coop) [B212]\t2024 [D212]\tSystems/IT [E212]',
   'McAfee [A213]\t25/hr (2nd? coop) [B213]',
   'Meta [A214]\t8200/month USD [B214]\t2024 [D214]',
   'Metrist [A215]\t70k/yr ~= 33.65/hr [B215]',
   'Microart Services [A216]\t26/hr (1st coop) [B216]',
   'Microsoft [A217]\t46/hr USD [B217]\t12k housing stipend + 1.6k transport stipend + flights covered [C217]\t2024 [D217]',
   'Microsoft Canada [A218]\t33/hr [B218]',
   'Milliman [A219]\t30/hr USD [B219]\t500 USD relocation stipend + 1500 USD monthly stipend [C219]\t2024 [D219]\tActuarial Analyst [E219]',
   'Molex [A220]\t23/hr (2nd coop), 25/hr (4th coop) [B220]'],
  'formulas': [],
  'chunk_number': 10,
  'headers': ['Company / Role', 'Bye World', 'Benefits', 'Year', 'Position']},
 {'range': 'A221:A240',
  'start_row': 221,
  'end_row': 240,
  'summary': 'This data chunk contains information about various companies and their compensation offers for co-op positions.',
  'context': 'The data includes hourly rates, monthly salaries, stipends, and additional details for different roles and years.',
  'table': ['MotoInsight [A221]\t3000/mo [B221]',
   'Motorola Solutions [A222]\t37/hr (5th coop) [B222]\t2024 [D222]\tProduct Design [E222]',
   'Moveworks [A223]\t9.5K/mo or 7.5K USD/mo + 500/mo stipend [B223]',
   'Mozilla [A224]\t30/hr (masters) [B224]\t2024 [D224]',
   'Munich Re [A225]\t1100/week [B225]\t1500 CAD stipend [C225]\t2024 [D225]',
   'NASDAQ [A226]\t28/hr [B226]',
   'NDI [A227]\tCoop Average [B227]\t2022 [D227]',
   'Newfront Insurance [A228]\t90/hr (6th coop) [B228]',
   'Nextroll [A229]\t57/hr [B229]\t60/month WFH allowance [C229]',
   'Nissan [A230]\t19-23/hr depending on term [B230]',
   'Nokia [A231]\t25/hr (4th coop), 33/hr (3rd and 4th years) [B231]',
   'Noom [A232]\t47 USD/hr [B232]\t1500 USD/mo housing [C232]',
   'Norm Li [A233]\t20-30/hr [B233]',
   'Nvidia [A234]\t36/hr (2b: 30.5/hr, 3a: 33/hr, 3b: 34.5/hr, 4a: 36/hr) [B234]\t500/wk housing [C234]',
   'NuraLogix [A235]\t28/hr (3rd coop) [B235]',
   'Nuro [A236]\t9000 USD/mo [B236]\t3k bonus [C236]',

**Entity and Relationship Extraction Prompt**

This is a [tuned](https://microsoft.github.io/graphrag/prompt_tuning/auto_prompt_tuning/) entity extraction prompt used in our real GraphRAG implementation, extracted in this format to see what's happening.

In [ ]:
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_openai import ChatOpenAI

llm = ChatOpenAI(temperature=0.0, model="gpt-4o")
import subprocess, sys

cmd = [
    sys.executable, "-m", "graphrag", "prompt-tune",
    "--config", "settings.yaml",
    "--output", "llm_tuned",
    "--limit", "10",
    "--discover-entity-types",
]

prompt_template=open('llm_tuned/extract_graph.txt').read()
prompt_template3=prompt_template.replace('{','{{').replace('}','}}').replace('{{input_text}}','{input_text}')
print(prompt_template3)
prompt = ChatPromptTemplate.from_template(prompt_template3)
chain = prompt | llm | StrOutputParser()

-Goal-
Given a text document that is potentially relevant to this activity and a list of entity types, identify all entities of those types from the text and all relationships among the identified entities.

-Steps-
1. Identify all entities. For each identified entity, extract the following information:
- entity_name: Name of the entity, capitalized
- entity_type: One of the following types: [ID, value, flag, metric, binary indicator]
- entity_description: Comprehensive description of the entity's attributes and activities
Format each entity as ("entity"{{tuple_delimiter}}<entity_name>{{tuple_delimiter}}<entity_type>{{tuple_delimiter}}<entity_description>)

2. From the entities identified in step 1, identify all pairs of (source_entity, target_entity) that are *clearly related* to each other.
For each pair of related entities, extract the following information:
- source_entity: name of the source entity, as identified in step 1
- target_entity: name of the target entity, as identified in step 1
- relationship_description: explanation as to why you think the source entity and the target entity are related to each other
- relationship_strength: an integer score between 1 to 10, indicating strength of the relationship between the source entity and target entity
Format each relationship as ("relationship"{{tuple_delimiter}}<source_entity>{{tuple_delimiter}}<target_entity>{{tuple_delimiter}}<relationship_description>{{tuple_delimiter}}<relationship_strength>)

3. Return output in English as a single list of all the entities and relationships identified in steps 1 and 2. Use **{{record_delimiter}}** as the list delimiter.

4. If you have to translate into English, just translate the descriptions, nothing else!

5. When finished, output {{completion_delimiter}}.

-Examples-
######################

Example 1:

entity_types: [ID, value, flag, metric, binary indicator]
text:
8.57 [D6088]\t4 [E6088]\tYes [F6088]\t10 [G6088]\t10 [H6088]\t2 [I6088]\tYes [J6088]",
            "CLG0039 [A6089]\t76 [B6089]\t6.09 [C6089]\t6.22 [D6089]\t2 [E6089]\tYes [F6089]\t6 [G6089]\t7 [H6089]\t1 [I6089]\tNo [J6089]",
            "CLG0049 [A6090]\t103 [B6090]\t6.12 [C6090]\t5.86 [D6090]\t8 [E6090]\tNo [F6090]\t6 [G6090]\t8 [H6090]\t0 [I6090]\tNo [J6090]",
            "CLG0082 [A6091]\t99 [B6091]\t6.38 [C6091]\t6.37 [D6091]\t4 [E6091]\tYes [F6091]\t7 [G6091]\t5 [H6091]\t0 [I6091]\tNo [J6091]",
            "CLG0100 [A6092]\t111 [B6092]\t7.93 [C6092]\t7.91 [D6092]\t5 [E6092]\tYes [F6092]\t0 [G6092]\t4 [H6092]\t3 [I6092]\tNo [J6092]",
            "CLG0037 [A6093]\t101 [B6093]\t8.3 [C6093]\t8.25 [D6093]\t7 [E6093]\tNo [F6093]\t9 [G6093]\t2 [H6093]\t4 [I6093]\tNo [J6093]",
            "CLG0090 [A6094]\t97 [B6094]\t5.09 [C6094]\t5.39 [D6094]\t5 [E6094]\tNo [F6094]\t3 [G6094]\t5 [H6094]\t3 [I6094]\tNo [J6094]",
            "CLG0097 [A6095]\t86 [B6095]\t6.21 [C6095]\t5.93 [D6095]\t10 [E6095]\tNo [F6095]\t9 [G6095]\t8 [H6095]\t5 [I6095]\tNo [J6095]",
            "CLG0001 [A6096]\t101 [B6096]\t7.15 [C6096]\t7.55 [D6096]\t4 [E6096]\tYes [F6096]\t4 [G6096]\t1 [H6096]\t0 [I6096]\tNo [J6096]",
            "CLG0091 [A6097]\t111 [B6097]\t6.66 [C6097]\t6.95 [D6097]\t7 [E6097]\tYes [F6097]\t1 [G6097]\t6 [H6097]\t2 [I6097]\tNo [J6097]",
            "CLG0037 [A6098]\t82 [B6098]\t9.42 [C6098]\t9.25 [D6098]\t4 [E6098]\tNo [F6098]\t1 [G6098]\t2 [H6098]\t4 [I6098]\tNo [J6098]",
            "CLG0086 [A6099]\t101 [B6099]\t8.94 [C6099]\t8.62 [D6099]\t10 [E6099]\tNo [F6099]\t10 [G6099]\t2 [H6099]\t4 [I6099]\tNo [J6099]",
            "CLG0019 [A6100]\t103 [B6100]\t8.13 [C6100]\t7.91 [D6100]\t4 [E6100]\tNo [F6100]\t3 [G6100]\t8 [H6100]\t0 [I6100]\tNo [J6100]"
          ],
          "formulas": [
            "Row6051: R1:CLG0074",
            "Row6052: R1:CLG0015",
            "Row6053: R1:CLG0057",
            "Row6054: R1:CLG0007",
            "Row6055: R1:CLG0078",
            "Row6056: R1:CLG0090",
            "Row6057: R1:CLG0018",
            "Row6058: R1:CLG0082",
            "Row6059: R1:CLG0006",
            "Row6060: R1:CLG0043",
            "Row6061: R1:CLG0089",
            "Row6062: R1:CLG0057",
            "Row6063: R1:CLG0041",
            "Row6064: R1:CLG0076",
            "Row6065: R1:CL
------------------------
output:
("entity"{{tuple_delimiter}}CLG0039{{tuple_delimiter}}ID{{tuple_delimiter}}A unique identifier for a data record)
{{record_delimiter}}
("entity"{{tuple_delimiter}}76{{tuple_delimiter}}value{{tuple_delimiter}}A numerical value associated with CLG0039)
{{record_delimiter}}
("entity"{{tuple_delimiter}}6.09{{tuple_delimiter}}metric{{tuple_delimiter}}A metric value associated with CLG0039)
{{record_delimiter}}
("entity"{{tuple_delimiter}}Yes{{tuple_delimiter}}flag{{tuple_delimiter}}A binary indicator flagging a specific condition for CLG0039 as true)
{{record_delimiter}}
("entity"{{tuple_delimiter}}10{{tuple_delimiter}}binary indicator{{tuple_delimiter}}A binary indicator value associated with CLG0039)
{{record_delimiter}}
("entity"{{tuple_delimiter}}CLG0049{{tuple_delimiter}}ID{{tuple_delimiter}}A unique identifier for a data record)
{{record_delimiter}}
("entity"{{tuple_delimiter}}103{{tuple_delimiter}}value{{tuple_delimiter}}A numerical value associated with CLG0049)
{{record_delimiter}}
("entity"{{tuple_delimiter}}No{{tuple_delimiter}}flag{{tuple_delimiter}}A binary indicator flagging a specific condition for CLG0049 as false)
{{record_delimiter}}
("entity"{{tuple_delimiter}}CLG0082{{tuple_delimiter}}ID{{tuple_delimiter}}A unique identifier for a data record)
{{record_delimiter}}
("entity"{{tuple_delimiter}}Yes{{tuple_delimiter}}flag{{tuple_delimiter}}A binary indicator flagging a specific condition for CLG0082 as true)
{{record_delimiter}}
("entity"{{tuple_delimiter}}CLG0100{{tuple_delimiter}}ID{{tuple_delimiter}}A unique identifier for a data record)
{{record_delimiter}}
("entity"{{tuple_delimiter}}No{{tuple_delimiter}}flag{{tuple_delimiter}}A binary indicator flagging a specific condition for CLG0100 as false)
{{record_delimiter}}
("entity"{{tuple_delimiter}}CLG0037{{tuple_delimiter}}ID{{tuple_delimiter}}A unique identifier for a data record, mentioned twice with different associated values)
{{record_delimiter}}
("entity"{{tuple_delimiter}}CLG0090{{tuple_delimiter}}ID{{tuple_delimiter}}A unique identifier for a data record, mentioned in both data and formulas sections)
{{record_delimiter}}
("relationship"{{tuple_delimiter}}CLG0039{{tuple_delimiter}}76{{tuple_delimiter}}The value 76 is directly associated with CLG0039{{tuple_delimiter}}10)
{{record_delimiter}}
("relationship"{{tuple_delimiter}}CLG0039{{tuple_delimiter}}Yes{{tuple_delimiter}}The flag Yes is directly associated with CLG0039 indicating a true condition{{tuple_delimiter}}10)
{{record_delimiter}}
("relationship"{{tuple_delimiter}}CLG0049{{tuple_delimiter}}103{{tuple_delimiter}}The value 103 is directly associated with CLG0049{{tuple_delimiter}}10)
{{record_delimiter}}
("relationship"{{tuple_delimiter}}CLG0049{{tuple_delimiter}}No{{tuple_delimiter}}The flag No is directly associated with CLG0049 indicating a false condition{{tuple_delimiter}}10)
{{record_delimiter}}
("relationship"{{tuple_delimiter}}CLG0082{{tuple_delimiter}}Yes{{tuple_delimiter}}The flag Yes is directly associated with CLG0082 indicating a true condition{{tuple_delimiter}}10)
{{record_delimiter}}
("relationship"{{tuple_delimiter}}CLG0100{{tuple_delimiter}}No{{tuple_delimiter}}The flag No is directly associated with CLG0100 indicating a false condition{{tuple_delimiter}}10)
{{record_delimiter}}
("relationship"{{tuple_delimiter}}CLG0037{{tuple_delimiter}}No{{tuple_delimiter}}The flag No is associated with CLG0037 indicating a false condition in both instances it is mentioned{{tuple_delimiter}}10)
{{record_delimiter}}
("relationship"{{tuple_delimiter}}CLG0090{{tuple_delimiter}}No{{tuple_delimiter}}The flag No is associated with CLG0090 indicating a false condition, and it is mentioned in both data and formulas sections{{tuple_delimiter}}10)
{{completion_delimiter}}
#############################


Example 2:

entity_types: [ID, value, flag, metric, binary indicator]
text:
.39 [C6347]\t5.34 [D6347]\t1 [E6347]\tYes [F6347]\t0 [G6347]\t8 [H6347]\t3 [I6347]\tNo [J6347]",
            "CLG0079 [A6348]\t93 [B6348]\t5.06 [C6348]\t5.2 [D6348]\t2 [E6348]\tYes [F6348]\t0 [G6348]\t3 [H6348]\t1 [I6348]\tNo [J6348]",
            "CLG0006 [A6349]\t119 [B6349]\t6.44 [C6349]\t6.13 [D6349]\t10 [E6349]\tYes [F6349]\t3 [G6349]\t5 [H6349]\t4 [I6349]\tNo [J6349]",
            "CLG0016 [A6350]\t82 [B6350]\t5.05 [C6350]\t5.13 [D6350]\t6 [E6350]\tNo [F6350]\t2 [G6350]\t3 [H6350]\t1 [I6350]\tNo [J6350]"
          ],
          "formulas": [
            "Row6301: R1:CLG0045",
            "Row6302: R1:CLG0037",
            "Row6303: R1:CLG0043",
            "Row6304: R1:CLG0073",
            "Row6305: R1:CLG0073",
            "Row6306: R1:CLG0076",
            "Row6307: R1:CLG0028",
            "Row6308: R1:CLG0071",
            "Row6309: R1:CLG0060",
            "Row6310: R1:CLG0064",
            "Row6311: R1:CLG0060",
            "Row6312: R1:CLG0099",
            "Row6313: R1:CLG0036",
            "Row6314: R1:CLG0047",
            "Row6315: R1:CLG0038",
            "Row6316: R1:CLG0065",
            "Row6317: R1:CLG0034",
            "Row6318: R1:CLG0022",
            "Row6319: R1:CLG0094",
            "Row6320: R1:CLG0084",
            "Row6321: R1:CLG0051",
            "Row6322: R1:CLG0072",
            "Row6323: R1:CLG0045",
            "Row6324: R1:CLG0071",
            "Row6325: R1:CLG0002",
            "Row6326: R1:CLG0058",
            "Row6327: R1:CLG0094",
            "Row6328: R1:CLG0012",
            "Row6329: R1:CLG0100",
            "Row6330: R1:CLG0027",
            "Row6331: R1:CLG0098",
            "Row6332: R1:CLG0038",
            "Row6333: R1:CLG0075",
            "Row6334: R1:CLG0020",
            "Row6335: R1:CLG0094",
            "Row6336: R1:CLG0043",
            "Row6337: R1:CLG0032",
            "Row6338: R1:CLG0090",
            "Row6339: R1:CLG0023",
            "Row6340: R1:CLG0041",
            "Row6341: R1:CLG0088",
            "Row6342: R1:CLG0002",
            "Row6343: R1:CLG0062",
            "Row6344: R1:CLG0096",
            "Row6345: R1:CLG0053",
            "Row6346: R1:CLG0057",
            "Row6347: R1:CLG0048",
            "Row6348: R1:CLG0079",
            "Row6349: R1:CLG0006",
            "Row6350: R1:CLG0016"
          ],
          "chunk_number": 126
        }}}},
        "chunk_127": {{{{
          "range": "A6351:A6400",
          "start_row": 6351,
          "end_row": 6400,
          "summary": "Data contains information on various items with attributes including ID, values, and flags.",
          "context": "Each row represents an item with metrics such as scores, counts, and binary indicators.",
          "table": [
            "CLG0011 [A6351]\t89 [B6351]\t6.15 [C6351]\t6.18 [D6351]\t2 [E6351]\tYes [F6351]\t10 [G6351]\t4 [H6351]\t0 [I6351]\tNo [J6351]",
            "CLG0046 [A6352]\t141 [B6352]\t7.1 [C635
------------------------
output:
("entity"{{tuple_delimiter}}CLG0079{{tuple_delimiter}}ID{{tuple_delimiter}}Identifier for a data record)
{{record_delimiter}}
("entity"{{tuple_delimiter}}93{{tuple_delimiter}}value{{tuple_delimiter}}Value associated with CLG0079 in some metric)
{{record_delimiter}}
("entity"{{tuple_delimiter}}5.06{{tuple_delimiter}}metric{{tuple_delimiter}}Metric value for CLG0079)
{{record_delimiter}}
("entity"{{tuple_delimiter}}Yes{{tuple_delimiter}}binary indicator{{tuple_delimiter}}Binary indicator associated with CLG0079, indicating a positive condition)
{{record_delimiter}}
("entity"{{tuple_delimiter}}CLG0006{{tuple_delimiter}}ID{{tuple_delimiter}}Identifier for another data record)
{{record_delimiter}}
("entity"{{tuple_delimiter}}119{{tuple_delimiter}}value{{tuple_delimiter}}Value associated with CLG0006 in some metric)
{{record_delimiter}}
("entity"{{tuple_delimiter}}6.44{{tuple_delimiter}}metric{{tuple_delimiter}}Metric value for CLG0006)
{{record_delimiter}}
("entity"{{tuple_delimiter}}No{{tuple_delimiter}}binary indicator{{tuple_delimiter}}Binary indicator associated with CLG0006, indicating a negative condition)
{{record_delimiter}}
("entity"{{tuple_delimiter}}CLG0016{{tuple_delimiter}}ID{{tuple_delimiter}}Identifier for another data record)
{{record_delimiter}}
("entity"{{tuple_delimiter}}82{{tuple_delimiter}}value{{tuple_delimiter}}Value associated with CLG0016 in some metric)
{{record_delimiter}}
("entity"{{tuple_delimiter}}5.05{{tuple_delimiter}}metric{{tuple_delimiter}}Metric value for CLG0016)
{{record_delimiter}}
("relationship"{{tuple_delimiter}}CLG0079{{tuple_delimiter}}93{{tuple_delimiter}}93 is a value associated with the ID CLG0079{{tuple_delimiter}}10)
{{record_delimiter}}
("relationship"{{tuple_delimiter}}CLG0079{{tuple_delimiter}}5.06{{tuple_delimiter}}5.06 is a metric value associated with the ID CLG0079{{tuple_delimiter}}10)
{{record_delimiter}}
("relationship"{{tuple_delimiter}}CLG0079{{tuple_delimiter}}Yes{{tuple_delimiter}}Yes is a binary indicator associated with the ID CLG0079{{tuple_delimiter}}10)
{{record_delimiter}}
("relationship"{{tuple_delimiter}}CLG0006{{tuple_delimiter}}119{{tuple_delimiter}}119 is a value associated with the ID CLG0006{{tuple_delimiter}}10)
{{record_delimiter}}
("relationship"{{tuple_delimiter}}CLG0006{{tuple_delimiter}}6.44{{tuple_delimiter}}6.44 is a metric value associated with the ID CLG0006{{tuple_delimiter}}10)
{{record_delimiter}}
("relationship"{{tuple_delimiter}}CLG0006{{tuple_delimiter}}No{{tuple_delimiter}}No is a binary indicator associated with the ID CLG0006{{tuple_delimiter}}10)
{{record_delimiter}}
("relationship"{{tuple_delimiter}}CLG0016{{tuple_delimiter}}82{{tuple_delimiter}}82 is a value associated with the ID CLG0016{{tuple_delimiter}}10)
{{record_delimiter}}
("relationship"{{tuple_delimiter}}CLG0016{{tuple_delimiter}}5.05{{tuple_delimiter}}5.05 is a metric value associated with the ID CLG0016{{tuple_delimiter}}10)
{{completion_delimiter}}
#############################



-Real Data-
######################
entity_types: [ID, value, flag, metric, binary indicator]
text: {input_text}
######################
output:

**Creating a Response**

In [ ]:
response = chain.invoke({"input_text": texts[10]})
print(response)

2025-10-05 01:43:00,190 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

In [ ]:
import re, os
from langchain_neo4j import Neo4jGraph

# --- Neo4j connection ---
os.environ["NEO4J_URI"] = "neo4j://127.0.0.1:7687"
os.environ["NEO4J_USERNAME"] = "neo4j"
os.environ["NEO4J_PASSWORD"] = "password"

graph = Neo4jGraph(refresh_schema=False)
graph.query("MATCH (n) DETACH DELETE n")

# --- Fixed parser ---
def parse_data(data):
    data = (
        data.replace("{tuple_delimiter}", "|")
            .replace("{record_delimiter}", "\n")
            .replace("{completion_delimiter}", "")
    )
    entities, relationships = [], []

    pattern = re.compile(r'\("([^"]+)"\|([^|]+)\|([^|]+)\|([^|)]+)(?:\|([^|)]+))?\)')
    # Groups:
    # 1 = kind ("entity" or "relationship")
    # 2.. = remaining tokens (3 or 4)

    for line in data.splitlines():
        line = line.strip()
        if not line:
            continue

        m = pattern.match(line)
        if not m:
            continue

        kind = m.group(1)
        t1, t2, t3, t4, t5 = m.groups()

        if kind == "entity":
            entities.append({
                "name": t2,
                "type": t3,
                "description": t4
            })
        elif kind == "relationship":
            relationships.append({
                "source": t2,
                "target": t3,
                "description": t4,
                "weight": t5
            })

    return entities, relationships


# --- Example input ---
data = """("entity"{tuple_delimiter}CLG0065{tuple_delimiter}ID{tuple_delimiter}Identifier for a data record)
{record_delimiter}
("entity"{tuple_delimiter}76{tuple_delimiter}value{tuple_delimiter}Value associated with CLG0065 in some metric)
{record_delimiter}
("relationship"{tuple_delimiter}CLG0095{tuple_delimiter}5.87{tuple_delimiter}5.87 is a metric value associated with the ID CLG0095{tuple_delimiter}10)
{completion_delimiter}"""
def insert_data(data):
    entities, relationships = parse_data(data)

    print("Entities:", entities)
    print("Relationships:", relationships)

    # --- Insert into Neo4j ---
    for e in entities:
        graph.query("""
            MERGE (n:Entity {name: $name})
            SET n.type = $type, n.description = $description
        """, params=e)

    for r in relationships:
        if r.get("weight") in [None, ""]:
            r['weight']= "unknown"

        graph.query("""
            MERGE (a:Entity {name: $source})
            MERGE (b:Entity {name: $target})
            MERGE (a)-[rel:RELATED_TO {description: $description, weight: $weight}]->(b)
        """, params=r)

def insert_whole_doc(chunks):
    for i,chunk in enumerate(chunks):
        response = chain.invoke({"input_text": chunk})
        insert_data(response)
        print(f"✅ Graph{i/len(chunks)} successfully inserted into Neo4j!")

insert_whole_doc(texts)
# insert_data(response)

2025-10-05 02:09:24,082 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Entities: [{'name': '1password', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly rates'}, {'name': '50/hr (4th coop)', 'type': 'value', 'description': 'Hourly rate for a 4th co-op position at 1password'}, {'name': '2023', 'type': 'value', 'description': 'Year associated with the co-op position at 1password'}, {'name': 'Abbott ADD', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly rates'}, {'name': '22.05/hr (2nd coop)', 'type': 'value', 'description': 'Hourly rate for a 2nd co-op position at Abbott ADD'}, {'name': 'Abnormal Security', 'type': 'ID', 'description': 'A company offering co-op positions with specified annual salary and relocation benefits'}, {'name': '106k USD annual prorated (~$51/hr USD)', 'type': 'value', 'description': 'Annual salary prorated to an hourly rate for a position at Abnormal Security'}, {'name': '5k relocation', 'type': 'value', 'description': 'Relocation benefit offered by Abnormal Security'}, {'name': 'Accedo', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly rates'}, {'name': '25-27/hr (3rd coop)', 'type': 'value', 'description': 'Hourly rate range for a 3rd co-op position at Accedo'}, {'name': 'Addepar', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly rates'}, {'name': '40/hr, 48/hr (5th coop)', 'type': 'value', 'description': 'Hourly rates for a 5th co-op position at Addepar'}, {'name': 'AdHawk Microsystems', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly rates and future year of employment'}, {'name': '40/hr (5th coop)', 'type': 'value', 'description': 'Hourly rate for a 5th co-op position at AdHawk Microsystems'}, {'name': '2024', 'type': 'value', 'description': 'Year associated with the co-op position at AdHawk Microsystems'}, {'name': 'Algorithms Developer', 'type': 'value', 'description': 'Position title for a co-op at AdHawk Microsystems'}, {'name': 'AGF Investments', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly rates and year of employment'}, {'name': '25/hr (2nd coop)', 'type': 'value', 'description': 'Hourly rate for a 2nd co-op position at AGF Investments'}, {'name': '2023', 'type': 'value', 'description': 'Year associated with the co-op position at AGF Investments'}, {'name': 'Web Developer (Junior)', 'type': 'value', 'description': 'Position title for a co-op at AGF Investments'}, {'name': 'AI Arena', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly rates'}, {'name': '45/hr', 'type': 'value', 'description': 'Hourly rate for a position at AI Arena'}, {'name': 'Akuna Capital', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly rates and benefits'}, {'name': '65 USD/hour', 'type': 'value', 'description': 'Hourly rate for a position at Akuna Capital'}, {'name': 'return flight + corporate housing', 'type': 'value', 'description': 'Benefits offered by Akuna Capital'}, {'name': 'Altice USA', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly rates'}, {'name': 'mid 30s/hr (6th coop)', 'type': 'value', 'description': 'Hourly rate range for a 6th co-op position at Altice USA'}, {'name': 'Amazon', 'type': 'ID', 'description': 'A company offering co-op positions with specified monthly salary and relocation benefits'}, {'name': '9138 USD/month', 'type': 'value', 'description': 'Monthly salary for a position at Amazon'}, {'name': '2425/month tax-free relocation stipend', 'type': 'value', 'description': 'Relocation stipend offered by Amazon'}, {'name': 'AMD', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly rates'}, {'name': '27/hr, ~21.88/hr (4th coop), ~29.33/hr (6th coop)', 'type': 'value', 'description': 'Hourly rates for various co-op positions at AMD'}, {'name': 'American Express', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly rates'}, {'name': '34.5/hr', 'type': 'value', 'description': 'Hourly rate for a position at American Express'}, {'name': 'ANSYS', 'type': 'ID', 'description': 'A company offering co-op positions with specified compensation structure'}, {'name': 'math coop average + 10%', 'type': 'value', 'description': 'Compensation structure for a co-op position at ANSYS'}, {'name': 'Apple', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly rates, relocation benefits, and positions'}, {'name': '42/hr USD (3A)', 'type': 'value', 'description': 'Hourly rate for a 3A co-op position at Apple'}, {'name': '3335/mo pretax relocation (3A)', 'type': 'value', 'description': 'Relocation benefit for a 3A co-op position at Apple'}, {'name': '2024', 'type': 'value', 'description': 'Year associated with the co-op position at Apple'}, {'name': 'Hardware', 'type': 'value', 'description': 'Position title for a co-op at Apple'}, {'name': 'System Level Test Engineer', 'type': 'value', 'description': 'Position title for a co-op at Apple'}]
Relationships: [{'source': '1password', 'target': '50/hr (4th coop)', 'description': '50/hr is the hourly rate for a 4th co-op position at 1password', 'weight': '10'}, {'source': '1password', 'target': '2023', 'description': '2023 is the year associated with the co-op position at 1password', 'weight': '10'}, {'source': 'Abbott ADD', 'target': '22.05/hr (2nd coop)', 'description': '22.05/hr is the hourly rate for a 2nd co-op position at Abbott ADD', 'weight': '10'}, {'source': 'Abnormal Security', 'target': '106k USD annual prorated (~$51/hr USD)', 'description': '106k USD annual prorated is the salary for a position at Abnormal Security', 'weight': '10'}, {'source': 'Abnormal Security', 'target': '5k relocation', 'description': '5k relocation is the benefit offered by Abnormal Security', 'weight': '10'}, {'source': 'Accedo', 'target': '25-27/hr (3rd coop)', 'description': '25-27/hr is the hourly rate range for a 3rd co-op position at Accedo', 'weight': '10'}, {'source': 'Addepar', 'target': '40/hr, 48/hr (5th coop)', 'description': '40/hr, 48/hr are the hourly rates for a 5th co-op position at Addepar', 'weight': '10'}, {'source': 'AdHawk Microsystems', 'target': '40/hr (5th coop)', 'description': '40/hr is the hourly rate for a 5th co-op position at AdHawk Microsystems', 'weight': '10'}, {'source': 'AdHawk Microsystems', 'target': '2024', 'description': '2024 is the year associated with the co-op position at AdHawk Microsystems', 'weight': '10'}, {'source': 'AdHawk Microsystems', 'target': 'Algorithms Developer', 'description': 'Algorithms Developer is the position title for a co-op at AdHawk Microsystems', 'weight': '10'}, {'source': 'AGF Investments', 'target': '25/hr (2nd coop)', 'description': '25/hr is the hourly rate for a 2nd co-op position at AGF Investments', 'weight': '10'}, {'source': 'AGF Investments', 'target': '2023', 'description': '2023 is the year associated with the co-op position at AGF Investments', 'weight': '10'}, {'source': 'AGF Investments', 'target': 'Web Developer (Junior)', 'description': 'Web Developer (Junior', 'weight': None}, {'source': 'AI Arena', 'target': '45/hr', 'description': '45/hr is the hourly rate for a position at AI Arena', 'weight': '10'}, {'source': 'Akuna Capital', 'target': '65 USD/hour', 'description': '65 USD/hour is the hourly rate for a position at Akuna Capital', 'weight': '10'}, {'source': 'Akuna Capital', 'target': 'return flight + corporate housing', 'description': 'Return flight + corporate housing are the benefits offered by Akuna Capital', 'weight': '10'}, {'source': 'Altice USA', 'target': 'mid 30s/hr (6th coop)', 'description': 'Mid 30s/hr is the hourly rate range for a 6th co-op position at Altice USA', 'weight': '10'}, {'source': 'Amazon', 'target': '9138 USD/month', 'description': '9138 USD/month is the monthly salary for a position at Amazon', 'weight': '10'}, {'source': 'Amazon', 'target': '2425/month tax-free relocation stipend', 'description': '2425/month tax-free relocation stipend is the benefit offered by Amazon', 'weight': '10'}, {'source': 'AMD', 'target': '27/hr, ~21.88/hr (4th coop), ~29.33/hr (6th coop)', 'description': '27/hr, ~21.88/hr, ~29.33/hr are the hourly rates for various co-op positions at AMD', 'weight': '10'}, {'source': 'American Express', 'target': '34.5/hr', 'description': '34.5/hr is the hourly rate for a position at American Express', 'weight': '10'}, {'source': 'ANSYS', 'target': 'math coop average + 10%', 'description': 'Math coop average + 10% is the compensation structure for a co-op position at ANSYS', 'weight': '10'}, {'source': 'Apple', 'target': '42/hr USD (3A)', 'description': '42/hr USD is the hourly rate for a 3A co-op position at Apple', 'weight': '10'}, {'source': 'Apple', 'target': '3335/mo pretax relocation (3A)', 'description': '3335/mo pretax relocation is the benefit for a 3A co-op position at Apple', 'weight': '10'}, {'source': 'Apple', 'target': '2024', 'description': '2024 is the year associated with the co-op position at Apple', 'weight': '10'}, {'source': 'Apple', 'target': 'Hardware', 'description': 'Hardware is the position title for a co-op at Apple', 'weight': '10'}, {'source': 'Apple', 'target': 'System Level Test Engineer', 'description': 'System Level Test Engineer is the position title for a co-op at Apple', 'weight': '10'}]
✅ Graph successfully inserted into Neo4j!

2025-10-05 02:09:44,453 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Entities: [{'name': 'Arctic Wolf', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly rates for different co-op years'}, {'name': '36/hr', 'type': 'value', 'description': 'Hourly rate for 3rd co-op at Arctic Wolf'}, {'name': '42/hr', 'type': 'value', 'description': 'Hourly rate for 4th co-op at Arctic Wolf'}, {'name': '2023', 'type': 'value', 'description': 'Year associated with the compensation rate at Arctic Wolf'}, {'name': 'Aterlo Networks', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly rates'}, {'name': '30/hr', 'type': 'value', 'description': 'Hourly rate for 4th co-op at Aterlo Networks'}, {'name': 'Athelas', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly rates and additional benefits'}, {'name': '33/hr USD', 'type': 'value', 'description': 'Hourly rate for co-op at Athelas in USD'}, {'name': '1200/mo USD housing stipend', 'type': 'value', 'description': 'Monthly housing stipend for 2nd co-op at Athelas in USD'}, {'name': 'Athos', 'type': 'ID', 'description': 'A company offering co-op positions with specified monthly compensation'}, {'name': '5000 USD/mo', 'type': 'value', 'description': 'Monthly compensation rate at Athos in USD'}, {'name': 'Atolio', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly rates for different co-op years'}, {'name': '34/hr', 'type': 'value', 'description': 'Hourly rate for 3rd co-op at Atolio'}, {'name': '38/hr', 'type': 'value', 'description': 'Hourly rate for 4th and 5th co-op at Atolio'}, {'name': '42/hr', 'type': 'value', 'description': 'Hourly rate for 6th co-op at Atolio'}, {'name': 'ATS Corporation', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly rates'}, {'name': '28/hr', 'type': 'value', 'description': 'Hourly rate for 5th year co-op at ATS Corporation'}, {'name': 'Autodesk', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly rates'}, {'name': '34/hr', 'type': 'value', 'description': 'Hourly rate for 5th co-op at Autodesk'}, {'name': '2024', 'type': 'value', 'description': 'Year associated with the compensation rate at Autodesk'}, {'name': 'Autonomic', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly rates for different co-op years'}, {'name': '38-40/hr', 'type': 'value', 'description': 'Hourly rate range for 4th co-op at Autonomic'}, {'name': '41/hr', 'type': 'value', 'description': 'Hourly rate for 5th co-op at Autonomic'}, {'name': 'Axonify', 'type': 'ID', 'description': 'A company offering co-op positions with specified weekly compensation'}, {'name': '1100/week', 'type': 'value', 'description': 'Weekly compensation rate for 4th co-op at Axonify'}, {'name': 'Bank of America', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly rates'}, {'name': '22/hr', 'type': 'value', 'description': 'Hourly rate for 2nd co-op at Bank of America'}, {'name': 'Bank of America (Merrill Lynch)', 'type': 'ID', 'description': 'A division of Bank of America offering co-op positions with specified hourly rates'}, {'name': '20/hr', 'type': 'value', 'description': 'Hourly rate for 1st co-op at Bank of America (Merrill Lynch'}, {'name': 'BDO', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly rates for different co-op years'}, {'name': '34.36/hr', 'type': 'value', 'description': 'Hourly rate for co-op at BDO'}, {'name': '25/h', 'type': 'value', 'description': 'Hourly rate for 2nd co-op at BDO'}, {'name': '32/h', 'type': 'value', 'description': 'Hourly rate for 3rd co-op at BDO'}, {'name': 'Bentley Systems', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly rates for different co-op years'}, {'name': '30/hr', 'type': 'value', 'description': 'Hourly rate for 1st co-op at Bentley Systems'}, {'name': '33/hr', 'type': 'value', 'description': 'Hourly rate for 2nd co-op at Bentley Systems'}, {'name': 'BETS Program', 'type': 'ID', 'description': 'A program offering co-op positions with specified stipend'}, {'name': '3000 stipend', 'type': 'value', 'description': 'Stipend amount for co-op at BETS Program'}, {'name': 'BetterUp', 'type': 'ID', 'description': 'A company offering co-op positions with specified monthly compensation'}, {'name': '8500/mo', 'type': 'value', 'description': 'Monthly compensation rate at BetterUp'}, {'name': 'Bitbuy', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly rates'}, {'name': '20/hr', 'type': 'value', 'description': 'Hourly rate for 1st co-op at Bitbuy'}, {'name': '10,000/mo', 'type': 'value', 'description': 'Monthly compensation rate at Bitbuy'}, {'name': 'Blackberry', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly rates'}, {'name': '~21/hr', 'type': 'value', 'description': 'Approximate hourly rate for co-op at Blackberry'}]
Relationships: [{'source': 'Arctic Wolf', 'target': '36/hr', 'description': '36/hr is the hourly rate for 3rd co-op at Arctic Wolf', 'weight': '10'}, {'source': 'Arctic Wolf', 'target': '42/hr', 'description': '42/hr is the hourly rate for 4th co-op at Arctic Wolf', 'weight': '10'}, {'source': 'Arctic Wolf', 'target': '2023', 'description': '2023 is the year associated with the compensation rate at Arctic Wolf', 'weight': '10'}, {'source': 'Aterlo Networks', 'target': '30/hr', 'description': '30/hr is the hourly rate for 4th co-op at Aterlo Networks', 'weight': '10'}, {'source': 'Athelas', 'target': '33/hr USD', 'description': '33/hr USD is the hourly rate for co-op at Athelas', 'weight': '10'}, {'source': 'Athelas', 'target': '1200/mo USD housing stipend', 'description': '1200/mo USD housing stipend is an additional benefit for 2nd co-op at Athelas', 'weight': '10'}, {'source': 'Athos', 'target': '5000 USD/mo', 'description': '5000 USD/mo is the monthly compensation rate at Athos', 'weight': '10'}, {'source': 'Atolio', 'target': '34/hr', 'description': '34/hr is the hourly rate for 3rd co-op at Atolio', 'weight': '10'}, {'source': 'Atolio', 'target': '38/hr', 'description': '38/hr is the hourly rate for 4th and 5th co-op at Atolio', 'weight': '10'}, {'source': 'Atolio', 'target': '42/hr', 'description': '42/hr is the hourly rate for 6th co-op at Atolio', 'weight': '10'}, {'source': 'ATS Corporation', 'target': '28/hr', 'description': '28/hr is the hourly rate for 5th year co-op at ATS Corporation', 'weight': '10'}, {'source': 'Autodesk', 'target': '34/hr', 'description': '34/hr is the hourly rate for 5th co-op at Autodesk', 'weight': '10'}, {'source': 'Autodesk', 'target': '2024', 'description': '2024 is the year associated with the compensation rate at Autodesk', 'weight': '10'}, {'source': 'Autonomic', 'target': '38-40/hr', 'description': '38-40/hr is the hourly rate range for 4th co-op at Autonomic', 'weight': '10'}, {'source': 'Autonomic', 'target': '41/hr', 'description': '41/hr is the hourly rate for 5th co-op at Autonomic', 'weight': '10'}, {'source': 'Axonify', 'target': '1100/week', 'description': '1100/week is the weekly compensation rate for 4th co-op at Axonify', 'weight': '10'}, {'source': 'Bank of America', 'target': '22/hr', 'description': '22/hr is the hourly rate for 2nd co-op at Bank of America', 'weight': '10'}, {'source': 'Bank of America (Merrill Lynch)', 'target': '20/hr', 'description': '20/hr is the hourly rate for 1st co-op at Bank of America (Merrill Lynch', 'weight': None}, {'source': 'BDO', 'target': '34.36/hr', 'description': '34.36/hr is the hourly rate for co-op at BDO', 'weight': '10'}, {'source': 'BDO', 'target': '25/h', 'description': '25/h is the hourly rate for 2nd co-op at BDO', 'weight': '10'}, {'source': 'BDO', 'target': '32/h', 'description': '32/h is the hourly rate for 3rd co-op at BDO', 'weight': '10'}, {'source': 'Bentley Systems', 'target': '30/hr', 'description': '30/hr is the hourly rate for 1st co-op at Bentley Systems', 'weight': '10'}, {'source': 'Bentley Systems', 'target': '33/hr', 'description': '33/hr is the hourly rate for 2nd co-op at Bentley Systems', 'weight': '10'}, {'source': 'BETS Program', 'target': '3000 stipend', 'description': '3000 stipend is the stipend amount for co-op at BETS Program', 'weight': '10'}, {'source': 'BetterUp', 'target': '8500/mo', 'description': '8500/mo is the monthly compensation rate at BetterUp', 'weight': '10'}, {'source': 'Bitbuy', 'target': '20/hr', 'description': '20/hr is the hourly rate for 1st co-op at Bitbuy', 'weight': '10'}, {'source': 'Bitbuy', 'target': '10,000/mo', 'description': '10,000/mo is the monthly compensation rate at Bitbuy', 'weight': '10'}, {'source': 'Blackberry', 'target': '~21/hr', 'description': '~21/hr is the approximate hourly rate for co-op at Blackberry', 'weight': '10'}]
✅ Graph successfully inserted into Neo4j!

2025-10-05 02:10:05,646 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Entities: [{'name': 'bld.ai', 'type': 'ID', 'description': 'A company offering a monthly salary for co-op positions'}, {'name': '7000/mo', 'type': 'value', 'description': 'The monthly salary offered by bld.ai for co-op positions'}, {'name': 'Bloomberg', 'type': 'ID', 'description': 'A company offering an hourly rate and stipend for co-op positions'}, {'name': '48/hr', 'type': 'value', 'description': 'The hourly rate offered by Bloomberg for co-op positions'}, {'name': '5100 stipend', 'type': 'value', 'description': 'The stipend offered by Bloomberg for the 5th co-op position'}, {'name': 'Bloq', 'type': 'ID', 'description': 'A company offering monthly salaries and benefits for co-op positions'}, {'name': '5.4k/mo', 'type': 'value', 'description': 'The monthly salary offered by Bloq for the 2nd co-op position'}, {'name': '6.2k/mo', 'type': 'value', 'description': 'The monthly salary offered by Bloq for the 3rd co-op position'}, {'name': '950/mo benefits', 'type': 'value', 'description': 'The monthly benefits offered by Bloq for the 2nd and 3rd co-op positions'}, {'name': 'Bluescape', 'type': 'ID', 'description': 'A company offering an hourly rate for co-op positions'}, {'name': '34/hr', 'type': 'value', 'description': 'The hourly rate offered by Bluescape for the 6th co-op position'}, {'name': 'BMO Business Analyst (2A)', 'type': 'ID', 'description': 'A role at BMO offering an hourly rate for co-op positions'}, {'name': '24/hr', 'type': 'value', 'description': 'The hourly rate offered by BMO for the Business Analyst (2A'}, {'name': 'BMO Product Analyst', 'type': 'ID', 'description': 'A role at BMO offering an hourly rate for co-op positions'}, {'name': '28/hr', 'type': 'value', 'description': 'The hourly rate offered by BMO for the Product Analyst co-op position'}, {'name': 'BMO Software Developer', 'type': 'ID', 'description': 'A role at BMO offering an hourly rate for co-op positions'}, {'name': '29.50/hr', 'type': 'value', 'description': 'The hourly rate offered by BMO for the Software Developer co-op position'}, {'name': 'Bolt', 'type': 'ID', 'description': 'A company offering an hourly rate for co-op positions'}, {'name': '56 USD/hr', 'type': 'value', 'description': 'The hourly rate offered by Bolt for co-op positions'}, {'name': 'Bonfire Interactive', 'type': 'ID', 'description': 'A company offering an hourly rate for co-op positions'}, {'name': '24/hr', 'type': 'value', 'description': 'The hourly rate offered by Bonfire Interactive for the 2nd co-op position'}, {'name': 'Boosted.AI', 'type': 'ID', 'description': 'A company offering an hourly rate for co-op positions'}, {'name': '35/hr', 'type': 'value', 'description': 'The hourly rate offered by Boosted.AI for co-op positions'}, {'name': 'Borrowell', 'type': 'ID', 'description': 'A company offering an hourly rate for co-op positions'}, {'name': '35/hr', 'type': 'value', 'description': 'The hourly rate offered by Borrowell for the mobile developer co-op position'}, {'name': 'Brookfield Annuity', 'type': 'ID', 'description': 'A company offering an hourly rate for co-op positions'}, {'name': '35/hr', 'type': 'value', 'description': 'The hourly rate offered by Brookfield Annuity for co-op positions'}, {'name': 'Brookfield Renewables', 'type': 'ID', 'description': 'A company offering an hourly rate for co-op positions'}, {'name': '26/hr', 'type': 'value', 'description': 'The hourly rate offered by Brookfield Renewables for co-op positions'}, {'name': 'BusPlanner', 'type': 'ID', 'description': 'A company offering average co-op compensation'}, {'name': 'CAAT Pension Plan', 'type': 'ID', 'description': 'A company offering an hourly rate for co-op positions'}, {'name': '18/hr', 'type': 'value', 'description': 'The hourly rate offered by CAAT Pension Plan for the 2nd co-op position'}, {'name': 'Canadian Food Inspection Agency (Full Stack Dev)', 'type': 'ID', 'description': 'A role offering an hourly rate for co-op positions'}, {'name': '24.77/hr', 'type': 'value', 'description': 'The hourly rate offered by the Canadian Food Inspection Agency for the Full Stack Developer co-op position'}, {'name': 'Capital1', 'type': 'ID', 'description': 'A company offering an hourly rate and signing bonus for co-op positions'}, {'name': '40/hr', 'type': 'value', 'description': 'The hourly rate offered by Capital1 for the 5th co-op position'}, {'name': '$1000 signing bonus', 'type': 'value', 'description': 'The signing bonus offered by Capital1 for co-op positions'}, {'name': 'Carta', 'type': 'ID', 'description': 'A company offering an hourly rate and weekly salary for co-op positions'}, {'name': '30.75/hr', 'type': 'value', 'description': 'The hourly rate offered by Carta for the 4th co-op position'}, {'name': '1230-1400/week', 'type': 'value', 'description': 'The weekly salary range offered by Carta for co-op positions'}]
Relationships: [{'source': 'bld.ai', 'target': '7000/mo', 'description': 'The monthly salary of 7000 is associated with bld.ai', 'weight': '10'}, {'source': 'Bloomberg', 'target': '48/hr', 'description': 'The hourly rate of 48 is associated with Bloomberg', 'weight': '10'}, {'source': 'Bloomberg', 'target': '5100 stipend', 'description': 'The stipend of 5100 is associated with Bloomberg for the 5th co-op', 'weight': '10'}, {'source': 'Bloq', 'target': '5.4k/mo', 'description': 'The monthly salary of 5.4k is associated with Bloq for the 2nd co-op', 'weight': '10'}, {'source': 'Bloq', 'target': '6.2k/mo', 'description': 'The monthly salary of 6.2k is associated with Bloq for the 3rd co-op', 'weight': '10'}, {'source': 'Bloq', 'target': '950/mo benefits', 'description': 'The monthly benefits of 950 are associated with Bloq for the 2nd and 3rd co-op', 'weight': '10'}, {'source': 'Bluescape', 'target': '34/hr', 'description': 'The hourly rate of 34 is associated with Bluescape for the 6th co-op', 'weight': '10'}, {'source': 'BMO Business Analyst (2A)', 'target': '24/hr', 'description': 'The hourly rate of 24 is associated with BMO Business Analyst (2A', 'weight': None}, {'source': 'BMO Product Analyst', 'target': '28/hr', 'description': 'The hourly rate of 28 is associated with BMO Product Analyst', 'weight': '10'}, {'source': 'BMO Software Developer', 'target': '29.50/hr', 'description': 'The hourly rate of 29.50 is associated with BMO Software Developer', 'weight': '10'}, {'source': 'Bolt', 'target': '56 USD/hr', 'description': 'The hourly rate of 56 USD is associated with Bolt', 'weight': '10'}, {'source': 'Bonfire Interactive', 'target': '24/hr', 'description': 'The hourly rate of 24 is associated with Bonfire Interactive for the 2nd co-op', 'weight': '10'}, {'source': 'Boosted.AI', 'target': '35/hr', 'description': 'The hourly rate of 35 is associated with Boosted.AI', 'weight': '10'}, {'source': 'Borrowell', 'target': '35/hr', 'description': 'The hourly rate of 35 is associated with Borrowell for the mobile developer co-op', 'weight': '10'}, {'source': 'Brookfield Annuity', 'target': '35/hr', 'description': 'The hourly rate of 35 is associated with Brookfield Annuity', 'weight': '10'}, {'source': 'Brookfield Renewables', 'target': '26/hr', 'description': 'The hourly rate of 26 is associated with Brookfield Renewables', 'weight': '10'}, {'source': 'CAAT Pension Plan', 'target': '18/hr', 'description': 'The hourly rate of 18 is associated with CAAT Pension Plan for the 2nd co-op', 'weight': '10'}, {'source': 'Canadian Food Inspection Agency (Full Stack Dev)', 'target': '24.77/hr', 'description': 'The hourly rate of 24.77 is associated with the Canadian Food Inspection Agency for the Full Stack Developer co-op', 'weight': '10'}, {'source': 'Capital1', 'target': '40/hr', 'description': 'The hourly rate of 40 is associated with Capital1 for the 5th co-op', 'weight': '10'}, {'source': 'Capital1', 'target': '$1000 signing bonus', 'description': 'The signing bonus of $1000 is associated with Capital1', 'weight': '10'}, {'source': 'Carta', 'target': '30.75/hr', 'description': 'The hourly rate of 30.75 is associated with Carta for the 4th co-op', 'weight': '10'}, {'source': 'Carta', 'target': '1230-1400/week', 'description': 'The weekly salary range of 1230-1400 is associated with Carta', 'weight': '10'}]
✅ Graph successfully inserted into Neo4j!

2025-10-05 02:10:36,272 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Entities: [{'name': 'Carta', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly rates for different co-op terms'}, {'name': '40/hr', 'type': 'value', 'description': 'Hourly rate for the 4th co-op term at Carta'}, {'name': '47/hr', 'type': 'value', 'description': 'Hourly rate for the 5th co-op term at Carta'}, {'name': '2024', 'type': 'value', 'description': 'Year associated with the co-op position at Carta'}, {'name': 'Android Engineering', 'type': 'flag', 'description': 'Position or role associated with the co-op at Carta'}, {'name': 'Carfax (Dev)', 'type': 'ID', 'description': 'A company offering a co-op position with a specified hourly rate'}, {'name': '26/hr', 'type': 'value', 'description': 'Hourly rate for the 2nd co-op term at Carfax (Dev'}, {'name': 'Castleton Commodities', 'type': 'ID', 'description': 'A company offering a co-op position with a specified hourly rate'}, {'name': '38/hr', 'type': 'value', 'description': 'Hourly rate for a co-op position at Castleton Commodities'}, {'name': 'CEGN', 'type': 'ID', 'description': 'A company offering a co-op position with a specified hourly rate range'}, {'name': 'Low-Mid 20s', 'type': 'value', 'description': 'Hourly rate range for a co-op position at CEGN'}, {'name': 'C.E. McMahon Professional Corporation', 'type': 'ID', 'description': 'A company offering a co-op position with a specified hourly rate'}, {'name': '19/hr', 'type': 'value', 'description': 'Hourly rate for a co-op position at C.E. McMahon Professional Corporation'}, {'name': 'Cepton', 'type': 'ID', 'description': 'A company offering a co-op position with a specified hourly rate and housing benefit'}, {'name': '35/hr', 'type': 'value', 'description': 'Hourly rate for a co-op position at Cepton'}, {'name': '500/mo housing', 'type': 'value', 'description': 'Monthly housing benefit for a co-op position at Cepton'}, {'name': 'Cerebras Systems', 'type': 'ID', 'description': 'A company offering a co-op position with a specified hourly rate'}, {'name': '38/hr', 'type': 'value', 'description': 'Hourly rate for a co-op position at Cerebras Systems'}, {'name': 'Ceridian', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly rates for different terms'}, {'name': '32/hr', 'type': 'value', 'description': 'Hourly rate for the 3rd co-op term at Ceridian'}, {'name': '2023', 'type': 'value', 'description': 'Year associated with the co-op position at Ceridian'}, {'name': '22/hr', 'type': 'value', 'description': 'Hourly rate for a co-op position at Ceridian in 2022 and 2023'}, {'name': 'Marketing Coordinator', 'type': 'flag', 'description': 'Position or role associated with the co-op at Ceridian'}, {'name': 'Certik', 'type': 'ID', 'description': 'A company offering a remote co-op position with a specified monthly salary'}, {'name': '7000 USD/month', 'type': 'value', 'description': 'Monthly salary for the 4th co-op term at Certik'}, {'name': 'CGI', 'type': 'ID', 'description': 'A company offering a co-op position with a specified hourly rate'}, {'name': '18/hr', 'type': 'value', 'description': 'Hourly rate for the 3rd co-op term at CGI'}, {'name': 'Chisel.ai', 'type': 'ID', 'description': 'A company offering a co-op position with a specified hourly rate'}, {'name': '40/hr', 'type': 'value', 'description': 'Hourly rate for the 5th co-op term at Chisel.ai'}, {'name': 'Christie Digital Systems', 'type': 'ID', 'description': 'A company offering a co-op position with a specified hourly rate and incremental increase'}, {'name': '18/hr', 'type': 'value', 'description': 'Hourly rate for the 1st co-op term at Christie Digital Systems'}, {'name': '+2/hr every add. coop term', 'type': 'value', 'description': 'Incremental hourly rate increase for each additional co-op term at Christie Digital Systems'}, {'name': 'CIBC', 'type': 'ID', 'description': 'A company offering a co-op position with a specified compensation structure'}, {'name': 'coop average + $1', 'type': 'value', 'description': 'Compensation structure for a co-op position at CIBC'}, {'name': 'Cisco (Ottawa Office)', 'type': 'ID', 'description': 'A company offering a co-op position with a specified hourly rate and signing bonus'}, {'name': '31-33/hr', 'type': 'value', 'description': 'Hourly rate range for the 1st co-op term at Cisco (Ottawa Office'}, {'name': '2000 CAD signing bonus', 'type': 'value', 'description': 'Signing bonus for the 1st co-op term at Cisco (Ottawa Office'}, {'name': '2024', 'type': 'value', 'description': 'Year associated with the co-op position at Cisco (Ottawa Office'}, {'name': 'Cisco Meraki', 'type': 'ID', 'description': 'A company offering a co-op position with a specified hourly rate and signing bonus'}, {'name': '67/hr', 'type': 'value', 'description': 'Maximum hourly rate for a co-op position at Cisco Meraki'}, {'name': '10k signing bonus', 'type': 'value', 'description': 'Signing bonus for a co-op position at Cisco Meraki'}, {'name': 'Citadel', 'type': 'ID', 'description': 'A company offering a co-op position with a specified weekly salary'}, {'name': '3365 USD/week', 'type': 'value', 'description': 'Weekly salary for a co-op position at Citadel'}, {'name': 'Citibank', 'type': 'ID', 'description': 'A company offering a co-op position with a specified hourly rate and housing stipend'}, {'name': '44/hr', 'type': 'value', 'description': 'Hourly rate for a co-op position at Citibank'}, {'name': '2000 CAD housing stipend', 'type': 'value', 'description': 'Housing stipend for a co-op position at Citibank'}, {'name': '2024', 'type': 'value', 'description': 'Year associated with the co-op position at Citibank'}, {'name': 'Cockroach Labs', 'type': 'ID', 'description': 'A company offering a co-op position with a specified monthly salary and signing bonus'}, {'name': '8000/month', 'type': 'value', 'description': 'Monthly salary for a co-op position at Cockroach Labs'}, {'name': '1.5k signing bonus', 'type': 'value', 'description': 'Signing bonus for a co-op position at Cockroach Labs'}, {'name': 'CodeWithChris', 'type': 'ID', 'description': 'A company offering a co-op position with a specified hourly rate'}, {'name': '20/hr', 'type': 'value', 'description': 'Hourly rate for the 1st co-op term at CodeWithChris'}]
Relationships: [{'source': 'Carta', 'target': '40/hr', 'description': '40/hr is the hourly rate for the 4th co-op term at Carta', 'weight': '10'}, {'source': 'Carta', 'target': '47/hr', 'description': '47/hr is the hourly rate for the 5th co-op term at Carta', 'weight': '10'}, {'source': 'Carta', 'target': '2024', 'description': '2024 is the year associated with the co-op position at Carta', 'weight': '10'}, {'source': 'Carta', 'target': 'Android Engineering', 'description': 'Android Engineering is the position associated with the co-op at Carta', 'weight': '10'}, {'source': 'Carfax (Dev)', 'target': '26/hr', 'description': '26/hr is the hourly rate for the 2nd co-op term at Carfax (Dev', 'weight': None}, {'source': 'Castleton Commodities', 'target': '38/hr', 'description': '38/hr is the hourly rate for a co-op position at Castleton Commodities', 'weight': '10'}, {'source': 'CEGN', 'target': 'Low-Mid 20s', 'description': 'Low-Mid 20s is the hourly rate range for a co-op position at CEGN', 'weight': '10'}, {'source': 'C.E. McMahon Professional Corporation', 'target': '19/hr', 'description': '19/hr is the hourly rate for a co-op position at C.E. McMahon Professional Corporation', 'weight': '10'}, {'source': 'Cepton', 'target': '35/hr', 'description': '35/hr is the hourly rate for a co-op position at Cepton', 'weight': '10'}, {'source': 'Cepton', 'target': '500/mo housing', 'description': '500/mo housing is the monthly housing benefit for a co-op position at Cepton', 'weight': '10'}, {'source': 'Cerebras Systems', 'target': '38/hr', 'description': '38/hr is the hourly rate for a co-op position at Cerebras Systems', 'weight': '10'}, {'source': 'Ceridian', 'target': '32/hr', 'description': '32/hr is the hourly rate for the 3rd co-op term at Ceridian', 'weight': '10'}, {'source': 'Ceridian', 'target': '2023', 'description': '2023 is the year associated with the co-op position at Ceridian', 'weight': '10'}, {'source': 'Ceridian', 'target': '22/hr', 'description': '22/hr is the hourly rate for a co-op position at Ceridian in 2022 and 2023', 'weight': '10'}, {'source': 'Ceridian', 'target': 'Marketing Coordinator', 'description': 'Marketing Coordinator is the position associated with the co-op at Ceridian', 'weight': '10'}, {'source': 'Certik', 'target': '7000 USD/month', 'description': '7000 USD/month is the monthly salary for the 4th co-op term at Certik', 'weight': '10'}, {'source': 'CGI', 'target': '18/hr', 'description': '18/hr is the hourly rate for the 3rd co-op term at CGI', 'weight': '10'}, {'source': 'Chisel.ai', 'target': '40/hr', 'description': '40/hr is the hourly rate for the 5th co-op term at Chisel.ai', 'weight': '10'}, {'source': 'Christie Digital Systems', 'target': '18/hr', 'description': '18/hr is the hourly rate for the 1st co-op term at Christie Digital Systems', 'weight': '10'}, {'source': 'Christie Digital Systems', 'target': '+2/hr every add. coop term', 'description': '+2/hr every add. coop term is the incremental hourly rate increase for each additional co-op term at Christie Digital Systems', 'weight': '10'}, {'source': 'CIBC', 'target': 'coop average + $1', 'description': 'coop average + $1 is the compensation structure for a co-op position at CIBC', 'weight': '10'}, {'source': 'Cisco (Ottawa Office)', 'target': '31-33/hr', 'description': '31-33/hr is the hourly rate range for the 1st co-op term at Cisco (Ottawa Office', 'weight': None}, {'source': 'Cisco (Ottawa Office)', 'target': '2000 CAD signing bonus', 'description': '2000 CAD signing bonus is the signing bonus for the 1st co-op term at Cisco (Ottawa Office', 'weight': None}, {'source': 'Cisco (Ottawa Office)', 'target': '2024', 'description': '2024 is the year associated with the co-op position at Cisco (Ottawa Office', 'weight': None}, {'source': 'Cisco Meraki', 'target': '67/hr', 'description': '67/hr is the maximum hourly rate for a co-op position at Cisco Meraki', 'weight': '10'}, {'source': 'Cisco Meraki', 'target': '10k signing bonus', 'description': '10k signing bonus is the signing bonus for a co-op position at Cisco Meraki', 'weight': '10'}, {'source': 'Citadel', 'target': '3365 USD/week', 'description': '3365 USD/week is the weekly salary for a co-op position at Citadel', 'weight': '10'}, {'source': 'Citibank', 'target': '44/hr', 'description': '44/hr is the hourly rate for a co-op position at Citibank', 'weight': '10'}, {'source': 'Citibank', 'target': '2000 CAD housing stipend', 'description': '2000 CAD housing stipend is the housing stipend for a co-op position at Citibank', 'weight': '10'}, {'source': 'Citibank', 'target': '2024', 'description': '2024 is the year associated with the co-op position at Citibank', 'weight': '10'}, {'source': 'Cockroach Labs', 'target': '8000/month', 'description': '8000/month is the monthly salary for a co-op position at Cockroach Labs', 'weight': '10'}, {'source': 'Cockroach Labs', 'target': '1.5k signing bonus', 'description': '1.5k signing bonus is the signing bonus for a co-op position at Cockroach Labs', 'weight': '10'}, {'source': 'CodeWithChris', 'target': '20/hr', 'description': '20/hr is the hourly rate for the 1st co-op term at CodeWithChris', 'weight': '10'}]
✅ Graph successfully inserted into Neo4j!

2025-10-05 02:11:03,036 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Entities: [{'name': 'Cohere', 'type': 'ID', 'description': 'A company offering hourly compensation based on experience'}, {'name': '20-50/hr', 'type': 'value', 'description': 'Hourly compensation range offered by Cohere based on experience'}, {'name': 'Coherent Logix', 'type': 'ID', 'description': 'A company offering compensation above the co-op average'}, {'name': '$1-3 above coop average', 'type': 'value', 'description': 'Compensation offered by Coherent Logix above the co-op average'}, {'name': 'Cohesity', 'type': 'ID', 'description': 'A company offering a specific hourly rate'}, {'name': '49/hr', 'type': 'value', 'description': 'Hourly compensation offered by Cohesity'}, {'name': 'Coinbase', 'type': 'ID', 'description': 'A company offering a specific hourly rate'}, {'name': '50/hr', 'type': 'value', 'description': 'Hourly compensation offered by Coinbase'}, {'name': 'Coinsquare', 'type': 'ID', 'description': 'A company offering different hourly rates based on co-op experience'}, {'name': '28/hr', 'type': 'value', 'description': 'Hourly compensation for 1st co-op at Coinsquare'}, {'name': '44/hr', 'type': 'value', 'description': 'Hourly compensation for 5th co-op or any dev role at Coinsquare'}, {'name': 'Composer.trade', 'type': 'ID', 'description': 'A company offering monthly compensation and a stipend'}, {'name': '9000/month', 'type': 'value', 'description': 'Monthly compensation offered by Composer.trade'}, {'name': '500/month stipend', 'type': 'value', 'description': 'Monthly stipend offered by Composer.trade'}, {'name': '2024', 'type': 'value', 'description': 'Year associated with the compensation details for Composer.trade'}, {'name': 'Compound', 'type': 'ID', 'description': 'A company offering monthly compensation'}, {'name': '$10,200/month', 'type': 'value', 'description': 'Monthly compensation offered by Compound'}, {'name': 'Connected', 'type': 'ID', 'description': 'A company offering hourly compensation for a specific co-op term'}, {'name': '37/hr', 'type': 'value', 'description': 'Hourly compensation for 6th co-op at Connected'}, {'name': 'Constant Contact', 'type': 'ID', 'description': 'A company offering hourly compensation for a specific co-op term'}, {'name': '35/hr', 'type': 'value', 'description': 'Hourly compensation for 4th co-op at Constant Contact'}, {'name': '2023', 'type': 'value', 'description': 'Year associated with the compensation details for Constant Contact'}, {'name': 'The Co-operators', 'type': 'ID', 'description': 'A company offering hourly compensation for a specific co-op term'}, {'name': '~21/hr', 'type': 'value', 'description': 'Approximate hourly compensation for 1st co-op at The Co-operators'}, {'name': 'Core Avionics', 'type': 'ID', 'description': 'A company offering different hourly rates based on co-op experience'}, {'name': '20/hr', 'type': 'value', 'description': 'Hourly compensation for 1st co-op at Core Avionics'}, {'name': '30/hr', 'type': 'value', 'description': 'Hourly compensation offered by Core Avionics'}, {'name': 'Coursera', 'type': 'ID', 'description': 'A company offering monthly compensation'}, {'name': '7000/month', 'type': 'value', 'description': 'Monthly compensation offered by Coursera'}, {'name': 'Cover Technologies Inc', 'type': 'ID', 'description': 'A company offering hourly compensation in USD'}, {'name': '30 USD/hr', 'type': 'value', 'description': 'Hourly compensation offered by Cover Technologies Inc'}, {'name': 'CPP Investments', 'type': 'ID', 'description': 'A company offering different hourly rates based on co-op experience and additional benefits'}, {'name': '37/hr', 'type': 'value', 'description': 'Hourly compensation for 2nd co-op at CPP Investments'}, {'name': '4% of yearly salary (70k) as vacation pay', 'type': 'value', 'description': 'Additional benefit offered by CPP Investments'}, {'name': '2024', 'type': 'value', 'description': 'Year associated with the compensation details for CPP Investments'}, {'name': 'SWE', 'type': 'value', 'description': 'Position associated with the compensation details for CPP Investments'}, {'name': '34/hr', 'type': 'value', 'description': 'Hourly compensation for 3rd co-op at CPP Investments'}, {'name': '"Intern Engineer"', 'type': 'value', 'description': 'Position associated with the compensation details for CPP Investments'}, {'name': '48/hr', 'type': 'value', 'description': 'Hourly compensation for 4th co-op at CPP Investments'}, {'name': '"Intern Analyst"', 'type': 'value', 'description': 'Position associated with the compensation details for CPP Investments'}, {'name': 'Crawford and Co', 'type': 'ID', 'description': 'A company offering hourly compensation and a specific position'}, {'name': '20/hr', 'type': 'value', 'description': 'Hourly compensation offered by Crawford and Co'}, {'name': '2022', 'type': 'value', 'description': 'Year associated with the compensation details for Crawford and Co'}, {'name': 'Business Analyst', 'type': 'value', 'description': 'Position associated with the compensation details for Crawford and Co'}, {'name': 'Cresta', 'type': 'ID', 'description': 'A company offering hourly compensation and additional benefits'}, {'name': '40/hr', 'type': 'value', 'description': 'Hourly compensation for 5th co-op at Cresta'}, {'name': '$25/day lunch', 'type': 'value', 'description': 'Additional benefit offered by Cresta'}, {'name': '2025', 'type': 'value', 'description': 'Year associated with the compensation details for Cresta'}, {'name': 'Creospark', 'type': 'ID', 'description': 'A company offering hourly compensation'}, {'name': '18/hr', 'type': 'value', 'description': 'Hourly compensation offered by Creospark'}, {'name': 'Crypto4a', 'type': 'ID', 'description': 'A company offering hourly compensation and additional benefits for remote work'}, {'name': '40/hr', 'type': 'value', 'description': 'Hourly compensation for remote, 6th co-op at Crypto4a'}, {'name': '4 days PTO', 'type': 'value', 'description': 'Additional benefit offered by Crypto4a'}, {'name': '2024', 'type': 'value', 'description': 'Year associated with the compensation details for Crypto4a'}, {'name': 'SWE', 'type': 'value', 'description': 'Position associated with the compensation details for Crypto4a'}]
Relationships: [{'source': 'Cohere', 'target': '20-50/hr', 'description': 'The hourly compensation range 20-50/hr is associated with Cohere based on experience', 'weight': '10'}, {'source': 'Coherent Logix', 'target': '$1-3 above coop average', 'description': 'The compensation $1-3 above coop average is associated with Coherent Logix', 'weight': '10'}, {'source': 'Cohesity', 'target': '49/hr', 'description': 'The hourly compensation 49/hr is associated with Cohesity', 'weight': '10'}, {'source': 'Coinbase', 'target': '50/hr', 'description': 'The hourly compensation 50/hr is associated with Coinbase', 'weight': '10'}, {'source': 'Coinsquare', 'target': '28/hr', 'description': 'The hourly compensation 28/hr for 1st co-op is associated with Coinsquare', 'weight': '10'}, {'source': 'Coinsquare', 'target': '44/hr', 'description': 'The hourly compensation 44/hr for 5th co-op or any dev role is associated with Coinsquare', 'weight': '10'}, {'source': 'Composer.trade', 'target': '9000/month', 'description': 'The monthly compensation 9000/month is associated with Composer.trade', 'weight': '10'}, {'source': 'Composer.trade', 'target': '500/month stipend', 'description': 'The monthly stipend 500/month is associated with Composer.trade', 'weight': '10'}, {'source': 'Composer.trade', 'target': '2024', 'description': 'The year 2024 is associated with the compensation details for Composer.trade', 'weight': '10'}, {'source': 'Compound', 'target': '$10,200/month', 'description': 'The monthly compensation $10,200/month is associated with Compound', 'weight': '10'}, {'source': 'Connected', 'target': '37/hr', 'description': 'The hourly compensation 37/hr for 6th co-op is associated with Connected', 'weight': '10'}, {'source': 'Constant Contact', 'target': '35/hr', 'description': 'The hourly compensation 35/hr for 4th co-op is associated with Constant Contact', 'weight': '10'}, {'source': 'Constant Contact', 'target': '2023', 'description': 'The year 2023 is associated with the compensation details for Constant Contact', 'weight': '10'}, {'source': 'The Co-operators', 'target': '~21/hr', 'description': 'The approximate hourly compensation ~21/hr for 1st co-op is associated with The Co-operators', 'weight': '10'}, {'source': 'Core Avionics', 'target': '20/hr', 'description': 'The hourly compensation 20/hr for 1st co-op is associated with Core Avionics', 'weight': '10'}, {'source': 'Core Avionics', 'target': '30/hr', 'description': 'The hourly compensation 30/hr is associated with Core Avionics', 'weight': '10'}, {'source': 'Coursera', 'target': '7000/month', 'description': 'The monthly compensation 7000/month is associated with Coursera', 'weight': '10'}, {'source': 'Cover Technologies Inc', 'target': '30 USD/hr', 'description': 'The hourly compensation 30 USD/hr is associated with Cover Technologies Inc', 'weight': '10'}, {'source': 'CPP Investments', 'target': '37/hr', 'description': 'The hourly compensation 37/hr for 2nd co-op is associated with CPP Investments', 'weight': '10'}, {'source': 'CPP Investments', 'target': '4% of yearly salary (70k) as vacation pay', 'description': 'The additional benefit of 4% of yearly salary (70k', 'weight': None}, {'source': 'CPP Investments', 'target': '2024', 'description': 'The year 2024 is associated with the compensation details for CPP Investments', 'weight': '10'}, {'source': 'CPP Investments', 'target': 'SWE', 'description': 'The position SWE is associated with the compensation details for CPP Investments', 'weight': '10'}, {'source': 'CPP Investments', 'target': '34/hr', 'description': 'The hourly compensation 34/hr for 3rd co-op is associated with CPP Investments', 'weight': '10'}, {'source': 'CPP Investments', 'target': '"Intern Engineer"', 'description': 'The position "Intern Engineer" is associated with the compensation details for CPP Investments', 'weight': '10'}, {'source': 'CPP Investments', 'target': '48/hr', 'description': 'The hourly compensation 48/hr for 4th co-op is associated with CPP Investments', 'weight': '10'}, {'source': 'CPP Investments', 'target': '"Intern Analyst"', 'description': 'The position "Intern Analyst" is associated with the compensation details for CPP Investments', 'weight': '10'}, {'source': 'Crawford and Co', 'target': '20/hr', 'description': 'The hourly compensation 20/hr is associated with Crawford and Co', 'weight': '10'}, {'source': 'Crawford and Co', 'target': '2022', 'description': 'The year 2022 is associated with the compensation details for Crawford and Co', 'weight': '10'}, {'source': 'Crawford and Co', 'target': 'Business Analyst', 'description': 'The position Business Analyst is associated with the compensation details for Crawford and Co', 'weight': '10'}, {'source': 'Cresta', 'target': '40/hr', 'description': 'The hourly compensation 40/hr for 5th co-op is associated with Cresta', 'weight': '10'}, {'source': 'Cresta', 'target': '$25/day lunch', 'description': 'The additional benefit of $25/day lunch is associated with Cresta', 'weight': '10'}, {'source': 'Cresta', 'target': '2025', 'description': 'The year 2025 is associated with the compensation details for Cresta', 'weight': '10'}, {'source': 'Creospark', 'target': '18/hr', 'description': 'The hourly compensation 18/hr is associated with Creospark', 'weight': '10'}, {'source': 'Crypto4a', 'target': '40/hr', 'description': 'The hourly compensation 40/hr for remote, 6th co-op is associated with Crypto4a', 'weight': '10'}, {'source': 'Crypto4a', 'target': '4 days PTO', 'description': 'The additional benefit of 4 days PTO is associated with Crypto4a', 'weight': '10'}, {'source': 'Crypto4a', 'target': '2024', 'description': 'The year 2024 is associated with the compensation details for Crypto4a', 'weight': '10'}, {'source': 'Crypto4a', 'target': 'SWE', 'description': 'The position SWE is associated with the compensation details for Crypto4a', 'weight': '10'}]
✅ Graph successfully inserted into Neo4j!

2025-10-05 02:11:29,009 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Entities: [{'name': 'Cube Group', 'type': 'ID', 'description': 'A company offering hourly pay rates in USD'}, {'name': '75/hr USD', 'type': 'value', 'description': 'Hourly pay rate offered by Cube Group in USD'}, {'name': '2024', 'type': 'value', 'description': 'Year associated with the pay rate for Cube Group'}, {'name': 'Curinos', 'type': 'ID', 'description': 'A company offering hourly pay rates'}, {'name': '34/hr (2b)', 'type': 'value', 'description': 'Hourly pay rate offered by Curinos, with a specific condition noted as 2b'}, {'name': 'Curvegrid (Japan)', 'type': 'ID', 'description': 'A company based in Japan offering monthly pay rates'}, {'name': '¥300,000/mo (2nd coop)', 'type': 'value', 'description': 'Monthly pay rate offered by Curvegrid in Japanese Yen, applicable for the second co-op term'}, {'name': 'D2L', 'type': 'ID', 'description': 'A company offering hourly pay rates'}, {'name': '28/hr', 'type': 'value', 'description': 'Hourly pay rate offered by D2L'}, {'name': 'Databrick', 'type': 'ID', 'description': 'A company offering hourly pay rates in CAD and additional housing benefits'}, {'name': '55 CAD/hr', 'type': 'value', 'description': 'Hourly pay rate offered by Databrick in Canadian Dollars'}, {'name': '1.3k/mo housing', 'type': 'value', 'description': 'Monthly housing benefit offered by Databrick'}, {'name': 'Datadog', 'type': 'ID', 'description': 'A company offering hourly pay rates and monthly housing benefits in USD'}, {'name': '40/hr', 'type': 'value', 'description': 'Hourly pay rate offered by Datadog'}, {'name': '2000 USD/mo housing', 'type': 'value', 'description': 'Monthly housing benefit offered by Datadog in USD'}, {'name': 'data.world', 'type': 'ID', 'description': 'A company offering weekly pay rates and remote stipends in USD'}, {'name': '1400 USD/week', 'type': 'value', 'description': 'Weekly pay rate offered by data.world in USD'}, {'name': '100 USD remote stipend', 'type': 'value', 'description': 'Remote work stipend offered by data.world in USD'}, {'name': 'Deep Breathe', 'type': 'ID', 'description': 'A company offering pay rates based on co-op averages'}, {'name': 'co-op average + 20%', 'type': 'value', 'description': 'Pay rate offered by Deep Breathe, calculated as 20% above the co-op average'}, {'name': 'Deep Genomics', 'type': 'ID', 'description': 'A company offering annual salary rates'}, {'name': '60k/yr', 'type': 'value', 'description': 'Annual salary offered by Deep Genomics'}, {'name': 'DeepHaven', 'type': 'ID', 'description': 'A company offering hourly pay rates that increase with work term'}, {'name': '32-38/hr', 'type': 'value', 'description': 'Hourly pay rate range offered by DeepHaven, with increases based on work term'}, {'name': '2024', 'type': 'value', 'description': 'Year associated with the pay rate for DeepHaven'}, {'name': 'Dejero', 'type': 'ID', 'description': 'A company offering pay rates based on co-op averages'}, {'name': '1.15*coop average', 'type': 'value', 'description': 'Pay rate offered by Dejero, calculated as 1.15 times the co-op average'}, {'name': 'Deloitte', 'type': 'ID', 'description': 'A company offering hourly pay rates'}, {'name': '25-28/hr', 'type': 'value', 'description': 'Hourly pay rate range offered by Deloitte'}, {'name': 'Delphia Asset Management', 'type': 'ID', 'description': 'A company offering pay rates above co-op averages'}, {'name': '5-10% above the coop average', 'type': 'value', 'description': 'Pay rate offered by Delphia Asset Management, calculated as 5-10% above the co-op average'}, {'name': 'Digitaled', 'type': 'ID', 'description': 'A company offering pay rates based on co-op averages'}, {'name': 'Coop average', 'type': 'value', 'description': 'Pay rate offered by Digitaled, based on the co-op average'}, {'name': 'Digital Extremes (Marketing)', 'type': 'ID', 'description': 'A company offering hourly pay rates for marketing roles'}, {'name': '20/hr (2nd coop)', 'type': 'value', 'description': 'Hourly pay rate offered by Digital Extremes for the second co-op term'}, {'name': 'DocuSign', 'type': 'ID', 'description': 'A company offering hourly pay rates'}, {'name': '52/hr', 'type': 'value', 'description': 'Hourly pay rate offered by DocuSign'}, {'name': 'Draper', 'type': 'ID', 'description': 'A company offering weekly pay rates'}, {'name': '1400/wk', 'type': 'value', 'description': 'Weekly pay rate offered by Draper'}, {'name': 'Dreamschools', 'type': 'ID', 'description': 'A company offering hourly pay rates'}, {'name': '19-24/hr', 'type': 'value', 'description': 'Hourly pay rate range offered by Dreamschools'}, {'name': 'Dropbase (Castodia)', 'type': 'ID', 'description': 'A company offering hourly pay rates with increases per work term'}, {'name': '(25-50/hr, +5 per work term), 29/hr for 3rd coop, 30-32/hr for 4/5th coop', 'type': 'value', 'description': 'Hourly pay rate structure offered by Dropbase, with specific rates for different co-op terms'}, {'name': 'DRW', 'type': 'ID', 'description': 'A company offering hourly pay rates'}, {'name': '35-37/hr', 'type': 'value', 'description': 'Hourly pay rate range offered by DRW'}]
Relationships: [{'source': 'Cube Group', 'target': '75/hr USD', 'description': '75/hr USD is the hourly pay rate associated with Cube Group', 'weight': '10'}, {'source': 'Cube Group', 'target': '2024', 'description': '2024 is the year associated with the pay rate for Cube Group', 'weight': '5'}, {'source': 'Curinos', 'target': '34/hr (2b)', 'description': '34/hr (2b', 'weight': None}, {'source': 'Curvegrid (Japan)', 'target': '¥300,000/mo (2nd coop)', 'description': '¥300,000/mo (2nd coop', 'weight': None}, {'source': 'D2L', 'target': '28/hr', 'description': '28/hr is the hourly pay rate associated with D2L', 'weight': '10'}, {'source': 'Databrick', 'target': '55 CAD/hr', 'description': '55 CAD/hr is the hourly pay rate associated with Databrick', 'weight': '10'}, {'source': 'Databrick', 'target': '1.3k/mo housing', 'description': '1.3k/mo housing is the monthly housing benefit associated with Databrick', 'weight': '8'}, {'source': 'Datadog', 'target': '40/hr', 'description': '40/hr is the hourly pay rate associated with Datadog', 'weight': '10'}, {'source': 'Datadog', 'target': '2000 USD/mo housing', 'description': '2000 USD/mo housing is the monthly housing benefit associated with Datadog', 'weight': '8'}, {'source': 'data.world', 'target': '1400 USD/week', 'description': '1400 USD/week is the weekly pay rate associated with data.world', 'weight': '10'}, {'source': 'data.world', 'target': '100 USD remote stipend', 'description': '100 USD remote stipend is the remote work benefit associated with data.world', 'weight': '7'}, {'source': 'Deep Breathe', 'target': 'co-op average + 20%', 'description': 'co-op average + 20% is the pay rate structure associated with Deep Breathe', 'weight': '9'}, {'source': 'Deep Genomics', 'target': '60k/yr', 'description': '60k/yr is the annual salary associated with Deep Genomics', 'weight': '10'}, {'source': 'DeepHaven', 'target': '32-38/hr', 'description': '32-38/hr is the hourly pay rate range associated with DeepHaven', 'weight': '10'}, {'source': 'DeepHaven', 'target': '2024', 'description': '2024 is the year associated with the pay rate for DeepHaven', 'weight': '5'}, {'source': 'Dejero', 'target': '1.15*coop average', 'description': '1.15*coop average is the pay rate structure associated with Dejero', 'weight': '9'}, {'source': 'Deloitte', 'target': '25-28/hr', 'description': '25-28/hr is the hourly pay rate range associated with Deloitte', 'weight': '10'}, {'source': 'Delphia Asset Management', 'target': '5-10% above the coop average', 'description': '5-10% above the coop average is the pay rate structure associated with Delphia Asset Management', 'weight': '9'}, {'source': 'Digitaled', 'target': 'Coop average', 'description': 'Coop average is the pay rate structure associated with Digitaled', 'weight': '9'}, {'source': 'Digital Extremes (Marketing)', 'target': '20/hr (2nd coop)', 'description': '20/hr (2nd coop', 'weight': None}, {'source': 'DocuSign', 'target': '52/hr', 'description': '52/hr is the hourly pay rate associated with DocuSign', 'weight': '10'}, {'source': 'Draper', 'target': '1400/wk', 'description': '1400/wk is the weekly pay rate associated with Draper', 'weight': '10'}, {'source': 'Dreamschools', 'target': '19-24/hr', 'description': '19-24/hr is the hourly pay rate range associated with Dreamschools', 'weight': '10'}, {'source': 'Dropbase (Castodia)', 'target': '(25-50/hr, +5 per work term), 29/hr for 3rd coop, 30-32/hr for 4/5th coop', 'description': '(25-50/hr, +5 per work term', 'weight': None}, {'source': 'DRW', 'target': '35-37/hr', 'description': '35-37/hr is the hourly pay rate range associated with DRW', 'weight': '10'}]
✅ Graph successfully inserted into Neo4j!

2025-10-05 02:11:50,818 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Entities: [{'name': 'Durovac', 'type': 'ID', 'description': 'A company offering a co-op position with a specified hourly rate'}, {'name': '23/hr', 'type': 'value', 'description': 'The hourly compensation rate for a 4th co-op position at Durovac'}, {'name': 'Ecobee', 'type': 'ID', 'description': 'A company offering co-op positions with varying hourly rates depending on the term'}, {'name': '36-41/hr', 'type': 'value', 'description': 'The hourly compensation range for a 4th co-op position at Ecobee'}, {'name': '43/hr', 'type': 'value', 'description': 'The hourly compensation rate for a 5th co-op position at Ecobee'}, {'name': '2024', 'type': 'value', 'description': 'The year associated with the co-op position at Ecobee'}, {'name': 'Ecompliance', 'type': 'ID', 'description': 'A company offering a co-op position with a specified hourly rate'}, {'name': '26/hr', 'type': 'value', 'description': 'The hourly compensation rate for a 4th co-op position at Ecompliance'}, {'name': 'Elekta', 'type': 'ID', 'description': 'A company offering a co-op position with a specified hourly rate'}, {'name': '27/hr', 'type': 'value', 'description': 'The hourly compensation rate for a 2A co-op position at Elekta'}, {'name': 'Embark Trucks', 'type': 'ID', 'description': 'A company offering a co-op position with a specified monthly rate'}, {'name': '10k/month', 'type': 'value', 'description': 'The monthly compensation rate for a co-op position at Embark Trucks, with currency depending on location'}, {'name': 'Enzuzo', 'type': 'ID', 'description': 'A company offering a co-op position with a specified hourly rate'}, {'name': '28/hr', 'type': 'value', 'description': 'The hourly compensation rate for a 3rd co-op position at Enzuzo'}, {'name': '2024', 'type': 'value', 'description': 'The year associated with the co-op position at Enzuzo'}, {'name': 'Fullstack', 'type': 'position', 'description': 'The role associated with the co-op position at Enzuzo'}, {'name': 'The Empire Life Insurance Company', 'type': 'ID', 'description': 'A company offering co-op positions with varying hourly rates based on work term'}, {'name': '22-28/hr', 'type': 'value', 'description': 'The hourly compensation range for co-op positions at The Empire Life Insurance Company'}, {'name': 'Enlighted Inc', 'type': 'ID', 'description': 'A company offering a co-op position with a specified hourly rate'}, {'name': '36/hr', 'type': 'value', 'description': 'The hourly compensation rate for a 5th co-op position at Enlighted Inc'}, {'name': 'Eon Media', 'type': 'ID', 'description': 'A company offering a co-op position with a specified monthly rate'}, {'name': '3800/mo', 'type': 'value', 'description': 'The monthly compensation rate for a 3rd-year co-op position at Eon Media'}, {'name': 'Equifax D&A', 'type': 'ID', 'description': 'A company offering a co-op position with a specified hourly rate'}, {'name': '22/hr', 'type': 'value', 'description': 'The hourly compensation rate for a 1st co-op position at Equifax D&A'}, {'name': 'Equitable Life Insurance Company', 'type': 'ID', 'description': 'A company offering co-op positions with varying hourly rates'}, {'name': '20/hr', 'type': 'value', 'description': 'The hourly compensation rate for a co-op position at Equitable Life Insurance Company'}, {'name': '23/hr', 'type': 'value', 'description': 'The hourly compensation rate for a 2nd co-op position at Equitable Life Insurance Company'}, {'name': 'ESCRYPT', 'type': 'ID', 'description': 'A company offering co-op positions with varying hourly rates'}, {'name': '26/hr', 'type': 'value', 'description': 'The hourly compensation rate for a 3rd co-op position at ESCRYPT'}, {'name': '30/hr', 'type': 'value', 'description': 'The hourly compensation rate for a 4th co-op position at ESCRYPT'}, {'name': 'eSentire', 'type': 'ID', 'description': 'A company offering a co-op position with a specified hourly rate'}, {'name': '24.50/hr', 'type': 'value', 'description': 'The hourly compensation rate for a co-op position at eSentire'}, {'name': 'ETHGlobal', 'type': 'ID', 'description': 'A company offering a co-op position with a specified monthly rate and stipend'}, {'name': '9000/month', 'type': 'value', 'description': 'The monthly compensation rate for a co-op position at ETHGlobal'}, {'name': '500/month stipend', 'type': 'value', 'description': 'The monthly stipend associated with the co-op position at ETHGlobal'}, {'name': '2024', 'type': 'value', 'description': 'The year associated with the co-op position at ETHGlobal'}, {'name': 'EY', 'type': 'ID', 'description': 'A company offering a co-op position with a specified hourly rate'}, {'name': '28/hr', 'type': 'value', 'description': 'The hourly compensation rate for a 3rd co-op position at EY'}, {'name': 'Faire', 'type': 'ID', 'description': 'A company offering a co-op position with a specified hourly rate'}, {'name': '44/hr', 'type': 'value', 'description': 'The hourly compensation rate for a 5th co-op position at Faire'}, {'name': '2024', 'type': 'value', 'description': 'The year associated with the co-op position at Faire'}, {'name': 'Engineering', 'type': 'position', 'description': 'The role associated with the co-op position at Faire'}, {'name': 'Fleet Complete', 'type': 'ID', 'description': 'A company offering co-op positions with varying hourly rates'}, {'name': '26/hr', 'type': 'value', 'description': 'The hourly compensation rate for a 3rd co-op position at Fleet Complete'}, {'name': '32/hr', 'type': 'value', 'description': 'The hourly compensation rate for a 5th co-op position at Fleet Complete'}, {'name': 'Fleet Labs', 'type': 'ID', 'description': 'A company offering a co-op position with a specified hourly rate range'}, {'name': '25-27/hr', 'type': 'value', 'description': 'The hourly compensation range for a co-op position at Fleet Labs'}, {'name': 'The Flight Deck', 'type': 'ID', 'description': 'A company offering a co-op position with a specified hourly rate'}, {'name': '23/hr', 'type': 'value', 'description': 'The hourly compensation rate for a co-op position at The Flight Deck'}]
Relationships: [{'source': 'Durovac', 'target': '23/hr', 'description': 'The hourly rate 23/hr is associated with the 4th co-op position at Durovac', 'weight': '10'}, {'source': 'Ecobee', 'target': '36-41/hr', 'description': 'The hourly rate range 36-41/hr is associated with the 4th co-op position at Ecobee', 'weight': '10'}, {'source': 'Ecobee', 'target': '43/hr', 'description': 'The hourly rate 43/hr is associated with the 5th co-op position at Ecobee', 'weight': '10'}, {'source': 'Ecobee', 'target': '2024', 'description': 'The year 2024 is associated with the co-op position at Ecobee', 'weight': '5'}, {'source': 'Ecompliance', 'target': '26/hr', 'description': 'The hourly rate 26/hr is associated with the 4th co-op position at Ecompliance', 'weight': '10'}, {'source': 'Elekta', 'target': '27/hr', 'description': 'The hourly rate 27/hr is associated with the 2A co-op position at Elekta', 'weight': '10'}, {'source': 'Embark Trucks', 'target': '10k/month', 'description': 'The monthly rate 10k/month is associated with the co-op position at Embark Trucks', 'weight': '10'}, {'source': 'Enzuzo', 'target': '28/hr', 'description': 'The hourly rate 28/hr is associated with the 3rd co-op position at Enzuzo', 'weight': '10'}, {'source': 'Enzuzo', 'target': '2024', 'description': 'The year 2024 is associated with the co-op position at Enzuzo', 'weight': '5'}, {'source': 'Enzuzo', 'target': 'Fullstack', 'description': 'The role Fullstack is associated with the co-op position at Enzuzo', 'weight': '5'}, {'source': 'The Empire Life Insurance Company', 'target': '22-28/hr', 'description': 'The hourly rate range 22-28/hr is associated with co-op positions at The Empire Life Insurance Company', 'weight': '10'}, {'source': 'Enlighted Inc', 'target': '36/hr', 'description': 'The hourly rate 36/hr is associated with the 5th co-op position at Enlighted Inc', 'weight': '10'}, {'source': 'Eon Media', 'target': '3800/mo', 'description': 'The monthly rate 3800/mo is associated with the 3rd-year co-op position at Eon Media', 'weight': '10'}, {'source': 'Equifax D&A', 'target': '22/hr', 'description': 'The hourly rate 22/hr is associated with the 1st co-op position at Equifax D&A', 'weight': '10'}, {'source': 'Equitable Life Insurance Company', 'target': '20/hr', 'description': 'The hourly rate 20/hr is associated with a co-op position at Equitable Life Insurance Company', 'weight': '10'}, {'source': 'Equitable Life Insurance Company', 'target': '23/hr', 'description': 'The hourly rate 23/hr is associated with the 2nd co-op position at Equitable Life Insurance Company', 'weight': '10'}, {'source': 'ESCRYPT', 'target': '26/hr', 'description': 'The hourly rate 26/hr is associated with the 3rd co-op position at ESCRYPT', 'weight': '10'}, {'source': 'ESCRYPT', 'target': '30/hr', 'description': 'The hourly rate 30/hr is associated with the 4th co-op position at ESCRYPT', 'weight': '10'}, {'source': 'eSentire', 'target': '24.50/hr', 'description': 'The hourly rate 24.50/hr is associated with the co-op position at eSentire', 'weight': '10'}, {'source': 'ETHGlobal', 'target': '9000/month', 'description': 'The monthly rate 9000/month is associated with the co-op position at ETHGlobal', 'weight': '10'}, {'source': 'ETHGlobal', 'target': '500/month stipend', 'description': 'The monthly stipend 500/month is associated with the co-op position at ETHGlobal', 'weight': '5'}, {'source': 'ETHGlobal', 'target': '2024', 'description': 'The year 2024 is associated with the co-op position at ETHGlobal', 'weight': '5'}, {'source': 'EY', 'target': '28/hr', 'description': 'The hourly rate 28/hr is associated with the 3rd co-op position at EY', 'weight': '10'}, {'source': 'Faire', 'target': '44/hr', 'description': 'The hourly rate 44/hr is associated with the 5th co-op position at Faire', 'weight': '10'}, {'source': 'Faire', 'target': '2024', 'description': 'The year 2024 is associated with the co-op position at Faire', 'weight': '5'}, {'source': 'Faire', 'target': 'Engineering', 'description': 'The role Engineering is associated with the co-op position at Faire', 'weight': '5'}, {'source': 'Fleet Complete', 'target': '26/hr', 'description': 'The hourly rate 26/hr is associated with the 3rd co-op position at Fleet Complete', 'weight': '10'}, {'source': 'Fleet Complete', 'target': '32/hr', 'description': 'The hourly rate 32/hr is associated with the 5th co-op position at Fleet Complete', 'weight': '10'}, {'source': 'Fleet Labs', 'target': '25-27/hr', 'description': 'The hourly rate range 25-27/hr is associated with the co-op position at Fleet Labs', 'weight': '10'}, {'source': 'The Flight Deck', 'target': '23/hr', 'description': 'The hourly rate 23/hr is associated with the co-op position at The Flight Deck', 'weight': '10'}]
✅ Graph successfully inserted into Neo4j!

2025-10-05 02:12:17,956 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Entities: [{'name': 'Flipp', 'type': 'ID', 'description': 'A company offering co-op positions with specified compensation rates'}, {'name': '$1082/wk', 'type': 'value', 'description': 'Weekly compensation rate offered by Flipp for co-op positions'}, {'name': 'Float', 'type': 'ID', 'description': 'A company offering co-op positions with specified compensation rates'}, {'name': '50/hr', 'type': 'value', 'description': 'Hourly compensation rate offered by Float for co-op positions'}, {'name': 'Ford', 'type': 'ID', 'description': 'A company offering co-op positions with specified compensation rates and additional terms'}, {'name': '27-35/hr', 'type': 'value', 'description': 'Hourly compensation range offered by Ford for co-op positions, with potential increases'}, {'name': '2024', 'type': 'value', 'description': "Year associated with Ford's co-op positions"}, {'name': 'SWE', 'type': 'value', 'description': 'Position type (Software Engineer'}, {'name': 'Forethought AI', 'type': 'ID', 'description': 'A company offering co-op positions with specified compensation rates'}, {'name': '6000-8000/month', 'type': 'value', 'description': 'Monthly compensation range offered by Forethought AI for co-op positions'}, {'name': 'Freshbooks', 'type': 'ID', 'description': 'A company offering co-op positions with specified compensation rates'}, {'name': '33/hr', 'type': 'value', 'description': 'Hourly compensation rate offered by Freshbooks for co-op positions'}, {'name': '70k/year', 'type': 'value', 'description': 'Annual salary offered by Freshbooks for co-op positions'}, {'name': 'Friendlier', 'type': 'ID', 'description': 'A company offering co-op positions with specified compensation rates'}, {'name': '17/hr', 'type': 'value', 'description': 'Hourly compensation rate offered by Friendlier for co-op positions'}, {'name': '2024', 'type': 'value', 'description': "Year associated with Friendlier's co-op positions"}, {'name': 'Fuego Studios Inc.', 'type': 'ID', 'description': 'A company offering co-op positions with specified compensation rates'}, {'name': '35/hr', 'type': 'value', 'description': 'Hourly compensation rate offered by Fuego Studios Inc. for co-op positions'}, {'name': '2024', 'type': 'value', 'description': "Year associated with Fuego Studios Inc.'s co-op positions"}, {'name': 'Genesys Laboratories', 'type': 'ID', 'description': 'A company offering co-op positions with specified compensation rates'}, {'name': '10% above the coop average', 'type': 'value', 'description': 'Compensation rate offered by Genesys Laboratories for co-op positions, relative to the average'}, {'name': 'Geotab', 'type': 'ID', 'description': 'A company offering co-op positions with specified compensation rates'}, {'name': '30/hr', 'type': 'value', 'description': 'Hourly compensation rate offered by Geotab for co-op positions'}, {'name': 'Get ResQ', 'type': 'ID', 'description': 'A company offering co-op positions with specified compensation rates'}, {'name': '43/hr', 'type': 'value', 'description': 'Hourly compensation rate offered by Get ResQ for co-op positions'}, {'name': 'GIP (Green Infrastructure Program)', 'type': 'ID', 'description': 'A program offering co-op positions with specified compensation rates'}, {'name': '31/hr', 'type': 'value', 'description': 'Hourly compensation rate offered by GIP for co-op positions'}, {'name': '2024', 'type': 'value', 'description': "Year associated with GIP's co-op positions"}, {'name': 'Glu', 'type': 'ID', 'description': 'A company offering co-op positions with specified compensation rates'}, {'name': '30/hr', 'type': 'value', 'description': 'Hourly compensation rate offered by Glu for co-op positions'}, {'name': '25/hr', 'type': 'value', 'description': 'Hourly compensation rate offered by Glu for co-op positions'}, {'name': 'GoDaddy', 'type': 'ID', 'description': 'A company offering co-op positions with specified compensation rates'}, {'name': '43/hr USD', 'type': 'value', 'description': 'Hourly compensation rate offered by GoDaddy for co-op positions in USD'}, {'name': '2024', 'type': 'value', 'description': "Year associated with GoDaddy's co-op positions"}, {'name': 'Google', 'type': 'ID', 'description': 'A company offering co-op positions with specified compensation rates and benefits'}, {'name': '$1538/week', 'type': 'value', 'description': 'Weekly compensation rate offered by Google for co-op positions in Canada'}, {'name': '$1700 - $2100 USD/week', 'type': 'value', 'description': 'Weekly compensation range offered by Google for co-op positions in the US'}, {'name': '4k housing stipend', 'type': 'value', 'description': 'Housing stipend offered by Google for co-op positions in Canada'}, {'name': '6k USD housing stipend', 'type': 'value', 'description': 'Housing stipend offered by Google for co-op positions in the USA'}, {'name': 'GPTZero', 'type': 'ID', 'description': 'A company offering co-op positions with specified compensation rates'}, {'name': '40-55/hr CAD', 'type': 'value', 'description': 'Hourly compensation range offered by GPTZero for co-op positions in Toronto'}, {'name': '7000-8000/month USD', 'type': 'value', 'description': 'Monthly compensation range offered by GPTZero for co-op positions in NYC'}, {'name': '2024', 'type': 'value', 'description': "Year associated with GPTZero's co-op positions"}, {'name': 'groq (Groq Inc)', 'type': 'ID', 'description': 'A company offering co-op positions with specified compensation rates'}, {'name': '37/hr', 'type': 'value', 'description': 'Hourly compensation rate offered by groq for co-op positions'}, {'name': '35-42/hr', 'type': 'value', 'description': 'Hourly compensation range offered by groq for co-op positions'}, {'name': 'Gsoft', 'type': 'ID', 'description': 'A company offering co-op positions with specified compensation rates'}, {'name': '40/hr', 'type': 'value', 'description': 'Hourly compensation rate offered by Gsoft for co-op positions'}, {'name': 'H2Analytics', 'type': 'ID', 'description': 'A company offering co-op positions with specified compensation rates'}, {'name': '23/hr', 'type': 'value', 'description': 'Hourly compensation rate offered by H2Analytics for co-op positions'}, {'name': 'Halp', 'type': 'ID', 'description': 'A company offering co-op positions with specified compensation rates'}, {'name': '38/hr', 'type': 'value', 'description': 'Hourly compensation rate offered by Halp for co-op positions'}, {'name': 'Hatch Credit', 'type': 'ID', 'description': 'A company offering co-op positions with specified compensation rates'}, {'name': '8000-9000 USD/month', 'type': 'value', 'description': 'Monthly compensation range offered by Hatch Credit for co-op positions'}]
Relationships: [{'source': 'Flipp', 'target': '$1082/wk', 'description': 'The weekly compensation rate of $1082 is associated with Flipp', 'weight': '10'}, {'source': 'Float', 'target': '50/hr', 'description': 'The hourly compensation rate of 50/hr is associated with Float', 'weight': '10'}, {'source': 'Ford', 'target': '27-35/hr', 'description': 'The hourly compensation range of 27-35/hr is associated with Ford', 'weight': '10'}, {'source': 'Ford', 'target': '2024', 'description': "The year 2024 is associated with Ford's co-op positions", 'weight': '10'}, {'source': 'Ford', 'target': 'SWE', 'description': "The position type SWE is associated with Ford's co-op positions", 'weight': '10'}, {'source': 'Forethought AI', 'target': '6000-8000/month', 'description': 'The monthly compensation range of 6000-8000/month is associated with Forethought AI', 'weight': '10'}, {'source': 'Freshbooks', 'target': '33/hr', 'description': 'The hourly compensation rate of 33/hr is associated with Freshbooks', 'weight': '10'}, {'source': 'Freshbooks', 'target': '70k/year', 'description': 'The annual salary of 70k/year is associated with Freshbooks', 'weight': '10'}, {'source': 'Friendlier', 'target': '17/hr', 'description': 'The hourly compensation rate of 17/hr is associated with Friendlier', 'weight': '10'}, {'source': 'Friendlier', 'target': '2024', 'description': "The year 2024 is associated with Friendlier's co-op positions", 'weight': '10'}, {'source': 'Fuego Studios Inc.', 'target': '35/hr', 'description': 'The hourly compensation rate of 35/hr is associated with Fuego Studios Inc.', 'weight': '10'}, {'source': 'Fuego Studios Inc.', 'target': '2024', 'description': "The year 2024 is associated with Fuego Studios Inc.'s co-op positions", 'weight': '10'}, {'source': 'Genesys Laboratories', 'target': '10% above the coop average', 'description': 'The compensation rate of 10% above the coop average is associated with Genesys Laboratories', 'weight': '10'}, {'source': 'Geotab', 'target': '30/hr', 'description': 'The hourly compensation rate of 30/hr is associated with Geotab', 'weight': '10'}, {'source': 'Get ResQ', 'target': '43/hr', 'description': 'The hourly compensation rate of 43/hr is associated with Get ResQ', 'weight': '10'}, {'source': 'GIP (Green Infrastructure Program)', 'target': '31/hr', 'description': 'The hourly compensation rate of 31/hr is associated with GIP', 'weight': '10'}, {'source': 'GIP (Green Infrastructure Program)', 'target': '2024', 'description': "The year 2024 is associated with GIP's co-op positions", 'weight': '10'}, {'source': 'Glu', 'target': '30/hr', 'description': 'The hourly compensation rate of 30/hr is associated with Glu', 'weight': '10'}, {'source': 'Glu', 'target': '25/hr', 'description': 'The hourly compensation rate of 25/hr is associated with Glu', 'weight': '10'}, {'source': 'GoDaddy', 'target': '43/hr USD', 'description': 'The hourly compensation rate of 43/hr USD is associated with GoDaddy', 'weight': '10'}, {'source': 'GoDaddy', 'target': '2024', 'description': "The year 2024 is associated with GoDaddy's co-op positions", 'weight': '10'}, {'source': 'Google', 'target': '$1538/week', 'description': 'The weekly compensation rate of $1538/week is associated with Google in Canada', 'weight': '10'}, {'source': 'Google', 'target': '$1700 - $2100 USD/week', 'description': 'The weekly compensation range of $1700 - $2100 USD/week is associated with Google in the US', 'weight': '10'}, {'source': 'Google', 'target': '4k housing stipend', 'description': 'The 4k housing stipend is associated with Google for co-op positions in Canada', 'weight': '10'}, {'source': 'Google', 'target': '6k USD housing stipend', 'description': 'The 6k USD housing stipend is associated with Google for co-op positions in the USA', 'weight': '10'}, {'source': 'GPTZero', 'target': '40-55/hr CAD', 'description': 'The hourly compensation range of 40-55/hr CAD is associated with GPTZero in Toronto', 'weight': '10'}, {'source': 'GPTZero', 'target': '7000-8000/month USD', 'description': 'The monthly compensation range of 7000-8000/month USD is associated with GPTZero in NYC', 'weight': '10'}, {'source': 'GPTZero', 'target': '2024', 'description': "The year 2024 is associated with GPTZero's co-op positions", 'weight': '10'}, {'source': 'groq (Groq Inc)', 'target': '37/hr', 'description': 'The hourly compensation rate of 37/hr is associated with groq', 'weight': '10'}, {'source': 'groq (Groq Inc)', 'target': '35-42/hr', 'description': 'The hourly compensation range of 35-42/hr is associated with groq', 'weight': '10'}, {'source': 'Gsoft', 'target': '40/hr', 'description': 'The hourly compensation rate of 40/hr is associated with Gsoft', 'weight': '10'}, {'source': 'H2Analytics', 'target': '23/hr', 'description': 'The hourly compensation rate of 23/hr is associated with H2Analytics', 'weight': '10'}, {'source': 'Halp', 'target': '38/hr', 'description': 'The hourly compensation rate of 38/hr is associated with Halp', 'weight': '10'}, {'source': 'Hatch Credit', 'target': '8000-9000 USD/month', 'description': 'The monthly compensation range of 8000-9000 USD/month is associated with Hatch Credit', 'weight': '10'}]
✅ Graph successfully inserted into Neo4j!

2025-10-05 02:12:37,719 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Entities: [{'name': 'Havas CX', 'type': 'ID', 'description': 'A company offering a coop position with a specified hourly rate for students'}, {'name': '30/hr', 'type': 'value', 'description': 'The hourly rate offered by Havas CX for a 4th coop position'}, {'name': '2024', 'type': 'value', 'description': 'The year associated with the Havas CX coop position'}, {'name': 'Software Engineering', 'type': 'value', 'description': 'The position offered by Havas CX'}, {'name': 'HeadSpin', 'type': 'ID', 'description': 'A company offering a coop position with a specified hourly rate for students'}, {'name': '32/hr', 'type': 'value', 'description': 'The hourly rate offered by HeadSpin for a 3rd coop position'}, {'name': 'Healthcare Systems R&A', 'type': 'ID', 'description': 'A company offering a coop position with a variable hourly rate based on funding'}, {'name': '16-20/hr', 'type': 'value', 'description': 'The variable hourly rate offered by Healthcare Systems R&A'}, {'name': '2023', 'type': 'value', 'description': 'The year associated with the Healthcare Systems R&A coop position'}, {'name': 'High Q Technologies', 'type': 'ID', 'description': 'A company offering a coop position with a specified hourly rate for students'}, {'name': '25/hr', 'type': 'value', 'description': 'The hourly rate offered by High Q Technologies for a 3rd coop position'}, {'name': 'Hockeystick', 'type': 'ID', 'description': 'A company offering a coop position with an hourly rate around the coop average'}, {'name': '21/hr', 'type': 'value', 'description': 'The hourly rate offered by Hockeystick for a 1st coop position'}, {'name': 'Home Depot (Dev)', 'type': 'ID', 'description': 'A company offering a coop position with a specified hourly rate for students'}, {'name': '20/hr', 'type': 'value', 'description': 'The hourly rate offered by Home Depot (Dev'}, {'name': 'HomeX', 'type': 'ID', 'description': 'A company offering a coop position with specified hourly rates for students'}, {'name': '30/hr, 33/hr', 'type': 'value', 'description': 'The hourly rates offered by HomeX for a 3rd coop position'}, {'name': 'HOOPP (Health Care of Ontario Pension Plan)', 'type': 'ID', 'description': 'A company offering a coop position with a specified hourly rate for students'}, {'name': '22.25/hr', 'type': 'value', 'description': 'The hourly rate offered by HOOPP for a 2nd coop position'}, {'name': 'Horizon Studio', 'type': 'ID', 'description': 'A company offering a coop position with a specified hourly rate for students'}, {'name': '27/hr', 'type': 'value', 'description': 'The hourly rate offered by Horizon Studio for a 3rd coop position'}, {'name': 'Huawei', 'type': 'ID', 'description': 'A company offering a coop position with a specified hourly rate for students'}, {'name': '36/hr', 'type': 'value', 'description': 'The hourly rate offered by Huawei for a 5th coop position'}, {'name': '2025', 'type': 'value', 'description': 'The year associated with the Huawei coop position'}, {'name': 'Hubdoc', 'type': 'ID', 'description': 'A company offering a coop position with a rate above the coop average'}, {'name': '5% above the coop average', 'type': 'value', 'description': 'The rate offered by Hubdoc for a coop position'}, {'name': 'HubSpot', 'type': 'ID', 'description': 'A company offering a coop position with a specified hourly rate in USD'}, {'name': '50-54/hr USD', 'type': 'value', 'description': 'The hourly rate offered by HubSpot for a coop position'}, {'name': 'IBM', 'type': 'ID', 'description': 'A company offering coop positions with specified hourly rates and additional benefits'}, {'name': '26.50/hr, 28-31/hr, 36/hr', 'type': 'value', 'description': 'The hourly rates offered by IBM for various coop positions'}, {'name': '32/hr', 'type': 'value', 'description': 'The hourly rate offered by IBM for a 4th coop position'}, {'name': 'IBM stock at a 15% discount off the market price', 'type': 'value', 'description': 'A benefit offered by IBM for coop positions'}, {'name': 'Product Design', 'type': 'value', 'description': 'The position offered by IBM'}, {'name': 'Index Exchange', 'type': 'ID', 'description': 'A company offering a coop position with a specified hourly rate for students'}, {'name': '30/hr or above', 'type': 'value', 'description': 'The hourly rate offered by Index Exchange for a coop position'}, {'name': 'Indus AI', 'type': 'ID', 'description': 'A company offering a coop position with a specified monthly rate in USD'}, {'name': '8500/month USD', 'type': 'value', 'description': 'The monthly rate offered by Indus AI for a 5th coop position'}, {'name': 'Flights included', 'type': 'value', 'description': 'A benefit offered by Indus AI for coop positions'}, {'name': 'Intact', 'type': 'ID', 'description': 'A company offering a coop position with a specified hourly rate for students'}, {'name': '43/hr', 'type': 'value', 'description': 'The hourly rate offered by Intact for a 5th coop position'}]
Relationships: [{'source': 'Havas CX', 'target': '30/hr', 'description': '30/hr is the hourly rate associated with Havas CX for a 4th coop position', 'weight': '10'}, {'source': 'Havas CX', 'target': '2024', 'description': '2024 is the year associated with the Havas CX coop position', 'weight': '10'}, {'source': 'Havas CX', 'target': 'Software Engineering', 'description': 'Software Engineering is the position offered by Havas CX', 'weight': '10'}, {'source': 'HeadSpin', 'target': '32/hr', 'description': '32/hr is the hourly rate associated with HeadSpin for a 3rd coop position', 'weight': '10'}, {'source': 'Healthcare Systems R&A', 'target': '16-20/hr', 'description': '16-20/hr is the variable hourly rate associated with Healthcare Systems R&A', 'weight': '10'}, {'source': 'Healthcare Systems R&A', 'target': '2023', 'description': '2023 is the year associated with the Healthcare Systems R&A coop position', 'weight': '10'}, {'source': 'High Q Technologies', 'target': '25/hr', 'description': '25/hr is the hourly rate associated with High Q Technologies for a 3rd coop position', 'weight': '10'}, {'source': 'Hockeystick', 'target': '21/hr', 'description': '21/hr is the hourly rate associated with Hockeystick for a 1st coop position', 'weight': '10'}, {'source': 'Home Depot (Dev)', 'target': '20/hr', 'description': '20/hr is the hourly rate associated with Home Depot (Dev', 'weight': None}, {'source': 'HomeX', 'target': '30/hr, 33/hr', 'description': '30/hr, 33/hr are the hourly rates associated with HomeX for a 3rd coop position', 'weight': '10'}, {'source': 'HOOPP (Health Care of Ontario Pension Plan)', 'target': '22.25/hr', 'description': '22.25/hr is the hourly rate associated with HOOPP for a 2nd coop position', 'weight': '10'}, {'source': 'Horizon Studio', 'target': '27/hr', 'description': '27/hr is the hourly rate associated with Horizon Studio for a 3rd coop position', 'weight': '10'}, {'source': 'Huawei', 'target': '36/hr', 'description': '36/hr is the hourly rate associated with Huawei for a 5th coop position', 'weight': '10'}, {'source': 'Huawei', 'target': '2025', 'description': '2025 is the year associated with the Huawei coop position', 'weight': '10'}, {'source': 'Hubdoc', 'target': '5% above the coop average', 'description': '5% above the coop average is the rate associated with Hubdoc for a coop position', 'weight': '10'}, {'source': 'HubSpot', 'target': '50-54/hr USD', 'description': '50-54/hr USD is the hourly rate associated with HubSpot for a coop position', 'weight': '10'}, {'source': 'IBM', 'target': '26.50/hr, 28-31/hr, 36/hr', 'description': '26.50/hr, 28-31/hr, 36/hr are the hourly rates associated with IBM for various coop positions', 'weight': '10'}, {'source': 'IBM', 'target': '32/hr', 'description': '32/hr is the hourly rate associated with IBM for a 4th coop position', 'weight': '10'}, {'source': 'IBM', 'target': 'IBM stock at a 15% discount off the market price', 'description': 'IBM stock at a 15% discount off the market price is a benefit associated with IBM for coop positions', 'weight': '10'}, {'source': 'IBM', 'target': 'Product Design', 'description': 'Product Design is the position offered by IBM', 'weight': '10'}, {'source': 'Index Exchange', 'target': '30/hr or above', 'description': '30/hr or above is the hourly rate associated with Index Exchange for a coop position', 'weight': '10'}, {'source': 'Indus AI', 'target': '8500/month USD', 'description': '8500/month USD is the monthly rate associated with Indus AI for a 5th coop position', 'weight': '10'}, {'source': 'Indus AI', 'target': 'Flights included', 'description': 'Flights included is a benefit associated with Indus AI for coop positions', 'weight': '10'}, {'source': 'Intact', 'target': '43/hr', 'description': '43/hr is the hourly rate associated with Intact for a 5th coop position', 'weight': '10'}]
✅ Graph successfully inserted into Neo4j!

2025-10-05 02:13:01,373 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Entities: [{'name': 'Intact Labs', 'type': 'ID', 'description': 'A company offering co-op positions with varying hourly compensation rates'}, {'name': '30.5/hr', 'type': 'value', 'description': 'Hourly compensation rate for a 3rd co-op position at Intact Labs'}, {'name': 'Data Science 32/hr', 'type': 'value', 'description': 'Hourly compensation rate for a 2nd co-op position in Data Science at Intact Labs'}, {'name': '39/hr', 'type': 'value', 'description': 'Hourly compensation rate for a 5th or 6th co-op position at Intact Labs'}, {'name': 'Intel', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly compensation rates'}, {'name': '33/hr', 'type': 'value', 'description': 'Hourly compensation rate for a co-op position at Intel'}, {'name': '35/hr', 'type': 'value', 'description': 'Hourly compensation rate for a 6th co-op position at Intel'}, {'name': 'Instinet Canada', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly compensation rates and stipends'}, {'name': '36/hr', 'type': 'value', 'description': 'Hourly compensation rate for a 2nd co-op position as an SRE analyst at Instinet Canada'}, {'name': '3k stipend', 'type': 'value', 'description': 'Stipend for a 2nd co-op position as an SRE analyst at Instinet Canada'}, {'name': 'Integrate.ai', 'type': 'ID', 'description': 'A company offering weekly compensation for positions'}, {'name': '1550/week', 'type': 'value', 'description': 'Weekly compensation rate at Integrate.ai'}, {'name': 'Intuit', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly compensation rates and stipends'}, {'name': '30-37/hr', 'type': 'value', 'description': 'Hourly compensation range for co-op positions at Intuit'}, {'name': '47/hr', 'type': 'value', 'description': 'Hourly compensation rate for a 3rd co-op position at Intuit'}, {'name': '5k USD stipend', 'type': 'value', 'description': 'Stipend offered by Intuit'}, {'name': 'iS5 Communications', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly compensation rates'}, {'name': '32/hr', 'type': 'value', 'description': 'Hourly compensation rate for a 6th co-op position at iS5 Communications'}, {'name': 'ISARA', 'type': 'ID', 'description': 'A company offering weekly compensation for co-op positions'}, {'name': '1228/week', 'type': 'value', 'description': 'Weekly compensation rate for a 3rd co-op position at ISARA'}, {'name': 'Itipack Systems', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly compensation rates'}, {'name': '23/hr', 'type': 'value', 'description': 'Hourly compensation rate for a 2nd co-op position at Itipack Systems'}, {'name': '2022', 'type': 'value', 'description': 'Year associated with the position at Itipack Systems'}, {'name': 'Mechanical Design', 'type': 'value', 'description': 'Position type at Itipack Systems'}, {'name': 'Jane Street', 'type': 'ID', 'description': 'A company offering monthly compensation and additional benefits'}, {'name': '16,667 USD/mo', 'type': 'value', 'description': 'Monthly compensation rate at Jane Street'}, {'name': '2.1k USD/mo housing stipend', 'type': 'value', 'description': 'Monthly housing stipend offered by Jane Street'}, {'name': '10k USD signing bonus', 'type': 'value', 'description': 'Signing bonus offered by Jane Street'}, {'name': 'Jays Care Foundation (TBJ)', 'type': 'ID', 'description': 'A foundation offering co-op positions with specified hourly compensation rates'}, {'name': '18/hr', 'type': 'value', 'description': 'Hourly compensation rate for a 1st co-op position at Jays Care Foundation'}, {'name': 'Jobox.ai', 'type': 'ID', 'description': 'A company offering monthly compensation for co-op positions'}, {'name': '5700 USD/mo', 'type': 'value', 'description': 'Monthly compensation rate for a 3rd co-op position at Jobox.ai'}, {'name': 'Kaleidescape', 'type': 'ID', 'description': 'A company offering weekly compensation for positions'}, {'name': '785/week', 'type': 'value', 'description': 'Weekly compensation rate at Kaleidescape'}, {'name': '2022', 'type': 'value', 'description': 'Year associated with the positions at Kaleidescape'}, {'name': 'All positions', 'type': 'value', 'description': 'Position type at Kaleidescape'}, {'name': 'Kambeo', 'type': 'ID', 'description': 'A company offering positions with specified hourly compensation ranges'}, {'name': '20-30/hr', 'type': 'value', 'description': 'Hourly compensation range at Kambeo'}, {'name': 'KeepTruckin', 'type': 'ID', 'description': 'A company offering positions with specified hourly compensation rates'}, {'name': '30/hr', 'type': 'value', 'description': 'Hourly compensation rate at KeepTruckin'}, {'name': 'KGS research', 'type': 'ID', 'description': 'A company with a humorous remark instead of compensation details'}, {'name': 'Kiavi', 'type': 'ID', 'description': 'A company offering monthly compensation for positions'}, {'name': '$9000/mo', 'type': 'value', 'description': 'Monthly compensation rate at Kiavi'}, {'name': 'Kinaxis', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly compensation rates'}, {'name': '24/hr', 'type': 'value', 'description': 'Hourly compensation rate for a co-op position at Kinaxis'}, {'name': '34/hr', 'type': 'value', 'description': 'Hourly compensation rate for 1st and 2nd co-op positions at Kinaxis'}, {'name': '28-30/hr', 'type': 'value', 'description': 'Hourly compensation range for a 4th co-op position at Kinaxis'}, {'name': 'Kodiak Robotics', 'type': 'ID', 'description': 'A company offering monthly compensation for co-op positions'}, {'name': '8k-9k USD/mo', 'type': 'value', 'description': 'Monthly compensation range for a 6th co-op position at Kodiak Robotics'}, {'name': 'Konrad Group', 'type': 'ID', 'description': 'A company offering monthly compensation for positions'}, {'name': '6000/mo', 'type': 'value', 'description': 'Monthly compensation rate at Konrad Group'}]
Relationships: [{'source': 'Intact Labs', 'target': '30.5/hr', 'description': '30.5/hr is the hourly compensation rate for a 3rd co-op position at Intact Labs', 'weight': '10'}, {'source': 'Intact Labs', 'target': 'Data Science 32/hr', 'description': 'Data Science 32/hr is the hourly compensation rate for a 2nd co-op position at Intact Labs', 'weight': '10'}, {'source': 'Intact Labs', 'target': '39/hr', 'description': '39/hr is the hourly compensation rate for a 5th or 6th co-op position at Intact Labs', 'weight': '10'}, {'source': 'Intel', 'target': '33/hr', 'description': '33/hr is the hourly compensation rate for a co-op position at Intel', 'weight': '10'}, {'source': 'Intel', 'target': '35/hr', 'description': '35/hr is the hourly compensation rate for a 6th co-op position at Intel', 'weight': '10'}, {'source': 'Instinet Canada', 'target': '36/hr', 'description': '36/hr is the hourly compensation rate for a 2nd co-op position as an SRE analyst at Instinet Canada', 'weight': '10'}, {'source': 'Instinet Canada', 'target': '3k stipend', 'description': '3k stipend is the stipend for a 2nd co-op position as an SRE analyst at Instinet Canada', 'weight': '10'}, {'source': 'Integrate.ai', 'target': '1550/week', 'description': '1550/week is the weekly compensation rate at Integrate.ai', 'weight': '10'}, {'source': 'Intuit', 'target': '30-37/hr', 'description': '30-37/hr is the hourly compensation range for co-op positions at Intuit', 'weight': '10'}, {'source': 'Intuit', 'target': '47/hr', 'description': '47/hr is the hourly compensation rate for a 3rd co-op position at Intuit', 'weight': '10'}, {'source': 'Intuit', 'target': '5k USD stipend', 'description': '5k USD stipend is the stipend offered by Intuit', 'weight': '10'}, {'source': 'iS5 Communications', 'target': '32/hr', 'description': '32/hr is the hourly compensation rate for a 6th co-op position at iS5 Communications', 'weight': '10'}, {'source': 'ISARA', 'target': '1228/week', 'description': '1228/week is the weekly compensation rate for a 3rd co-op position at ISARA', 'weight': '10'}, {'source': 'Itipack Systems', 'target': '23/hr', 'description': '23/hr is the hourly compensation rate for a 2nd co-op position at Itipack Systems', 'weight': '10'}, {'source': 'Itipack Systems', 'target': '2022', 'description': '2022 is the year associated with the position at Itipack Systems', 'weight': '5'}, {'source': 'Itipack Systems', 'target': 'Mechanical Design', 'description': 'Mechanical Design is the position type at Itipack Systems', 'weight': '5'}, {'source': 'Jane Street', 'target': '16,667 USD/mo', 'description': '16,667 USD/mo is the monthly compensation rate at Jane Street', 'weight': '10'}, {'source': 'Jane Street', 'target': '2.1k USD/mo housing stipend', 'description': '2.1k USD/mo housing stipend is the monthly housing stipend offered by Jane Street', 'weight': '10'}, {'source': 'Jane Street', 'target': '10k USD signing bonus', 'description': '10k USD signing bonus is the signing bonus offered by Jane Street', 'weight': '10'}, {'source': 'Jays Care Foundation (TBJ)', 'target': '18/hr', 'description': '18/hr is the hourly compensation rate for a 1st co-op position at Jays Care Foundation', 'weight': '10'}, {'source': 'Jobox.ai', 'target': '5700 USD/mo', 'description': '5700 USD/mo is the monthly compensation rate for a 3rd co-op position at Jobox.ai', 'weight': '10'}, {'source': 'Kaleidescape', 'target': '785/week', 'description': '785/week is the weekly compensation rate at Kaleidescape', 'weight': '10'}, {'source': 'Kaleidescape', 'target': '2022', 'description': '2022 is the year associated with the positions at Kaleidescape', 'weight': '5'}, {'source': 'Kaleidescape', 'target': 'All positions', 'description': 'All positions is the position type at Kaleidescape', 'weight': '5'}, {'source': 'Kambeo', 'target': '20-30/hr', 'description': '20-30/hr is the hourly compensation range at Kambeo', 'weight': '10'}, {'source': 'KeepTruckin', 'target': '30/hr', 'description': '30/hr is the hourly compensation rate at KeepTruckin', 'weight': '10'}, {'source': 'Kiavi', 'target': '$9000/mo', 'description': '$9000/mo is the monthly compensation rate at Kiavi', 'weight': '10'}, {'source': 'Kinaxis', 'target': '24/hr', 'description': '24/hr is the hourly compensation rate for a co-op position at Kinaxis', 'weight': '10'}, {'source': 'Kinaxis', 'target': '34/hr', 'description': '34/hr is the hourly compensation rate for 1st and 2nd co-op positions at Kinaxis', 'weight': '10'}, {'source': 'Kinaxis', 'target': '28-30/hr', 'description': '28-30/hr is the hourly compensation range for a 4th co-op position at Kinaxis', 'weight': '10'}, {'source': 'Kodiak Robotics', 'target': '8k-9k USD/mo', 'description': '8k-9k USD/mo is the monthly compensation range for a 6th co-op position at Kodiak Robotics', 'weight': '10'}, {'source': 'Konrad Group', 'target': '6000/mo', 'description': '6000/mo is the monthly compensation rate at Konrad Group', 'weight': '10'}]
✅ Graph successfully inserted into Neo4j!

2025-10-05 02:13:23,419 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Entities: [{'name': 'LCBO', 'type': 'ID', 'description': 'A company offering a PM role with a weekly compensation rate'}, {'name': '1100/wk', 'type': 'value', 'description': 'Weekly compensation rate for a PM role at LCBO'}, {'name': 'League', 'type': 'ID', 'description': 'A company offering co-op positions with hourly compensation rates'}, {'name': '33/hr', 'type': 'value', 'description': 'Hourly compensation rate for a 4th co-op position at League'}, {'name': '41/hr', 'type': 'value', 'description': 'Hourly compensation rate for a 6th co-op position at League'}, {'name': 'Level', 'type': 'ID', 'description': 'A company offering monthly compensation and additional benefits'}, {'name': '13,000/mo', 'type': 'value', 'description': 'Monthly compensation rate at Level'}, {'name': '200 for equipment + 100/mo UberEats allowance', 'type': 'value', 'description': 'Additional benefits provided by Level'}, {'name': 'LifeWorks', 'type': 'ID', 'description': 'A company offering hourly compensation rates'}, {'name': '22.5/hr', 'type': 'value', 'description': 'Hourly compensation rate at LifeWorks'}, {'name': 'Lifion by Adp', 'type': 'ID', 'description': 'A company offering hourly compensation rates'}, {'name': '40-44/hr', 'type': 'value', 'description': 'Hourly compensation range at Lifion by Adp'}, {'name': 'Loblaw', 'type': 'ID', 'description': 'A company offering co-op positions with hourly compensation rates'}, {'name': '31/hr', 'type': 'value', 'description': 'Hourly compensation rate for a 2nd co-op position at Loblaw'}, {'name': 'Data Science', 'type': 'position', 'description': 'Position offered at Loblaw'}, {'name': 'Loblaw Digital', 'type': 'ID', 'description': 'A company offering co-op positions with hourly compensation rates'}, {'name': '30/hr', 'type': 'value', 'description': 'Hourly compensation rate for a 2nd co-op position at Loblaw Digital'}, {'name': '2023', 'type': 'year', 'description': 'Year associated with the position at Loblaw Digital'}, {'name': 'Data Analyst', 'type': 'position', 'description': 'Position offered at Loblaw Digital'}, {'name': 'Mastercard Foundation', 'type': 'ID', 'description': 'A company offering co-op positions with hourly compensation rates'}, {'name': '19.5/hr', 'type': 'value', 'description': 'Hourly compensation rate for a 1st co-op position at Mastercard Foundation'}, {'name': 'Manulife', 'type': 'ID', 'description': 'A company offering co-op positions with hourly compensation rates'}, {'name': '25/hr', 'type': 'value', 'description': 'Hourly compensation rate at Manulife'}, {'name': '26/hr', 'type': 'value', 'description': 'Hourly compensation rate for a 3rd year position at Manulife'}, {'name': 'Mach7 Technologies', 'type': 'ID', 'description': 'A company offering co-op positions with hourly compensation rates'}, {'name': '25/hr', 'type': 'value', 'description': 'Hourly compensation rate for a 3rd co-op position at Mach7 Technologies'}, {'name': '2024', 'type': 'year', 'description': 'Year associated with the position at Mach7 Technologies'}, {'name': 'Systems/IT', 'type': 'position', 'description': 'Position offered at Mach7 Technologies'}, {'name': 'McAfee', 'type': 'ID', 'description': 'A company offering co-op positions with hourly compensation rates'}, {'name': '25/hr', 'type': 'value', 'description': 'Hourly compensation rate for a 2nd co-op position at McAfee'}, {'name': 'Meta', 'type': 'ID', 'description': 'A company offering monthly compensation rates'}, {'name': '8200/month USD', 'type': 'value', 'description': 'Monthly compensation rate at Meta'}, {'name': '2024', 'type': 'year', 'description': 'Year associated with the position at Meta'}, {'name': 'Metrist', 'type': 'ID', 'description': 'A company offering yearly compensation rates'}, {'name': '70k/yr ~= 33.65/hr', 'type': 'value', 'description': 'Yearly compensation rate at Metrist, approximately equivalent to an hourly rate'}, {'name': 'Microart Services', 'type': 'ID', 'description': 'A company offering co-op positions with hourly compensation rates'}, {'name': '26/hr', 'type': 'value', 'description': 'Hourly compensation rate for a 1st co-op position at Microart Services'}, {'name': 'Microsoft', 'type': 'ID', 'description': 'A company offering hourly compensation rates and additional benefits'}, {'name': '46/hr USD', 'type': 'value', 'description': 'Hourly compensation rate at Microsoft'}, {'name': '12k housing stipend + 1.6k transport stipend + flights covered', 'type': 'value', 'description': 'Additional benefits provided by Microsoft'}, {'name': '2024', 'type': 'year', 'description': 'Year associated with the position at Microsoft'}, {'name': 'Microsoft Canada', 'type': 'ID', 'description': 'A company offering hourly compensation rates'}, {'name': '33/hr', 'type': 'value', 'description': 'Hourly compensation rate at Microsoft Canada'}, {'name': 'Milliman', 'type': 'ID', 'description': 'A company offering hourly compensation rates and additional benefits'}, {'name': '30/hr USD', 'type': 'value', 'description': 'Hourly compensation rate at Milliman'}, {'name': '500 USD relocation stipend + 1500 USD monthly stipend', 'type': 'value', 'description': 'Additional benefits provided by Milliman'}, {'name': '2024', 'type': 'year', 'description': 'Year associated with the position at Milliman'}, {'name': 'Actuarial Analyst', 'type': 'position', 'description': 'Position offered at Milliman'}, {'name': 'Molex', 'type': 'ID', 'description': 'A company offering co-op positions with hourly compensation rates'}, {'name': '23/hr', 'type': 'value', 'description': 'Hourly compensation rate for a 2nd co-op position at Molex'}, {'name': '25/hr', 'type': 'value', 'description': 'Hourly compensation rate for a 4th co-op position at Molex'}]
Relationships: [{'source': 'LCBO', 'target': '1100/wk', 'description': '1100/wk is the weekly compensation rate for a PM role at LCBO', 'weight': '10'}, {'source': 'League', 'target': '33/hr', 'description': '33/hr is the hourly compensation rate for a 4th co-op position at League', 'weight': '10'}, {'source': 'League', 'target': '41/hr', 'description': '41/hr is the hourly compensation rate for a 6th co-op position at League', 'weight': '10'}, {'source': 'Level', 'target': '13,000/mo', 'description': '13,000/mo is the monthly compensation rate at Level', 'weight': '10'}, {'source': 'Level', 'target': '200 for equipment + 100/mo UberEats allowance', 'description': 'These are additional benefits provided by Level', 'weight': '10'}, {'source': 'LifeWorks', 'target': '22.5/hr', 'description': '22.5/hr is the hourly compensation rate at LifeWorks', 'weight': '10'}, {'source': 'Lifion by Adp', 'target': '40-44/hr', 'description': '40-44/hr is the hourly compensation range at Lifion by Adp', 'weight': '10'}, {'source': 'Loblaw', 'target': '31/hr', 'description': '31/hr is the hourly compensation rate for a 2nd co-op position at Loblaw', 'weight': '10'}, {'source': 'Loblaw', 'target': 'Data Science', 'description': 'Data Science is the position offered at Loblaw', 'weight': '10'}, {'source': 'Loblaw Digital', 'target': '30/hr', 'description': '30/hr is the hourly compensation rate for a 2nd co-op position at Loblaw Digital', 'weight': '10'}, {'source': 'Loblaw Digital', 'target': '2023', 'description': '2023 is the year associated with the position at Loblaw Digital', 'weight': '10'}, {'source': 'Loblaw Digital', 'target': 'Data Analyst', 'description': 'Data Analyst is the position offered at Loblaw Digital', 'weight': '10'}, {'source': 'Mastercard Foundation', 'target': '19.5/hr', 'description': '19.5/hr is the hourly compensation rate for a 1st co-op position at Mastercard Foundation', 'weight': '10'}, {'source': 'Manulife', 'target': '25/hr', 'description': '25/hr is the hourly compensation rate at Manulife', 'weight': '10'}, {'source': 'Manulife', 'target': '26/hr', 'description': '26/hr is the hourly compensation rate for a 3rd year position at Manulife', 'weight': '10'}, {'source': 'Mach7 Technologies', 'target': '25/hr', 'description': '25/hr is the hourly compensation rate for a 3rd co-op position at Mach7 Technologies', 'weight': '10'}, {'source': 'Mach7 Technologies', 'target': '2024', 'description': '2024 is the year associated with the position at Mach7 Technologies', 'weight': '10'}, {'source': 'Mach7 Technologies', 'target': 'Systems/IT', 'description': 'Systems/IT is the position offered at Mach7 Technologies', 'weight': '10'}, {'source': 'McAfee', 'target': '25/hr', 'description': '25/hr is the hourly compensation rate for a 2nd co-op position at McAfee', 'weight': '10'}, {'source': 'Meta', 'target': '8200/month USD', 'description': '8200/month USD is the monthly compensation rate at Meta', 'weight': '10'}, {'source': 'Meta', 'target': '2024', 'description': '2024 is the year associated with the position at Meta', 'weight': '10'}, {'source': 'Metrist', 'target': '70k/yr ~= 33.65/hr', 'description': '70k/yr is the yearly compensation rate at Metrist, approximately equivalent to an hourly rate', 'weight': '10'}, {'source': 'Microart Services', 'target': '26/hr', 'description': '26/hr is the hourly compensation rate for a 1st co-op position at Microart Services', 'weight': '10'}, {'source': 'Microsoft', 'target': '46/hr USD', 'description': '46/hr USD is the hourly compensation rate at Microsoft', 'weight': '10'}, {'source': 'Microsoft', 'target': '12k housing stipend + 1.6k transport stipend + flights covered', 'description': 'These are additional benefits provided by Microsoft', 'weight': '10'}, {'source': 'Microsoft', 'target': '2024', 'description': '2024 is the year associated with the position at Microsoft', 'weight': '10'}, {'source': 'Microsoft Canada', 'target': '33/hr', 'description': '33/hr is the hourly compensation rate at Microsoft Canada', 'weight': '10'}, {'source': 'Milliman', 'target': '30/hr USD', 'description': '30/hr USD is the hourly compensation rate at Milliman', 'weight': '10'}, {'source': 'Milliman', 'target': '500 USD relocation stipend + 1500 USD monthly stipend', 'description': 'These are additional benefits provided by Milliman', 'weight': '10'}, {'source': 'Milliman', 'target': '2024', 'description': '2024 is the year associated with the position at Milliman', 'weight': '10'}, {'source': 'Milliman', 'target': 'Actuarial Analyst', 'description': 'Actuarial Analyst is the position offered at Milliman', 'weight': '10'}, {'source': 'Molex', 'target': '23/hr', 'description': '23/hr is the hourly compensation rate for a 2nd co-op position at Molex', 'weight': '10'}, {'source': 'Molex', 'target': '25/hr', 'description': '25/hr is the hourly compensation rate for a 4th co-op position at Molex', 'weight': '10'}]
✅ Graph successfully inserted into Neo4j!

2025-10-05 02:13:47,658 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Entities: [{'name': 'MotoInsight', 'type': 'ID', 'description': 'A company offering co-op positions with specified compensation'}, {'name': '3000/mo', 'type': 'value', 'description': 'Monthly salary offered by MotoInsight for a co-op position'}, {'name': 'Motorola Solutions', 'type': 'ID', 'description': 'A company offering co-op positions with specified compensation and role details'}, {'name': '37/hr', 'type': 'value', 'description': 'Hourly rate offered by Motorola Solutions for a 5th co-op position'}, {'name': '2024', 'type': 'value', 'description': 'Year associated with the co-op position at Motorola Solutions'}, {'name': 'Product Design', 'type': 'value', 'description': 'Role associated with the co-op position at Motorola Solutions'}, {'name': 'Moveworks', 'type': 'ID', 'description': 'A company offering co-op positions with specified compensation options'}, {'name': '9.5K/mo', 'type': 'value', 'description': 'Monthly salary option offered by Moveworks for a co-op position'}, {'name': '7.5K USD/mo', 'type': 'value', 'description': 'Alternative monthly salary option offered by Moveworks for a co-op position'}, {'name': '500/mo stipend', 'type': 'value', 'description': 'Monthly stipend offered by Moveworks in addition to salary'}, {'name': 'Mozilla', 'type': 'ID', 'description': 'A company offering co-op positions with specified compensation'}, {'name': '30/hr', 'type': 'value', 'description': "Hourly rate offered by Mozilla for a master's level co-op position"}, {'name': 'Munich Re', 'type': 'ID', 'description': 'A company offering co-op positions with specified compensation and stipend'}, {'name': '1100/week', 'type': 'value', 'description': 'Weekly salary offered by Munich Re for a co-op position'}, {'name': '1500 CAD stipend', 'type': 'value', 'description': 'Stipend offered by Munich Re in addition to weekly salary'}, {'name': 'NASDAQ', 'type': 'ID', 'description': 'A company offering co-op positions with specified compensation'}, {'name': '28/hr', 'type': 'value', 'description': 'Hourly rate offered by NASDAQ for a co-op position'}, {'name': 'NDI', 'type': 'ID', 'description': 'A company offering co-op positions with average compensation details'}, {'name': 'Coop Average', 'type': 'value', 'description': 'Average compensation offered by NDI for co-op positions'}, {'name': 'Newfront Insurance', 'type': 'ID', 'description': 'A company offering co-op positions with specified compensation'}, {'name': '90/hr', 'type': 'value', 'description': 'Hourly rate offered by Newfront Insurance for a 6th co-op position'}, {'name': 'Nextroll', 'type': 'ID', 'description': 'A company offering co-op positions with specified compensation and benefits'}, {'name': '57/hr', 'type': 'value', 'description': 'Hourly rate offered by Nextroll for a co-op position'}, {'name': '60/month WFH allowance', 'type': 'value', 'description': 'Monthly work-from-home allowance offered by Nextroll'}, {'name': 'Nissan', 'type': 'ID', 'description': 'A company offering co-op positions with variable compensation'}, {'name': '19-23/hr', 'type': 'value', 'description': 'Hourly rate range offered by Nissan depending on the term'}, {'name': 'Nokia', 'type': 'ID', 'description': 'A company offering co-op positions with specified compensation for different years'}, {'name': '25/hr', 'type': 'value', 'description': 'Hourly rate offered by Nokia for a 4th co-op position'}, {'name': '33/hr', 'type': 'value', 'description': 'Hourly rate offered by Nokia for 3rd and 4th year positions'}, {'name': 'Noom', 'type': 'ID', 'description': 'A company offering co-op positions with specified compensation and housing benefits'}, {'name': '47 USD/hr', 'type': 'value', 'description': 'Hourly rate offered by Noom for a co-op position'}, {'name': '1500 USD/mo housing', 'type': 'value', 'description': 'Monthly housing allowance offered by Noom'}, {'name': 'Norm Li', 'type': 'ID', 'description': 'A company offering co-op positions with variable compensation'}, {'name': '20-30/hr', 'type': 'value', 'description': 'Hourly rate range offered by Norm Li for a co-op position'}, {'name': 'Nvidia', 'type': 'ID', 'description': 'A company offering co-op positions with specified compensation and housing benefits'}, {'name': '36/hr', 'type': 'value', 'description': 'Hourly rate offered by Nvidia for a 4a co-op position'}, {'name': '500/wk housing', 'type': 'value', 'description': 'Weekly housing allowance offered by Nvidia'}, {'name': 'NuraLogix', 'type': 'ID', 'description': 'A company offering co-op positions with specified compensation'}, {'name': '28/hr', 'type': 'value', 'description': 'Hourly rate offered by NuraLogix for a 3rd co-op position'}, {'name': 'Nuro', 'type': 'ID', 'description': 'A company offering co-op positions with specified compensation and bonus'}, {'name': '9000 USD/mo', 'type': 'value', 'description': 'Monthly salary offered by Nuro for a co-op position'}, {'name': '3k bonus', 'type': 'value', 'description': 'Bonus offered by Nuro in addition to monthly salary'}, {'name': 'Nuvalence', 'type': 'ID', 'description': 'A company offering co-op positions with specified compensation for remote work'}, {'name': '55/hr', 'type': 'value', 'description': 'Hourly rate offered by Nuvalence for a 5th co-op position'}, {'name': '60/hr remote', 'type': 'value', 'description': 'Hourly rate offered by Nuvalence for remote work'}, {'name': 'Nuvation', 'type': 'ID', 'description': 'A company offering co-op positions with specified weekly compensation'}, {'name': '1350/week', 'type': 'value', 'description': 'Weekly salary offered by Nuvation for a 3rd co-op position'}, {'name': '2023', 'type': 'value', 'description': 'Year associated with the co-op position at Nuvation'}, {'name': 'OANDA', 'type': 'ID', 'description': 'A company offering co-op positions with specified annual compensation'}, {'name': '48000/yr', 'type': 'value', 'description': 'Annual salary offered by OANDA for a 2nd co-op position'}, {'name': '65000/yr', 'type': 'value', 'description': 'Annual salary offered by OANDA for a 5th co-op position'}, {'name': 'Okta', 'type': 'ID', 'description': 'A company offering co-op positions with specified compensation range'}, {'name': '40-45/hr', 'type': 'value', 'description': 'Hourly rate range offered by Okta for a co-op position'}]
Relationships: [{'source': 'MotoInsight', 'target': '3000/mo', 'description': '3000/mo is the monthly salary offered by MotoInsight for a co-op position', 'weight': '10'}, {'source': 'Motorola Solutions', 'target': '37/hr', 'description': '37/hr is the hourly rate offered by Motorola Solutions for a 5th co-op position', 'weight': '10'}, {'source': 'Motorola Solutions', 'target': '2024', 'description': '2024 is the year associated with the co-op position at Motorola Solutions', 'weight': '10'}, {'source': 'Motorola Solutions', 'target': 'Product Design', 'description': 'Product Design is the role associated with the co-op position at Motorola Solutions', 'weight': '10'}, {'source': 'Moveworks', 'target': '9.5K/mo', 'description': '9.5K/mo is the monthly salary option offered by Moveworks for a co-op position', 'weight': '10'}, {'source': 'Moveworks', 'target': '7.5K USD/mo', 'description': '7.5K USD/mo is an alternative monthly salary option offered by Moveworks for a co-op position', 'weight': '10'}, {'source': 'Moveworks', 'target': '500/mo stipend', 'description': '500/mo stipend is offered by Moveworks in addition to salary', 'weight': '10'}, {'source': 'Mozilla', 'target': '30/hr', 'description': "30/hr is the hourly rate offered by Mozilla for a master's level co-op position", 'weight': '10'}, {'source': 'Munich Re', 'target': '1100/week', 'description': '1100/week is the weekly salary offered by Munich Re for a co-op position', 'weight': '10'}, {'source': 'Munich Re', 'target': '1500 CAD stipend', 'description': '1500 CAD stipend is offered by Munich Re in addition to weekly salary', 'weight': '10'}, {'source': 'NASDAQ', 'target': '28/hr', 'description': '28/hr is the hourly rate offered by NASDAQ for a co-op position', 'weight': '10'}, {'source': 'NDI', 'target': 'Coop Average', 'description': 'Coop Average is the average compensation offered by NDI for co-op positions', 'weight': '10'}, {'source': 'Newfront Insurance', 'target': '90/hr', 'description': '90/hr is the hourly rate offered by Newfront Insurance for a 6th co-op position', 'weight': '10'}, {'source': 'Nextroll', 'target': '57/hr', 'description': '57/hr is the hourly rate offered by Nextroll for a co-op position', 'weight': '10'}, {'source': 'Nextroll', 'target': '60/month WFH allowance', 'description': '60/month WFH allowance is offered by Nextroll', 'weight': '10'}, {'source': 'Nissan', 'target': '19-23/hr', 'description': '19-23/hr is the hourly rate range offered by Nissan depending on the term', 'weight': '10'}, {'source': 'Nokia', 'target': '25/hr', 'description': '25/hr is the hourly rate offered by Nokia for a 4th co-op position', 'weight': '10'}, {'source': 'Nokia', 'target': '33/hr', 'description': '33/hr is the hourly rate offered by Nokia for 3rd and 4th year positions', 'weight': '10'}, {'source': 'Noom', 'target': '47 USD/hr', 'description': '47 USD/hr is the hourly rate offered by Noom for a co-op position', 'weight': '10'}, {'source': 'Noom', 'target': '1500 USD/mo housing', 'description': '1500 USD/mo housing is the monthly housing allowance offered by Noom', 'weight': '10'}, {'source': 'Norm Li', 'target': '20-30/hr', 'description': '20-30/hr is the hourly rate range offered by Norm Li for a co-op position', 'weight': '10'}, {'source': 'Nvidia', 'target': '36/hr', 'description': '36/hr is the hourly rate offered by Nvidia for a 4a co-op position', 'weight': '10'}, {'source': 'Nvidia', 'target': '500/wk housing', 'description': '500/wk housing is the weekly housing allowance offered by Nvidia', 'weight': '10'}, {'source': 'NuraLogix', 'target': '28/hr', 'description': '28/hr is the hourly rate offered by NuraLogix for a 3rd co-op position', 'weight': '10'}, {'source': 'Nuro', 'target': '9000 USD/mo', 'description': '9000 USD/mo is the monthly salary offered by Nuro for a co-op position', 'weight': '10'}, {'source': 'Nuro', 'target': '3k bonus', 'description': '3k bonus is offered by Nuro in addition to monthly salary', 'weight': '10'}, {'source': 'Nuvalence', 'target': '55/hr', 'description': '55/hr is the hourly rate offered by Nuvalence for a 5th co-op position', 'weight': '10'}, {'source': 'Nuvalence', 'target': '60/hr remote', 'description': '60/hr remote is the hourly rate offered by Nuvalence for remote work', 'weight': '10'}, {'source': 'Nuvation', 'target': '1350/week', 'description': '1350/week is the weekly salary offered by Nuvation for a 3rd co-op position', 'weight': '10'}, {'source': 'Nuvation', 'target': '2023', 'description': '2023 is the year associated with the co-op position at Nuvation', 'weight': '10'}, {'source': 'OANDA', 'target': '48000/yr', 'description': '48000/yr is the annual salary offered by OANDA for a 2nd co-op position', 'weight': '10'}, {'source': 'OANDA', 'target': '65000/yr', 'description': '65000/yr is the annual salary offered by OANDA for a 5th co-op position', 'weight': '10'}, {'source': 'Okta', 'target': '40-45/hr', 'description': '40-45/hr is the hourly rate range offered by Okta for a co-op position', 'weight': '10'}]
✅ Graph successfully inserted into Neo4j!

2025-10-05 02:14:05,412 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Entities: [{'name': 'OLG', 'type': 'ID', 'description': 'Identifier for a company offering co-op positions'}, {'name': '23/hr', 'type': 'value', 'description': 'Hourly wage for the first co-op position at OLG'}, {'name': 'OMERS', 'type': 'ID', 'description': 'Identifier for a company offering co-op positions'}, {'name': '24/hr', 'type': 'value', 'description': 'Hourly wage for co-op positions at OMERS, with a higher rate for the fourth co-op'}, {'name': 'Onsemi', 'type': 'ID', 'description': 'Identifier for a company offering co-op positions'}, {'name': '30.29/hr', 'type': 'value', 'description': 'Hourly wage for co-op positions at Onsemi'}, {'name': 'Ontario Institute for Cancer Research', 'type': 'ID', 'description': 'Identifier for a research institute offering co-op positions'}, {'name': '18.6/hr', 'type': 'value', 'description': 'Hourly wage for the first co-op position at the Ontario Institute for Cancer Research'}, {'name': '21/hr', 'type': 'value', 'description': 'Hourly wage for the second co-op position at the Ontario Institute for Cancer Research'}, {'name': 'Ontario Ministry of Health', 'type': 'ID', 'description': 'Identifier for a government ministry offering co-op positions'}, {'name': '17.27/hr', 'type': 'value', 'description': 'Hourly wage for the first co-op position at the Ontario Ministry of Health'}, {'name': '18.42/hr', 'type': 'value', 'description': 'Hourly wage for the second co-op position at the Ontario Ministry of Health'}, {'name': 'OpenText', 'type': 'ID', 'description': 'Identifier for a company offering co-op positions'}, {'name': '21/hr', 'type': 'value', 'description': 'Hourly wage for the second co-op position at OpenText, similar to co-op averages'}, {'name': '~30.25/hr', 'type': 'value', 'description': 'Approximate hourly wage for the third co-op position at OpenText'}, {'name': 'OPSEU Pension Trust', 'type': 'ID', 'description': 'Identifier for a pension trust offering co-op positions'}, {'name': '1020/wk', 'type': 'value', 'description': 'Weekly wage for co-op positions at OPSEU Pension Trust'}, {'name': 'Oracle', 'type': 'ID', 'description': 'Identifier for a company offering co-op positions'}, {'name': '35/hr', 'type': 'value', 'description': 'Hourly wage for the third co-op position at Oracle'}, {'name': '40/hr', 'type': 'value', 'description': 'Hourly wage for the fourth co-op position at Oracle'}, {'name': 'Penfield.AI', 'type': 'ID', 'description': 'Identifier for a company offering co-op positions'}, {'name': '20-50/h', 'type': 'value', 'description': 'Hourly wage range for co-op positions at Penfield.AI, depending on experience'}, {'name': 'Pienso', 'type': 'ID', 'description': 'Identifier for a company offering co-op positions'}, {'name': '67/hr', 'type': 'value', 'description': 'Hourly wage for the fifth co-op position at Pienso'}, {'name': 'PlayStation', 'type': 'ID', 'description': 'Identifier for a company offering co-op positions'}, {'name': '31/hr', 'type': 'value', 'description': 'Hourly wage for the second co-op position at PlayStation'}, {'name': 'PointClickCare', 'type': 'ID', 'description': 'Identifier for a company offering co-op positions'}, {'name': '25-32/hr', 'type': 'value', 'description': 'Hourly wage range for the second co-op position at PointClickCare'}, {'name': 'Pratt and Whitney', 'type': 'ID', 'description': 'Identifier for a company offering co-op positions'}, {'name': '22/hr', 'type': 'value', 'description': 'Hourly wage for the first co-op position at Pratt and Whitney'}, {'name': 'primer.ai', 'type': 'ID', 'description': 'Identifier for a company offering co-op positions'}, {'name': '50/hr', 'type': 'value', 'description': 'Hourly wage for the fourth co-op position at primer.ai'}, {'name': 'Prodigy Education', 'type': 'ID', 'description': 'Identifier for a company offering co-op positions'}, {'name': '33/hr', 'type': 'value', 'description': 'Hourly wage for the fifth co-op position at Prodigy Education'}, {'name': 'Qualcomm (Markham)', 'type': 'ID', 'description': 'Identifier for a company offering co-op positions'}, {'name': '42/hr', 'type': 'value', 'description': 'Hourly wage for the fourth-year co-op position at Qualcomm (Markham'}, {'name': '1500/mo', 'type': 'value', 'description': 'Monthly housing allowance for co-op positions at Qualcomm (Markham'}, {'name': 'Questrade', 'type': 'ID', 'description': 'Identifier for a company offering co-op positions'}, {'name': '21/hr', 'type': 'value', 'description': 'Hourly wage for the first co-op position at Questrade'}, {'name': 'Radix Labs', 'type': 'ID', 'description': 'Identifier for a company offering co-op positions'}, {'name': '25/hr USD', 'type': 'value', 'description': 'Hourly wage in USD for co-op positions at Radix Labs'}, {'name': 'Railvision Analytics', 'type': 'ID', 'description': 'Identifier for a company offering co-op positions'}, {'name': '30/hr', 'type': 'value', 'description': 'Hourly wage for the third co-op position at Railvision Analytics'}]
Relationships: [{'source': 'OLG', 'target': '23/hr', 'description': '23/hr is the hourly wage for the first co-op position at OLG', 'weight': '10'}, {'source': 'OMERS', 'target': '24/hr', 'description': '24/hr is the hourly wage for co-op positions at OMERS, with a higher rate for the fourth co-op', 'weight': '10'}, {'source': 'Onsemi', 'target': '30.29/hr', 'description': '30.29/hr is the hourly wage for co-op positions at Onsemi', 'weight': '10'}, {'source': 'Ontario Institute for Cancer Research', 'target': '18.6/hr', 'description': '18.6/hr is the hourly wage for the first co-op position at the Ontario Institute for Cancer Research', 'weight': '10'}, {'source': 'Ontario Institute for Cancer Research', 'target': '21/hr', 'description': '21/hr is the hourly wage for the second co-op position at the Ontario Institute for Cancer Research', 'weight': '10'}, {'source': 'Ontario Ministry of Health', 'target': '17.27/hr', 'description': '17.27/hr is the hourly wage for the first co-op position at the Ontario Ministry of Health', 'weight': '10'}, {'source': 'Ontario Ministry of Health', 'target': '18.42/hr', 'description': '18.42/hr is the hourly wage for the second co-op position at the Ontario Ministry of Health', 'weight': '10'}, {'source': 'OpenText', 'target': '21/hr', 'description': '21/hr is the hourly wage for the second co-op position at OpenText, similar to co-op averages', 'weight': '10'}, {'source': 'OpenText', 'target': '~30.25/hr', 'description': '~30.25/hr is the approximate hourly wage for the third co-op position at OpenText', 'weight': '10'}, {'source': 'OPSEU Pension Trust', 'target': '1020/wk', 'description': '1020/wk is the weekly wage for co-op positions at OPSEU Pension Trust', 'weight': '10'}, {'source': 'Oracle', 'target': '35/hr', 'description': '35/hr is the hourly wage for the third co-op position at Oracle', 'weight': '10'}, {'source': 'Oracle', 'target': '40/hr', 'description': '40/hr is the hourly wage for the fourth co-op position at Oracle', 'weight': '10'}, {'source': 'Penfield.AI', 'target': '20-50/h', 'description': '20-50/h is the hourly wage range for co-op positions at Penfield.AI, depending on experience', 'weight': '10'}, {'source': 'Pienso', 'target': '67/hr', 'description': '67/hr is the hourly wage for the fifth co-op position at Pienso', 'weight': '10'}, {'source': 'PlayStation', 'target': '31/hr', 'description': '31/hr is the hourly wage for the second co-op position at PlayStation', 'weight': '10'}, {'source': 'PointClickCare', 'target': '25-32/hr', 'description': '25-32/hr is the hourly wage range for the second co-op position at PointClickCare', 'weight': '10'}, {'source': 'Pratt and Whitney', 'target': '22/hr', 'description': '22/hr is the hourly wage for the first co-op position at Pratt and Whitney', 'weight': '10'}, {'source': 'primer.ai', 'target': '50/hr', 'description': '50/hr is the hourly wage for the fourth co-op position at primer.ai', 'weight': '10'}, {'source': 'Prodigy Education', 'target': '33/hr', 'description': '33/hr is the hourly wage for the fifth co-op position at Prodigy Education', 'weight': '10'}, {'source': 'Qualcomm (Markham)', 'target': '42/hr', 'description': '42/hr is the hourly wage for the fourth-year co-op position at Qualcomm (Markham', 'weight': None}, {'source': 'Qualcomm (Markham)', 'target': '1500/mo', 'description': '1500/mo is the monthly housing allowance for co-op positions at Qualcomm (Markham', 'weight': None}, {'source': 'Questrade', 'target': '21/hr', 'description': '21/hr is the hourly wage for the first co-op position at Questrade', 'weight': '10'}, {'source': 'Radix Labs', 'target': '25/hr USD', 'description': '25/hr USD is the hourly wage for co-op positions at Radix Labs', 'weight': '10'}, {'source': 'Railvision Analytics', 'target': '30/hr', 'description': '30/hr is the hourly wage for the third co-op position at Railvision Analytics', 'weight': '10'}]
✅ Graph successfully inserted into Neo4j!

2025-10-05 02:14:29,151 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Entities: [{'name': 'Raposa Research', 'type': 'ID', 'description': 'A company offering hourly wage positions'}, {'name': '100?/hr USD', 'type': 'value', 'description': 'An hourly wage rate offered by Raposa Research, with uncertainty indicated by the question mark'}, {'name': 'RBC', 'type': 'ID', 'description': 'A company offering various co-op positions with specified hourly wages'}, {'name': '22/hr (2nd coop)', 'type': 'value', 'description': 'An hourly wage rate for a second co-op position at RBC'}, {'name': 'Buisness Analyst', 'type': 'position', 'description': 'A job position offered by RBC'}, {'name': '28/hr', 'type': 'value', 'description': 'An hourly wage rate for a Data Analyst position at RBC'}, {'name': 'Data Analyst', 'type': 'position', 'description': 'A job position offered by RBC'}, {'name': '30/hr (1st coop)', 'type': 'value', 'description': 'An hourly wage rate for a first co-op position in Risk Management at RBC'}, {'name': 'Risk Management', 'type': 'position', 'description': 'A job position offered by RBC'}, {'name': '30.75 (3rd coop)', 'type': 'value', 'description': 'An hourly wage rate for a third co-op position at RBC'}, {'name': '2024', 'type': 'year', 'description': 'The year associated with a position at RBC'}, {'name': 'SWDE', 'type': 'position', 'description': 'A job position offered by RBC'}, {'name': 'Reebee', 'type': 'ID', 'description': 'A company offering co-op positions with wages above average'}, {'name': '$1 above coop average, 1096/week', 'type': 'value', 'description': 'A wage rate offered by Reebee, indicating a weekly pay above the co-op average'}, {'name': 'Relay Financial', 'type': 'ID', 'description': 'A company offering positions with variable hourly wages depending on the term'}, {'name': '27-43/hr depending on term', 'type': 'value', 'description': 'A range of hourly wages offered by Relay Financial, dependent on the term'}, {'name': 'Relic Entertainment', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly wages'}, {'name': '25/hr (2nd coop)', 'type': 'value', 'description': 'An hourly wage rate for a second co-op position at Relic Entertainment'}, {'name': 'Remitbee', 'type': 'ID', 'description': 'A company listed with a note to see the blacklist, offering co-op positions'}, {'name': '20/hr (3rd coop)', 'type': 'value', 'description': 'An hourly wage rate for a third co-op position at Remitbee'}, {'name': 'Replicant Inc', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly wages'}, {'name': '35-37/hr (4th coop)', 'type': 'value', 'description': 'A range of hourly wages for a fourth co-op position at Replicant Inc'}, {'name': 'ResQ', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly wages'}, {'name': '36/hr (5th coop)', 'type': 'value', 'description': 'An hourly wage rate for a fifth co-op position at ResQ'}, {'name': 'Ritual', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly wages'}, {'name': '20/hr (1st coop)', 'type': 'value', 'description': 'An hourly wage rate for a first co-op position at Ritual'}, {'name': '2022', 'type': 'year', 'description': 'The year associated with a position at Ritual'}, {'name': 'QA', 'type': 'position', 'description': 'A job position offered by Ritual'}, {'name': '46/hr (6th coop)', 'type': 'value', 'description': 'An hourly wage rate for a sixth co-op position at Ritual'}, {'name': 'Robinhood (Canada)', 'type': 'ID', 'description': 'A company offering positions with specified hourly wages'}, {'name': '33/hr', 'type': 'value', 'description': 'An hourly wage rate offered by Robinhood (Canada'}, {'name': '2025', 'type': 'year', 'description': 'The year associated with a position at Robinhood (Canada'}, {'name': 'Robinhood', 'type': 'ID', 'description': 'A company offering positions with specified hourly wages and additional benefits'}, {'name': '48 USD/hr', 'type': 'value', 'description': 'An hourly wage rate offered by Robinhood'}, {'name': '2000 USD/mo housing', 'type': 'benefit', 'description': 'A monthly housing benefit offered by Robinhood'}, {'name': 'Roblox', 'type': 'ID', 'description': 'A company offering positions with specified hourly wages and additional benefits'}, {'name': '56 USD/hr, 62/hr (DS), 60/hr', 'type': 'value', 'description': 'A range of hourly wages offered by Roblox for different positions'}, {'name': '1k WFH stipend, 7K housing stipend', 'type': 'benefit', 'description': 'Work-from-home and housing stipends offered by Roblox'}, {'name': 'Rocscience', 'type': 'ID', 'description': 'A company offering co-op positions with wages at or above average'}, {'name': 'coop average or $1 above (20-28/hr)', 'type': 'value', 'description': 'A wage range offered by Rocscience, indicating pay at or above the co-op average'}, {'name': 'Roo', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly wages'}, {'name': '35/hr USD (4th coop)', 'type': 'value', 'description': 'An hourly wage rate for a fourth co-op position at Roo'}, {'name': '2024', 'type': 'year', 'description': 'The year associated with a position at Roo'}, {'name': 'SWE', 'type': 'position', 'description': 'A job position offered by Roo'}, {'name': 'Sagen', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly wages'}, {'name': '23/hr (2nd coop), 25/hr (3rd coop)', 'type': 'value', 'description': 'Hourly wage rates for second and third co-op positions at Sagen'}, {'name': '2022', 'type': 'year', 'description': 'The year associated with a position at Sagen'}]
Relationships: [{'source': 'Raposa Research', 'target': '100?/hr USD', 'description': 'The hourly wage rate is associated with Raposa Research', 'weight': '10'}, {'source': 'RBC', 'target': '22/hr (2nd coop)', 'description': 'The hourly wage rate is associated with a second co-op position at RBC', 'weight': '10'}, {'source': 'RBC', 'target': 'Buisness Analyst', 'description': 'The position of Business Analyst is offered by RBC', 'weight': '10'}, {'source': 'RBC', 'target': '28/hr', 'description': 'The hourly wage rate is associated with a Data Analyst position at RBC', 'weight': '10'}, {'source': 'RBC', 'target': 'Data Analyst', 'description': 'The position of Data Analyst is offered by RBC', 'weight': '10'}, {'source': 'RBC', 'target': '30/hr (1st coop)', 'description': 'The hourly wage rate is associated with a first co-op position in Risk Management at RBC', 'weight': '10'}, {'source': 'RBC', 'target': 'Risk Management', 'description': 'The position of Risk Management is offered by RBC', 'weight': '10'}, {'source': 'RBC', 'target': '30.75 (3rd coop)', 'description': 'The hourly wage rate is associated with a third co-op position at RBC', 'weight': '10'}, {'source': 'RBC', 'target': '2024', 'description': 'The year 2024 is associated with a position at RBC', 'weight': '10'}, {'source': 'RBC', 'target': 'SWDE', 'description': 'The position of SWDE is offered by RBC', 'weight': '10'}, {'source': 'Reebee', 'target': '$1 above coop average, 1096/week', 'description': 'The wage rate is associated with Reebee, indicating a weekly pay above the co-op average', 'weight': '10'}, {'source': 'Relay Financial', 'target': '27-43/hr depending on term', 'description': 'The range of hourly wages is associated with Relay Financial, dependent on the term', 'weight': '10'}, {'source': 'Relic Entertainment', 'target': '25/hr (2nd coop)', 'description': 'The hourly wage rate is associated with a second co-op position at Relic Entertainment', 'weight': '10'}, {'source': 'Remitbee', 'target': '20/hr (3rd coop)', 'description': 'The hourly wage rate is associated with a third co-op position at Remitbee', 'weight': '10'}, {'source': 'Replicant Inc', 'target': '35-37/hr (4th coop)', 'description': 'The range of hourly wages is associated with a fourth co-op position at Replicant Inc', 'weight': '10'}, {'source': 'ResQ', 'target': '36/hr (5th coop)', 'description': 'The hourly wage rate is associated with a fifth co-op position at ResQ', 'weight': '10'}, {'source': 'Ritual', 'target': '20/hr (1st coop)', 'description': 'The hourly wage rate is associated with a first co-op position at Ritual', 'weight': '10'}, {'source': 'Ritual', 'target': '2022', 'description': 'The year 2022 is associated with a position at Ritual', 'weight': '10'}, {'source': 'Ritual', 'target': 'QA', 'description': 'The position of QA is offered by Ritual', 'weight': '10'}, {'source': 'Ritual', 'target': '46/hr (6th coop)', 'description': 'The hourly wage rate is associated with a sixth co-op position at Ritual', 'weight': '10'}, {'source': 'Robinhood (Canada)', 'target': '33/hr', 'description': 'The hourly wage rate is associated with Robinhood (Canada', 'weight': None}, {'source': 'Robinhood (Canada)', 'target': '2025', 'description': 'The year 2025 is associated with a position at Robinhood (Canada', 'weight': None}, {'source': 'Robinhood', 'target': '48 USD/hr', 'description': 'The hourly wage rate is associated with Robinhood', 'weight': '10'}, {'source': 'Robinhood', 'target': '2000 USD/mo housing', 'description': 'The monthly housing benefit is associated with Robinhood', 'weight': '10'}, {'source': 'Roblox', 'target': '56 USD/hr, 62/hr (DS), 60/hr', 'description': 'The range of hourly wages is associated with Roblox for different positions', 'weight': '10'}, {'source': 'Roblox', 'target': '1k WFH stipend, 7K housing stipend', 'description': 'The work-from-home and housing stipends are associated with Roblox', 'weight': '10'}, {'source': 'Rocscience', 'target': 'coop average or $1 above (20-28/hr)', 'description': 'The wage range is associated with Rocscience, indicating pay at or above the co-op average', 'weight': '10'}, {'source': 'Roo', 'target': '35/hr USD (4th coop)', 'description': 'The hourly wage rate is associated with a fourth co-op position at Roo', 'weight': '10'}, {'source': 'Roo', 'target': '2024', 'description': 'The year 2024 is associated with a position at Roo', 'weight': '10'}, {'source': 'Roo', 'target': 'SWE', 'description': 'The position of SWE is offered by Roo', 'weight': '10'}, {'source': 'Sagen', 'target': '23/hr (2nd coop), 25/hr (3rd coop)', 'description': 'The hourly wage rates are associated with second and third co-op positions at Sagen', 'weight': '10'}, {'source': 'Sagen', 'target': '2022', 'description': 'The year 2022 is associated with a position at Sagen', 'weight': '10'}]
✅ Graph successfully inserted into Neo4j!

2025-10-05 02:14:46,746 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Entities: [{'name': 'Samsung Research America', 'type': 'ID', 'description': 'A company offering co-op positions with specific compensation details'}, {'name': '39 USD/hr', 'type': 'value', 'description': 'The hourly rate offered by Samsung Research America for co-op positions'}, {'name': '9k USD stipend', 'type': 'value', 'description': 'The stipend offered by Samsung Research America for co-op positions'}, {'name': 'SAP', 'type': 'ID', 'description': 'A company offering co-op positions with specific compensation details'}, {'name': '$1 above the coop average, 24/hr (2nd coop)', 'type': 'value', 'description': 'The compensation details offered by SAP for co-op positions'}, {'name': 'SAP ML', 'type': 'ID', 'description': 'A company offering co-op positions with specific compensation details'}, {'name': '40/hr (1st coop)', 'type': 'value', 'description': 'The compensation details offered by SAP ML for co-op positions'}, {'name': 'Scotiabank (Data Science/Soft Dev)', 'type': 'ID', 'description': 'A company offering co-op positions with specific compensation details'}, {'name': '~31/hr (3rd year)', 'type': 'value', 'description': 'The compensation details offered by Scotiabank for co-op positions'}, {'name': 'Scrawlr', 'type': 'ID', 'description': 'A company offering co-op positions with specific compensation details'}, {'name': 'coop average +~20% depending on experience', 'type': 'value', 'description': 'The compensation details offered by Scrawlr for co-op positions'}, {'name': 'Shinydocs', 'type': 'ID', 'description': 'A company offering co-op positions with specific compensation details'}, {'name': 'coop average', 'type': 'value', 'description': 'The compensation details offered by Shinydocs for co-op positions'}, {'name': '40-50/hr depending on term', 'type': 'value', 'description': 'The compensation details offered for co-op positions, unspecified company'}, {'name': '1000/mo stipend', 'type': 'value', 'description': 'The stipend offered for co-op positions, unspecified company'}, {'name': 'Shoplogic', 'type': 'ID', 'description': 'A company offering co-op positions with specific compensation details'}, {'name': '27/hr', 'type': 'value', 'description': 'The compensation details offered by Shoplogic for co-op positions'}, {'name': 'Sibros', 'type': 'ID', 'description': 'A company offering co-op positions with specific compensation details'}, {'name': '45/hr USD', 'type': 'value', 'description': 'The compensation details offered by Sibros for co-op positions'}, {'name': '700 housing stipend', 'type': 'value', 'description': 'The housing stipend offered by Sibros for co-op positions'}, {'name': 'SickKids', 'type': 'ID', 'description': 'A company offering co-op positions with specific compensation details'}, {'name': 'Coop Average', 'type': 'value', 'description': 'The compensation details offered by SickKids for co-op positions'}, {'name': 'SideFX', 'type': 'ID', 'description': 'A company offering co-op positions with specific compensation details'}, {'name': '35/hr, 45-47/hr (6th coop), 36/hr + 3*(work term #) also reported', 'type': 'value', 'description': 'The compensation details offered by SideFX for co-op positions'}, {'name': 'Simplii Financial (CIBC) (Product Analyst)', 'type': 'ID', 'description': 'A company offering co-op positions with specific compensation details'}, {'name': '26/hr', 'type': 'value', 'description': 'The compensation details offered by Simplii Financial for co-op positions'}, {'name': 'Skydio', 'type': 'ID', 'description': 'A company offering co-op positions with specific compensation details'}, {'name': '52/hr (3rd coop)', 'type': 'value', 'description': 'The compensation details offered by Skydio for co-op positions'}, {'name': '48/hr USD (3A)', 'type': 'value', 'description': 'The compensation details offered by Skydio for co-op positions'}, {'name': '5k pretax relocation', 'type': 'value', 'description': 'The relocation stipend offered by Skydio for co-op positions'}, {'name': 'Smile CDR', 'type': 'ID', 'description': 'A company offering co-op positions with specific compensation details'}, {'name': '36/hr (3rd coop)', 'type': 'value', 'description': 'The compensation details offered by Smile CDR for co-op positions'}, {'name': 'Snap Inc', 'type': 'ID', 'description': 'A company offering co-op positions with specific compensation details'}, {'name': '$9000 USD/mo', 'type': 'value', 'description': 'The monthly compensation offered by Snap Inc for co-op positions'}, {'name': '$2500 USD/mo housing stipend + $500 USD/mo misc', 'type': 'value', 'description': 'The housing and miscellaneous stipend offered by Snap Inc for co-op positions'}, {'name': 'Snowflake computing', 'type': 'ID', 'description': 'A company offering co-op positions with specific compensation details'}, {'name': '43-55/hr', 'type': 'value', 'description': 'The compensation details offered by Snowflake computing for co-op positions'}, {'name': 'stipends', 'type': 'value', 'description': 'Additional stipends offered by Snowflake computing for co-op positions'}, {'name': 'Solana Labs', 'type': 'ID', 'description': 'A company offering co-op positions with specific compensation details'}, {'name': '60/hr USD', 'type': 'value', 'description': 'The compensation details offered by Solana Labs for co-op positions'}, {'name': '3k/mo USD housing', 'type': 'value', 'description': 'The housing stipend offered by Solana Labs for co-op positions'}, {'name': 'SoundHound', 'type': 'ID', 'description': 'A company offering co-op positions with specific compensation details'}, {'name': '6300/month', 'type': 'value', 'description': 'The monthly compensation offered by SoundHound for co-op positions'}, {'name': 'Spotwork', 'type': 'ID', 'description': 'A company offering co-op positions with specific compensation details'}, {'name': '20/hr (1st coop)', 'type': 'value', 'description': 'The compensation details offered by Spotwork for co-op positions'}]
Relationships: [{'source': 'Samsung Research America', 'target': '39 USD/hr', 'description': '39 USD/hr is the hourly rate associated with Samsung Research America', 'weight': '10'}, {'source': 'Samsung Research America', 'target': '9k USD stipend', 'description': '9k USD stipend is associated with Samsung Research America', 'weight': '10'}, {'source': 'SAP', 'target': '$1 above the coop average, 24/hr (2nd coop)', 'description': '$1 above the coop average, 24/hr (2nd coop', 'weight': None}, {'source': 'SAP ML', 'target': '40/hr (1st coop)', 'description': '40/hr (1st coop', 'weight': None}, {'source': 'Scotiabank (Data Science/Soft Dev)', 'target': '~31/hr (3rd year)', 'description': '~31/hr (3rd year', 'weight': None}, {'source': 'Scrawlr', 'target': 'coop average +~20% depending on experience', 'description': 'coop average +~20% depending on experience is the compensation associated with Scrawlr', 'weight': '10'}, {'source': 'Shinydocs', 'target': 'coop average', 'description': 'coop average is the compensation associated with Shinydocs', 'weight': '10'}, {'source': 'Shoplogic', 'target': '27/hr', 'description': '27/hr is the compensation associated with Shoplogic', 'weight': '10'}, {'source': 'Sibros', 'target': '45/hr USD', 'description': '45/hr USD is the compensation associated with Sibros', 'weight': '10'}, {'source': 'Sibros', 'target': '700 housing stipend', 'description': '700 housing stipend is associated with Sibros', 'weight': '10'}, {'source': 'SickKids', 'target': 'Coop Average', 'description': 'Coop Average is the compensation associated with SickKids', 'weight': '10'}, {'source': 'SideFX', 'target': '35/hr, 45-47/hr (6th coop), 36/hr + 3*(work term #) also reported', 'description': '35/hr, 45-47/hr (6th coop', 'weight': None}, {'source': 'Simplii Financial (CIBC) (Product Analyst)', 'target': '26/hr', 'description': '26/hr is the compensation associated with Simplii Financial', 'weight': '10'}, {'source': 'Skydio', 'target': '52/hr (3rd coop)', 'description': '52/hr (3rd coop', 'weight': None}, {'source': 'Skydio', 'target': '48/hr USD (3A)', 'description': '48/hr USD (3A', 'weight': None}, {'source': 'Skydio', 'target': '5k pretax relocation', 'description': '5k pretax relocation is associated with Skydio', 'weight': '10'}, {'source': 'Smile CDR', 'target': '36/hr (3rd coop)', 'description': '36/hr (3rd coop', 'weight': None}, {'source': 'Snap Inc', 'target': '$9000 USD/mo', 'description': '$9000 USD/mo is the compensation associated with Snap Inc', 'weight': '10'}, {'source': 'Snap Inc', 'target': '$2500 USD/mo housing stipend + $500 USD/mo misc', 'description': '$2500 USD/mo housing stipend + $500 USD/mo misc is associated with Snap Inc', 'weight': '10'}, {'source': 'Snowflake computing', 'target': '43-55/hr', 'description': '43-55/hr is the compensation associated with Snowflake computing', 'weight': '10'}, {'source': 'Snowflake computing', 'target': 'stipends', 'description': 'stipends are associated with Snowflake computing', 'weight': '10'}, {'source': 'Solana Labs', 'target': '60/hr USD', 'description': '60/hr USD is the compensation associated with Solana Labs', 'weight': '10'}, {'source': 'Solana Labs', 'target': '3k/mo USD housing', 'description': '3k/mo USD housing is associated with Solana Labs', 'weight': '10'}, {'source': 'SoundHound', 'target': '6300/month', 'description': '6300/month is the compensation associated with SoundHound', 'weight': '10'}, {'source': 'Spotwork', 'target': '20/hr (1st coop)', 'description': '20/hr (1st coop', 'weight': None}]
✅ Graph successfully inserted into Neo4j!

2025-10-05 02:15:03,643 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Entities: [{'name': 'Spotwork', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly rates'}, {'name': '22/hr', 'type': 'value', 'description': 'Hourly rate for a 2nd co-op position at Spotwork'}, {'name': '2023', 'type': 'value', 'description': 'Year associated with the co-op position at Spotwork'}, {'name': 'Mobile SWE', 'type': 'metric', 'description': 'Position title for the co-op at Spotwork'}, {'name': 'SPS Commerce', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly rates'}, {'name': '30/hr', 'type': 'value', 'description': 'Hourly rate for a 3rd co-op position at SPS Commerce in 2023'}, {'name': '35/hr', 'type': 'value', 'description': 'Hourly rate for a 3rd co-op position at SPS Commerce in 2024'}, {'name': 'Square', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly rates and benefits'}, {'name': '38/hr', 'type': 'value', 'description': 'Hourly rate for a position at Square'}, {'name': '1k/mo housing', 'type': 'value', 'description': 'Monthly housing allowance provided by Square'}, {'name': 'Squaredance', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly rates'}, {'name': '35/hr', 'type': 'value', 'description': 'Hourly rate for a 2nd co-op position at Squaredance'}, {'name': 'Squarepoint Capital', 'type': 'ID', 'description': 'A company offering co-op positions with specified annual salary and benefits'}, {'name': '85k/year', 'type': 'value', 'description': 'Annual salary for a position at Squarepoint Capital'}, {'name': '1.5k/mo allowance', 'type': 'value', 'description': 'Monthly allowance provided by Squarepoint Capital'}, {'name': 'SS&C Technologies', 'type': 'ID', 'description': 'A company offering co-op positions with varying hourly rates'}, {'name': 'Stablecorp', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly rates'}, {'name': '22.5/hr', 'type': 'value', 'description': 'Hourly rate for a 2nd co-op position at Stablecorp'}, {'name': 'Stackadapt', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly rates'}, {'name': '50/hr', 'type': 'value', 'description': 'Hourly rate for a 5th co-op position at Stackadapt'}, {'name': 'Standardbio Tools', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly rates and benefits'}, {'name': '22/hr', 'type': 'value', 'description': 'Hourly rate for a 3rd co-op position at Standardbio Tools'}, {'name': '4% vacation pay', 'type': 'value', 'description': 'Vacation pay percentage provided by Standardbio Tools'}, {'name': 'Stealth Startup', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly rates'}, {'name': '64/hr', 'type': 'value', 'description': 'Hourly rate for a position at Stealth Startup'}, {'name': 'Stratum ai', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly rates'}, {'name': '30-35/hr', 'type': 'value', 'description': 'Hourly rate range for a position at Stratum ai'}, {'name': 'Super.com', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly rates and benefits'}, {'name': '37/hr', 'type': 'value', 'description': 'Hourly rate for a 3rd co-op position at Super.com'}, {'name': '39/hr', 'type': 'value', 'description': 'Hourly rate for a 5th co-op position at Super.com'}, {'name': 'Weekly Uber Eats', 'type': 'value', 'description': 'Weekly benefit provided by Super.com'}, {'name': 'Sync.com', 'type': 'ID', 'description': 'A company offering co-op positions with varying hourly rates'}, {'name': '15-25/hr', 'type': 'value', 'description': 'Hourly rate range depending on experience at Sync.com'}, {'name': 'System 1', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly rates'}, {'name': '28/hr', 'type': 'value', 'description': 'Hourly rate for a 2nd co-op position at System 1'}, {'name': 'Tactic Studios', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly rates'}, {'name': '35/hr', 'type': 'value', 'description': 'Hourly rate for a position at Tactic Studios'}, {'name': 'Tealbook', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly rates'}, {'name': '35/hr', 'type': 'value', 'description': 'Hourly rate for a position at Tealbook'}, {'name': 'Tenneco', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly rates and positions'}, {'name': '20/hr', 'type': 'value', 'description': 'Hourly rate for a 1st co-op position at Tenneco'}, {'name': '2022', 'type': 'value', 'description': 'Year associated with the co-op position at Tenneco'}, {'name': 'Engineering', 'type': 'metric', 'description': 'Position title for the co-op at Tenneco'}]
Relationships: [{'source': 'Spotwork', 'target': '22/hr', 'description': '22/hr is the hourly rate for a 2nd co-op position at Spotwork', 'weight': '10'}, {'source': 'Spotwork', 'target': '2023', 'description': '2023 is the year associated with the co-op position at Spotwork', 'weight': '10'}, {'source': 'Spotwork', 'target': 'Mobile SWE', 'description': 'Mobile SWE is the position title for the co-op at Spotwork', 'weight': '10'}, {'source': 'SPS Commerce', 'target': '30/hr', 'description': '30/hr is the hourly rate for a 3rd co-op position at SPS Commerce in 2023', 'weight': '10'}, {'source': 'SPS Commerce', 'target': '35/hr', 'description': '35/hr is the hourly rate for a 3rd co-op position at SPS Commerce in 2024', 'weight': '10'}, {'source': 'Square', 'target': '38/hr', 'description': '38/hr is the hourly rate for a position at Square', 'weight': '10'}, {'source': 'Square', 'target': '1k/mo housing', 'description': '1k/mo housing is the monthly housing allowance provided by Square', 'weight': '10'}, {'source': 'Squaredance', 'target': '35/hr', 'description': '35/hr is the hourly rate for a 2nd co-op position at Squaredance', 'weight': '10'}, {'source': 'Squarepoint Capital', 'target': '85k/year', 'description': '85k/year is the annual salary for a position at Squarepoint Capital', 'weight': '10'}, {'source': 'Squarepoint Capital', 'target': '1.5k/mo allowance', 'description': '1.5k/mo allowance is the monthly allowance provided by Squarepoint Capital', 'weight': '10'}, {'source': 'Stablecorp', 'target': '22.5/hr', 'description': '22.5/hr is the hourly rate for a 2nd co-op position at Stablecorp', 'weight': '10'}, {'source': 'Stackadapt', 'target': '50/hr', 'description': '50/hr is the hourly rate for a 5th co-op position at Stackadapt', 'weight': '10'}, {'source': 'Standardbio Tools', 'target': '22/hr', 'description': '22/hr is the hourly rate for a 3rd co-op position at Standardbio Tools', 'weight': '10'}, {'source': 'Standardbio Tools', 'target': '4% vacation pay', 'description': '4% vacation pay is the vacation pay percentage provided by Standardbio Tools', 'weight': '10'}, {'source': 'Stealth Startup', 'target': '64/hr', 'description': '64/hr is the hourly rate for a position at Stealth Startup', 'weight': '10'}, {'source': 'Stratum ai', 'target': '30-35/hr', 'description': '30-35/hr is the hourly rate range for a position at Stratum ai', 'weight': '10'}, {'source': 'Super.com', 'target': '37/hr', 'description': '37/hr is the hourly rate for a 3rd co-op position at Super.com', 'weight': '10'}, {'source': 'Super.com', 'target': '39/hr', 'description': '39/hr is the hourly rate for a 5th co-op position at Super.com', 'weight': '10'}, {'source': 'Super.com', 'target': 'Weekly Uber Eats', 'description': 'Weekly Uber Eats is the weekly benefit provided by Super.com', 'weight': '10'}, {'source': 'Sync.com', 'target': '15-25/hr', 'description': '15-25/hr is the hourly rate range depending on experience at Sync.com', 'weight': '10'}, {'source': 'System 1', 'target': '28/hr', 'description': '28/hr is the hourly rate for a 2nd co-op position at System 1', 'weight': '10'}, {'source': 'Tactic Studios', 'target': '35/hr', 'description': '35/hr is the hourly rate for a position at Tactic Studios', 'weight': '10'}, {'source': 'Tealbook', 'target': '35/hr', 'description': '35/hr is the hourly rate for a position at Tealbook', 'weight': '10'}, {'source': 'Tenneco', 'target': '20/hr', 'description': '20/hr is the hourly rate for a 1st co-op position at Tenneco', 'weight': '10'}, {'source': 'Tenneco', 'target': '2022', 'description': '2022 is the year associated with the co-op position at Tenneco', 'weight': '10'}, {'source': 'Tenneco', 'target': 'Engineering', 'description': 'Engineering is the position title for the co-op at Tenneco', 'weight': '10'}]
✅ Graph successfully inserted into Neo4j!

2025-10-05 02:15:21,533 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Entities: [{'name': 'TD', 'type': 'ID', 'description': 'Identifier for a company offering co-op positions'}, {'name': '31/hr (3rd coop)', 'type': 'value', 'description': 'Hourly rate for a third co-op position at TD'}, {'name': '2024', 'type': 'value', 'description': 'Year associated with the co-op position at TD'}, {'name': 'SWE', 'type': 'flag', 'description': 'Flag indicating the role is Software Engineering'}, {'name': 'Teledyne Dalsa', 'type': 'ID', 'description': 'Identifier for a company offering co-op positions'}, {'name': 'Coop Average', 'type': 'value', 'description': 'Average co-op salary at Teledyne Dalsa'}, {'name': 'Tesla', 'type': 'ID', 'description': 'Identifier for a company offering co-op positions'}, {'name': '32/hr (remote), 28-32 USD/hr (onsite, Fremont/Palo Alto)', 'type': 'value', 'description': 'Hourly rate for remote and onsite co-op positions at Tesla'}, {'name': '~4k relocation (onsite, Fremont/Palo Alto)', 'type': 'value', 'description': 'Relocation package for onsite co-op positions at Tesla'}, {'name': 'Texada Software', 'type': 'ID', 'description': 'Identifier for a company offering co-op positions'}, {'name': '21/hr (1st coop), 32/hr (4th coop)', 'type': 'value', 'description': 'Hourly rate for first and fourth co-op positions at Texada Software'}, {'name': 'TextNow', 'type': 'ID', 'description': 'Identifier for a company offering co-op positions'}, {'name': '35/hr (4th coop)', 'type': 'value', 'description': 'Hourly rate for a fourth co-op position at TextNow'}, {'name': '1500 stipend (4th coop)', 'type': 'value', 'description': 'Stipend for a fourth co-op position at TextNow'}, {'name': 'The Cooperators', 'type': 'ID', 'description': 'Identifier for a company offering co-op positions'}, {'name': '20/hr (1st coop)', 'type': 'value', 'description': 'Hourly rate for a first co-op position at The Cooperators'}, {'name': 'theScore', 'type': 'ID', 'description': 'Identifier for a company offering co-op positions'}, {'name': '40/hr (4th coop), 43/hr (5th coop)', 'type': 'value', 'description': 'Hourly rate for fourth and fifth co-op positions at theScore'}, {'name': 'Thomson Reuters', 'type': 'ID', 'description': 'Identifier for a company offering co-op positions'}, {'name': 'Ranges from 30-39/hr (32/hr for 2B term), 1250/week (3rd coop)', 'type': 'value', 'description': 'Hourly and weekly rates for co-op positions at Thomson Reuters'}, {'name': 'Thumbtack', 'type': 'ID', 'description': 'Identifier for a company offering co-op positions'}, {'name': '35/hr, 42/hr (6th coop)', 'type': 'value', 'description': 'Hourly rate for co-op positions at Thumbtack'}, {'name': 'TikTok', 'type': 'ID', 'description': 'Identifier for a company offering co-op positions'}, {'name': '47/hr', 'type': 'value', 'description': 'Hourly rate for a co-op position at TikTok'}, {'name': '14/hr housing', 'type': 'value', 'description': 'Housing allowance for a co-op position at TikTok'}, {'name': 'Titanium Agency', 'type': 'ID', 'description': 'Identifier for a company offering co-op positions'}, {'name': '25/hr (1st coop), 27/hr (2nd coop), up to 35/hr for upper years', 'type': 'value', 'description': 'Hourly rate for co-op positions at Titanium Agency'}, {'name': 'TMMC (Toyota Motor Manufacturing Canada)', 'type': 'ID', 'description': 'Identifier for a company offering co-op positions'}, {'name': 'Co-op average', 'type': 'value', 'description': 'Average co-op salary at TMMC'}, {'name': 'TOOLBX', 'type': 'ID', 'description': 'Identifier for a company offering co-op positions'}, {'name': '25/hr, 30/hr (3rd year), 45/hr (6th coop)', 'type': 'value', 'description': 'Hourly rate for co-op positions at TOOLBX'}, {'name': 'Toronto Stock Exchange (TSX)', 'type': 'ID', 'description': 'Identifier for a company offering co-op positions'}, {'name': '25/hr (2nd coop)', 'type': 'value', 'description': 'Hourly rate for a second co-op position at TSX'}, {'name': 'Tophat', 'type': 'ID', 'description': 'Identifier for a company offering co-op positions'}, {'name': '30-34/hr', 'type': 'value', 'description': 'Hourly rate for a co-op position at Tophat'}]
Relationships: [{'source': 'TD', 'target': '31/hr (3rd coop)', 'description': 'The hourly rate 31/hr is associated with the company TD for a third co-op position', 'weight': '10'}, {'source': 'TD', 'target': '2024', 'description': 'The year 2024 is associated with the co-op position at TD', 'weight': '10'}, {'source': 'TD', 'target': 'SWE', 'description': 'The role SWE is associated with the co-op position at TD', 'weight': '10'}, {'source': 'Teledyne Dalsa', 'target': 'Coop Average', 'description': 'The average co-op salary is associated with Teledyne Dalsa', 'weight': '10'}, {'source': 'Tesla', 'target': '32/hr (remote), 28-32 USD/hr (onsite, Fremont/Palo Alto)', 'description': 'The hourly rates are associated with Tesla for remote and onsite co-op positions', 'weight': '10'}, {'source': 'Tesla', 'target': '~4k relocation (onsite, Fremont/Palo Alto)', 'description': 'The relocation package is associated with Tesla for onsite co-op positions', 'weight': '10'}, {'source': 'Texada Software', 'target': '21/hr (1st coop), 32/hr (4th coop)', 'description': 'The hourly rates are associated with Texada Software for first and fourth co-op positions', 'weight': '10'}, {'source': 'TextNow', 'target': '35/hr (4th coop)', 'description': 'The hourly rate 35/hr is associated with TextNow for a fourth co-op position', 'weight': '10'}, {'source': 'TextNow', 'target': '1500 stipend (4th coop)', 'description': 'The stipend is associated with TextNow for a fourth co-op position', 'weight': '10'}, {'source': 'The Cooperators', 'target': '20/hr (1st coop)', 'description': 'The hourly rate 20/hr is associated with The Cooperators for a first co-op position', 'weight': '10'}, {'source': 'theScore', 'target': '40/hr (4th coop), 43/hr (5th coop)', 'description': 'The hourly rates are associated with theScore for fourth and fifth co-op positions', 'weight': '10'}, {'source': 'Thomson Reuters', 'target': 'Ranges from 30-39/hr (32/hr for 2B term), 1250/week (3rd coop)', 'description': 'The hourly and weekly rates are associated with Thomson Reuters for co-op positions', 'weight': '10'}, {'source': 'Thumbtack', 'target': '35/hr, 42/hr (6th coop)', 'description': 'The hourly rates are associated with Thumbtack for co-op positions', 'weight': '10'}, {'source': 'TikTok', 'target': '47/hr', 'description': 'The hourly rate 47/hr is associated with TikTok for a co-op position', 'weight': '10'}, {'source': 'TikTok', 'target': '14/hr housing', 'description': 'The housing allowance is associated with TikTok for a co-op position', 'weight': '10'}, {'source': 'Titanium Agency', 'target': '25/hr (1st coop), 27/hr (2nd coop), up to 35/hr for upper years', 'description': 'The hourly rates are associated with Titanium Agency for co-op positions', 'weight': '10'}, {'source': 'TMMC (Toyota Motor Manufacturing Canada)', 'target': 'Co-op average', 'description': 'The average co-op salary is associated with TMMC', 'weight': '10'}, {'source': 'TOOLBX', 'target': '25/hr, 30/hr (3rd year), 45/hr (6th coop)', 'description': 'The hourly rates are associated with TOOLBX for co-op positions', 'weight': '10'}, {'source': 'Toronto Stock Exchange (TSX)', 'target': '25/hr (2nd coop)', 'description': 'The hourly rate 25/hr is associated with TSX for a second co-op position', 'weight': '10'}, {'source': 'Tophat', 'target': '30-34/hr', 'description': 'The hourly rate 30-34/hr is associated with Tophat for a co-op position', 'weight': '10'}]
✅ Graph successfully inserted into Neo4j!

2025-10-05 02:15:42,863 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Entities: [{'name': 'TTC (Toronto Transit Commission)', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly pay rates'}, {'name': '27.65/hr', 'type': 'value', 'description': 'Hourly pay rate for the 6th co-op term at TTC'}, {'name': 'Trend Micro', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly pay rates and additional details'}, {'name': '32-34/hr', 'type': 'value', 'description': 'Hourly pay rate range for the 3rd co-op term at Trend Micro'}, {'name': '2024', 'type': 'value', 'description': 'Year associated with the co-op position at Trend Micro'}, {'name': 'SWE', 'type': 'flag', 'description': 'Software Engineering position associated with the co-op at Trend Micro'}, {'name': 'Trexo Robotics', 'type': 'ID', 'description': 'A company offering co-op positions with pay rates based on a percentage above the average'}, {'name': 'co-op average + 20%', 'type': 'value', 'description': 'Pay rate for co-op positions at Trexo Robotics, calculated as 20% above the average'}, {'name': 'Trustwave Holdings', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly pay rates'}, {'name': '25/hr', 'type': 'value', 'description': 'Hourly pay rate for the 3rd co-op term at Trustwave Holdings'}, {'name': 'Tulip Retail', 'type': 'ID', 'description': 'A company offering co-op positions with varying weekly pay rates based on the co-op term'}, {'name': '800/wk', 'type': 'value', 'description': 'Weekly pay rate for the 1st and 2nd co-op terms at Tulip Retail'}, {'name': '1000/wk', 'type': 'value', 'description': 'Weekly pay rate for the 3rd and 4th co-op terms at Tulip Retail'}, {'name': '1200/wk', 'type': 'value', 'description': 'Weekly pay rate for the 5th and 6th co-op terms at Tulip Retail'}, {'name': 'TutorOcean', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly pay rates'}, {'name': '20/hr', 'type': 'value', 'description': 'Hourly pay rate for co-op positions at TutorOcean'}, {'name': 'Tweepsmap', 'type': 'ID', 'description': 'A company offering co-op positions with pay rates based on the average'}, {'name': 'coop average', 'type': 'value', 'description': 'Pay rate for co-op positions at Tweepsmap, based on the average'}, {'name': 'Twitter', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly pay rates and additional stipends'}, {'name': '40/hr', 'type': 'value', 'description': 'Hourly pay rate for co-op positions at Twitter'}, {'name': '1000/mo WFH stipend', 'type': 'value', 'description': 'Monthly work-from-home stipend for co-op positions at Twitter'}, {'name': '41.25/hr', 'type': 'value', 'description': 'Hourly pay rate for co-op positions at Twitter with an additional stipend'}, {'name': '3000/mo stipend', 'type': 'value', 'description': 'Monthly stipend for co-op positions at Twitter'}, {'name': 'Uber', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly pay rates and additional housing stipend'}, {'name': '44/hr', 'type': 'value', 'description': 'Hourly pay rate for co-op positions at Uber'}, {'name': '1500/mo housing stipend', 'type': 'value', 'description': 'Monthly housing stipend for co-op positions at Uber'}, {'name': 'UHN (DATA Team)', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly pay rates'}, {'name': '20.00/hr', 'type': 'value', 'description': 'Hourly pay rate for co-op positions at UHN (DATA Team'}, {'name': '2023', 'type': 'value', 'description': 'Year associated with the co-op position at UHN (DATA Team'}, {'name': 'Ultimate Software', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly pay rates'}, {'name': '30-32/hr', 'type': 'value', 'description': 'Hourly pay rate range for co-op positions at Ultimate Software'}, {'name': '33/hr', 'type': 'value', 'description': 'Hourly pay rate for the 3rd co-op term at Ultimate Software'}, {'name': 'Union Bank of Switzerland (UBS Group AG)', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly pay rates'}, {'name': '24/hr', 'type': 'value', 'description': 'Hourly pay rate for the 2nd co-op term at Union Bank of Switzerland (UBS Group AG'}, {'name': 'Untether AI', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly pay rates'}, {'name': '21-24/hr', 'type': 'value', 'description': 'Hourly pay rate range for co-op positions at Untether AI'}, {'name': 'Uplift', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly pay rates'}, {'name': '38/hr', 'type': 'value', 'description': 'Hourly pay rate for co-op positions at Uplift'}, {'name': 'Veeva Systems', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly pay rates'}, {'name': '35/hr', 'type': 'value', 'description': 'Hourly pay rate for co-op positions at Veeva Systems'}, {'name': 'Vendia', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly pay rates in USD'}, {'name': '55/hr USD', 'type': 'value', 'description': 'Hourly pay rate in USD for co-op positions at Vendia'}, {'name': 'Veriday', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly pay rates'}, {'name': '20/hr', 'type': 'value', 'description': 'Hourly pay rate for the 1st co-op term at Veriday'}, {'name': 'Versa Networks', 'type': 'ID', 'description': 'A company offering co-op positions with specified hourly pay rates'}, {'name': '55/hr', 'type': 'value', 'description': 'Hourly pay rate for the 4th and 5th co-op terms at Versa Networks'}, {'name': '2023', 'type': 'value', 'description': 'Year associated with the co-op position at Versa Networks'}]
Relationships: [{'source': 'TTC (Toronto Transit Commission)', 'target': '27.65/hr', 'description': '27.65/hr is the hourly pay rate for the 6th co-op term at TTC', 'weight': '10'}, {'source': 'Trend Micro', 'target': '32-34/hr', 'description': '32-34/hr is the hourly pay rate range for the 3rd co-op term at Trend Micro', 'weight': '10'}, {'source': 'Trend Micro', 'target': '2024', 'description': '2024 is the year associated with the co-op position at Trend Micro', 'weight': '10'}, {'source': 'Trend Micro', 'target': 'SWE', 'description': 'SWE is the Software Engineering position associated with the co-op at Trend Micro', 'weight': '10'}, {'source': 'Trexo Robotics', 'target': 'co-op average + 20%', 'description': 'co-op average + 20% is the pay rate for co-op positions at Trexo Robotics', 'weight': '10'}, {'source': 'Trustwave Holdings', 'target': '25/hr', 'description': '25/hr is the hourly pay rate for the 3rd co-op term at Trustwave Holdings', 'weight': '10'}, {'source': 'Tulip Retail', 'target': '800/wk', 'description': '800/wk is the weekly pay rate for the 1st and 2nd co-op terms at Tulip Retail', 'weight': '10'}, {'source': 'Tulip Retail', 'target': '1000/wk', 'description': '1000/wk is the weekly pay rate for the 3rd and 4th co-op terms at Tulip Retail', 'weight': '10'}, {'source': 'Tulip Retail', 'target': '1200/wk', 'description': '1200/wk is the weekly pay rate for the 5th and 6th co-op terms at Tulip Retail', 'weight': '10'}, {'source': 'TutorOcean', 'target': '20/hr', 'description': '20/hr is the hourly pay rate for co-op positions at TutorOcean', 'weight': '10'}, {'source': 'Tweepsmap', 'target': 'coop average', 'description': 'coop average is the pay rate for co-op positions at Tweepsmap', 'weight': '10'}, {'source': 'Twitter', 'target': '40/hr', 'description': '40/hr is the hourly pay rate for co-op positions at Twitter', 'weight': '10'}, {'source': 'Twitter', 'target': '1000/mo WFH stipend', 'description': '1000/mo WFH stipend is the monthly work-from-home stipend for co-op positions at Twitter', 'weight': '10'}, {'source': 'Twitter', 'target': '41.25/hr', 'description': '41.25/hr is the hourly pay rate for co-op positions at Twitter with an additional stipend', 'weight': '10'}, {'source': 'Twitter', 'target': '3000/mo stipend', 'description': '3000/mo stipend is the monthly stipend for co-op positions at Twitter', 'weight': '10'}, {'source': 'Uber', 'target': '44/hr', 'description': '44/hr is the hourly pay rate for co-op positions at Uber', 'weight': '10'}, {'source': 'Uber', 'target': '1500/mo housing stipend', 'description': '1500/mo housing stipend is the monthly housing stipend for co-op positions at Uber', 'weight': '10'}, {'source': 'UHN (DATA Team)', 'target': '20.00/hr', 'description': '20.00/hr is the hourly pay rate for co-op positions at UHN (DATA Team', 'weight': None}, {'source': 'UHN (DATA Team)', 'target': '2023', 'description': '2023 is the year associated with the co-op position at UHN (DATA Team', 'weight': None}, {'source': 'Ultimate Software', 'target': '30-32/hr', 'description': '30-32/hr is the hourly pay rate range for co-op positions at Ultimate Software', 'weight': '10'}, {'source': 'Ultimate Software', 'target': '33/hr', 'description': '33/hr is the hourly pay rate for the 3rd co-op term at Ultimate Software', 'weight': '10'}, {'source': 'Union Bank of Switzerland (UBS Group AG)', 'target': '24/hr', 'description': '24/hr is the hourly pay rate for the 2nd co-op term at Union Bank of Switzerland (UBS Group AG', 'weight': None}, {'source': 'Untether AI', 'target': '21-24/hr', 'description': '21-24/hr is the hourly pay rate range for co-op positions at Untether AI', 'weight': '10'}, {'source': 'Uplift', 'target': '38/hr', 'description': '38/hr is the hourly pay rate for co-op positions at Uplift', 'weight': '10'}, {'source': 'Veeva Systems', 'target': '35/hr', 'description': '35/hr is the hourly pay rate for co-op positions at Veeva Systems', 'weight': '10'}, {'source': 'Vendia', 'target': '55/hr USD', 'description': '55/hr USD is the hourly pay rate for co-op positions at Vendia', 'weight': '10'}, {'source': 'Veriday', 'target': '20/hr', 'description': '20/hr is the hourly pay rate for the 1st co-op term at Veriday', 'weight': '10'}, {'source': 'Versa Networks', 'target': '55/hr', 'description': '55/hr is the hourly pay rate for the 4th and 5th co-op terms at Versa Networks', 'weight': '10'}, {'source': 'Versa Networks', 'target': '2023', 'description': '2023 is the year associated with the co-op position at Versa Networks', 'weight': '10'}]
✅ Graph successfully inserted into Neo4j!

2025-10-05 02:16:00,784 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Entities: [{'name': 'Versett', 'type': 'ID', 'description': 'A company offering co-op positions with specific hourly compensation rates'}, {'name': '32-25/hr', 'type': 'value', 'description': 'Hourly compensation rate for Versett during the 2nd co-op'}, {'name': 'VerticalScope', 'type': 'ID', 'description': 'A company offering co-op positions with specific hourly compensation rates'}, {'name': '30/hr', 'type': 'value', 'description': 'Hourly compensation rate for VerticalScope during the 4th co-op'}, {'name': 'Voiceflow', 'type': 'ID', 'description': 'A company offering co-op positions with variable hourly compensation rates based on term and team'}, {'name': '40-55/hr', 'type': 'value', 'description': 'Hourly compensation rate range for Voiceflow based on term and team'}, {'name': 'Voiceform', 'type': 'ID', 'description': 'A company offering co-op positions with variable hourly compensation rates depending on experience'}, {'name': '20-50/hr', 'type': 'value', 'description': 'Hourly compensation rate range for Voiceform depending on experience'}, {'name': 'Waabi Innovation', 'type': 'ID', 'description': 'A company offering co-op positions with specific hourly compensation rates and stipends'}, {'name': '52/hr', 'type': 'value', 'description': 'Hourly compensation rate for Waabi Innovation during the 3rd year'}, {'name': '500/wk stipend', 'type': 'value', 'description': 'Weekly stipend for Waabi Innovation during the 3rd year'}, {'name': 'Wattpad', 'type': 'ID', 'description': 'A company offering co-op positions with specific monthly and hourly compensation rates'}, {'name': '4500/month', 'type': 'value', 'description': 'Monthly compensation rate for Wattpad during the 2nd co-op'}, {'name': '35/hr', 'type': 'value', 'description': 'Hourly compensation rate for Wattpad during the 4th co-op'}, {'name': 'Wayfair', 'type': 'ID', 'description': 'A company offering co-op positions with specific hourly compensation rates and benefits'}, {'name': '48/hr USD', 'type': 'value', 'description': 'Hourly compensation rate in USD for Wayfair during the 3rd co-op'}, {'name': 'Housing stipend', 'type': 'value', 'description': 'Benefit offered by Wayfair during the co-op'}, {'name': 'Wealthsimple', 'type': 'ID', 'description': 'A company offering co-op positions with specific monthly compensation rates'}, {'name': '7450/mo', 'type': 'value', 'description': 'Monthly compensation rate for Wealthsimple during the 4th co-op'}, {'name': 'Wind River', 'type': 'ID', 'description': 'A company offering co-op positions with specific hourly compensation rates'}, {'name': '24-29/hr', 'type': 'value', 'description': 'Hourly compensation rate range for Wind River, including 24/hr for the 2nd co-op'}, {'name': 'Wish', 'type': 'ID', 'description': 'A company offering co-op positions with variable hourly and monthly compensation rates'}, {'name': '40-60/hr', 'type': 'value', 'description': 'Hourly compensation rate range for Wish'}, {'name': '9100/mo', 'type': 'value', 'description': 'Monthly compensation rate for Wish during the 5th co-op'}, {'name': 'WSIB Innovation Lab', 'type': 'ID', 'description': 'A company offering co-op positions with specific hourly compensation rates'}, {'name': '29.5/hr', 'type': 'value', 'description': 'Hourly compensation rate for WSIB Innovation Lab during the 1st co-op'}, {'name': 'Xanadu', 'type': 'ID', 'description': 'A company offering co-op positions with specific hourly compensation rates'}, {'name': '30/hr', 'type': 'value', 'description': 'Hourly compensation rate for Xanadu during the 1st co-op'}, {'name': 'Yext', 'type': 'ID', 'description': 'A company offering co-op positions with specific hourly compensation rates and stipends'}, {'name': '50 USD/hr', 'type': 'value', 'description': 'Hourly compensation rate in USD for Yext'}, {'name': '5k USD stipend', 'type': 'value', 'description': 'Stipend offered by Yext'}, {'name': 'Yugabyte', 'type': 'ID', 'description': 'A company offering co-op positions with specific monthly compensation rates for remote and on-site positions'}, {'name': '10,000/mo', 'type': 'value', 'description': 'Monthly compensation rate for remote positions at Yugabyte'}, {'name': '8k USD/mo', 'type': 'value', 'description': 'Monthly compensation rate for on-site positions at Yugabyte'}, {'name': 'Zenreach/Greenfield', 'type': 'ID', 'description': 'A company offering co-op positions with specific hourly compensation rates'}, {'name': '29/hr', 'type': 'value', 'description': 'Hourly compensation rate for Zenreach/Greenfield during the 3rd co-op'}, {'name': 'Zighra', 'type': 'ID', 'description': 'A company offering co-op positions with variable hourly compensation rates'}, {'name': '40+/hr', 'type': 'value', 'description': 'Hourly compensation rate for Zighra'}]
Relationships: [{'source': 'Versett', 'target': '32-25/hr', 'description': 'The hourly compensation rate of 32-25/hr is associated with Versett for the 2nd co-op', 'weight': '10'}, {'source': 'VerticalScope', 'target': '30/hr', 'description': 'The hourly compensation rate of 30/hr is associated with VerticalScope for the 4th co-op', 'weight': '10'}, {'source': 'Voiceflow', 'target': '40-55/hr', 'description': 'The hourly compensation rate range of 40-55/hr is associated with Voiceflow based on term and team', 'weight': '10'}, {'source': 'Voiceform', 'target': '20-50/hr', 'description': 'The hourly compensation rate range of 20-50/hr is associated with Voiceform depending on experience', 'weight': '10'}, {'source': 'Waabi Innovation', 'target': '52/hr', 'description': 'The hourly compensation rate of 52/hr is associated with Waabi Innovation for the 3rd year', 'weight': '10'}, {'source': 'Waabi Innovation', 'target': '500/wk stipend', 'description': 'The weekly stipend of 500/wk is associated with Waabi Innovation for the 3rd year', 'weight': '10'}, {'source': 'Wattpad', 'target': '4500/month', 'description': 'The monthly compensation rate of 4500/month is associated with Wattpad for the 2nd co-op', 'weight': '10'}, {'source': 'Wattpad', 'target': '35/hr', 'description': 'The hourly compensation rate of 35/hr is associated with Wattpad for the 4th co-op', 'weight': '10'}, {'source': 'Wayfair', 'target': '48/hr USD', 'description': 'The hourly compensation rate of 48/hr USD is associated with Wayfair for the 3rd co-op', 'weight': '10'}, {'source': 'Wayfair', 'target': 'Housing stipend', 'description': 'The housing stipend is a benefit associated with Wayfair during the co-op', 'weight': '10'}, {'source': 'Wealthsimple', 'target': '7450/mo', 'description': 'The monthly compensation rate of 7450/mo is associated with Wealthsimple for the 4th co-op', 'weight': '10'}, {'source': 'Wind River', 'target': '24-29/hr', 'description': 'The hourly compensation rate range of 24-29/hr is associated with Wind River, including 24/hr for the 2nd co-op', 'weight': '10'}, {'source': 'Wish', 'target': '40-60/hr', 'description': 'The hourly compensation rate range of 40-60/hr is associated with Wish', 'weight': '10'}, {'source': 'Wish', 'target': '9100/mo', 'description': 'The monthly compensation rate of 9100/mo is associated with Wish for the 5th co-op', 'weight': '10'}, {'source': 'WSIB Innovation Lab', 'target': '29.5/hr', 'description': 'The hourly compensation rate of 29.5/hr is associated with WSIB Innovation Lab for the 1st co-op', 'weight': '10'}, {'source': 'Xanadu', 'target': '30/hr', 'description': 'The hourly compensation rate of 30/hr is associated with Xanadu for the 1st co-op', 'weight': '10'}, {'source': 'Yext', 'target': '50 USD/hr', 'description': 'The hourly compensation rate of 50 USD/hr is associated with Yext', 'weight': '10'}, {'source': 'Yext', 'target': '5k USD stipend', 'description': 'The stipend of 5k USD is associated with Yext', 'weight': '10'}, {'source': 'Yugabyte', 'target': '10,000/mo', 'description': 'The monthly compensation rate of 10,000/mo is associated with Yugabyte for remote positions', 'weight': '10'}, {'source': 'Yugabyte', 'target': '8k USD/mo', 'description': 'The monthly compensation rate of 8k USD/mo is associated with Yugabyte for on-site positions', 'weight': '10'}, {'source': 'Zenreach/Greenfield', 'target': '29/hr', 'description': 'The hourly compensation rate of 29/hr is associated with Zenreach/Greenfield for the 3rd co-op', 'weight': '10'}, {'source': 'Zighra', 'target': '40+/hr', 'description': 'The hourly compensation rate of 40+/hr is associated with Zighra', 'weight': '10'}]
✅ Graph successfully inserted into Neo4j!

In [ ]:
from langchain_openai import ChatOpenAI
from langchain_community.graphs import Neo4jGraph
from langchain_community.chains.graph_qa.cypher import GraphCypherQAChain

# connect to Neo4j
graph = Neo4jGraph(
    url="neo4j://127.0.0.1:7687",
    username="neo4j",
    password="password"
)

llm = ChatOpenAI(model="gpt-4-turbo", temperature=0)

chain = GraphCypherQAChain.from_llm(
    llm,
    graph=graph,
    verbose=True,
    allow_dangerous_requests=True
)
from langchain.prompts import PromptTemplate
from langchain.chains import LLMChain

rephrase_prompt = PromptTemplate.from_template(
    "Convert the question into a concise graph search phrase:\nQuestion: {question}\nSearch phrase:"
)

rephraser = LLMChain(llm=llm, prompt=rephrase_prompt)

# --- Function with feedback loop ---
def query_graph_with_rephrase(user_input, max_attempts=3):
    attempt = 0
    while attempt < max_attempts:
        graph_query = rephraser.run({"question": user_input}).strip()
        print(f"\n Attempt {attempt+1}: Graph query → {graph_query}")
        
        response = chain.invoke({"query": graph_query})
        result = response.get("result", "").strip()

        if result and "don't know" not in result.lower():
            print("\n Found answer:")
            return result
        else:
            user_input = f"Try a different phrasing for: {graph_query}"
            attempt += 1
    
    return " No valid result after rephrasing attempts."

# --- Run ---
user_input = "what is Microsoft pay"
final_result = query_graph_with_rephrase(user_input)
print("\nFinal Result:", final_result)

2025-10-06 00:46:39,169 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 Attempt 1: Graph query → Microsoft pay overview


> Entering new GraphCypherQAChain chain...

2025-10-06 00:46:40,910 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Generated Cypher:
cypher
MATCH (e:Entity {name: "Microsoft"})-[:RELATED_TO]->(p:Entity {type: "pay overview"})
RETURN p.description

Full Context:
[]

2025-10-06 00:46:41,728 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

> Finished chain.

2025-10-06 00:46:42,752 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 Attempt 2: Graph query → "Microsoft salary summary"


> Entering new GraphCypherQAChain chain...

2025-10-06 00:46:43,981 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Generated Cypher:
cypher
MATCH (e:Entity {name: "Microsoft"})-[:RELATED_TO]->(s:Entity {type: "salary summary"})
RETURN s.description

Full Context:
[]

2025-10-06 00:46:45,456 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

> Finished chain.

2025-10-06 00:46:46,395 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

 Attempt 3: Graph query → "Microsoft salary overview"


> Entering new GraphCypherQAChain chain...

2025-10-06 00:46:47,922 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Generated Cypher:
MATCH (e1:Entity {name: "Microsoft"})-[:RELATED_TO]->(e2:Entity {type: "salary overview"}) RETURN e2.name, e2.description
Full Context:
[]

2025-10-06 00:46:48,692 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

> Finished chain.

Final Result:  No valid result after rephrasing attempts.

We see the extraction of **entities**:

`("entity"{tuple_delimiter}EVALUATION METRICS{tuple_delimiter}evaluation metrics{tuple_delimiter}Evaluation metrics are criteria  used to assess the performance of AI models, including metrics like cross-entropy, perplexity, factuality, and context relevance)`

As well as **relationships**:

`("relationship"{tuple_delimiter}EVALUATION METRICS{tuple_delimiter}CONTEXT RELEVANCE{tuple_delimiter}Context relevance is an evaluation metric that ensures the model uses the most pertinent information for generating responses{tuple_delimiter}8)`

Following this, these per chunk subgraphs are merged together - any entities with the same name and type are merged by creating an array of their descriptions. Similarly, any relationships with the same source and target are merged by creating an array of their descriptions. These lists are then summarized one more time

### **Looking at Final Entities and Relationships**

In [77]:
import pandas as pd

entities = pd.read_parquet('./ragtest/output/create_final_entities.parquet')

entities.head()

,id,human_readable_id,title,type,description,text_unit_ids
0,e3a7f24b-88b6-4481-b3a7-c35075a9671f,0,GPT-3,ORGANIZATION,GPT-3 is a large language model developed by O...,[ca73c495111f5cadd87e6a7a01aed66647ae6623fdf41...
1,f55cae4e-dd0d-47a2-912b-f7680147dd31,1,GPT-4,ORGANIZATION,GPT-4 is an advanced large language model deve...,[ca73c495111f5cadd87e6a7a01aed66647ae6623fdf41...
2,f3e3e46b-6746-45a7-9a26-1432f14c45e4,2,BERT,ORGANIZATION,"BERT, which stands for Bidirectional Encoder R...",[ca73c495111f5cadd87e6a7a01aed66647ae6623fdf41...
3,0491a417-2e18-41c4-ae1e-3e39bf2eb98f,3,PALM,ORGANIZATION,PaLM is a large language model developed by Go...,[ca73c495111f5cadd87e6a7a01aed66647ae6623fdf41...
4,2b7f14f5-d1d5-49f6-bace-46fd1767f99e,4,LLAMA,ORGANIZATION,LLAMA is a versatile and advanced model known ...,[ca73c495111f5cadd87e6a7a01aed66647ae6623fdf41...

In [78]:
relationships = pd.read_parquet('./ragtest/output/create_final_relationships.parquet')

relationships.head()

,id,human_readable_id,source,target,description,weight,combined_degree,text_unit_ids
0,b895553a-f860-4d15-bba2-a42f1464e810,0,GPT-3,GPT-4,"GPT-4 is an advanced version of GPT-3, buildin...",8.0,20,[ca73c495111f5cadd87e6a7a01aed66647ae6623fdf41...
1,1548feb2-5a6a-43e6-ab44-81252056193e,1,GPT-3,CHATGPT,"ChatGPT is based on the GPT architecture, spec...",7.0,14,[ca73c495111f5cadd87e6a7a01aed66647ae6623fdf41...
2,e538721d-c023-4994-b918-1efece80ea7e,2,GPT-3,BERT,Both BERT and GPT-3 are pre-trained language m...,6.0,18,[ca73c495111f5cadd87e6a7a01aed66647ae6623fdf41...
3,063a2941-df53-4b5c-a66a-45e60bdba604,3,GPT-3,REINFORCEMENT LEARNING FROM HUMAN FEEDBACK (RLHF),RLHF is used in training GPT-3 to refine its o...,7.0,13,[ca73c495111f5cadd87e6a7a01aed66647ae6623fdf41...
4,7e0cd0b4-4688-434f-a194-f2b9ce397a94,4,GPT-3,PROMPT ENGINEERING,Prompt engineering is a technique used to guid...,6.0,14,[ca73c495111f5cadd87e6a7a01aed66647ae6623fdf41...

### **Community Detection & Node Embedding**

<img src="./media/leidan.png" width=600>

After we have our basic graph with entities and relationships, we analyze its structure in two ways. Community Detection uses the [Leiden algorithm](https://en.wikipedia.org/wiki/Leiden_algorithm) to find explicit groupings in the graph, creating a hierarchy of related entities. The lower in the hierarchy, the more granular the community. Node Embedding uses [Node2Vec](https://arxiv.org/abs/1607.00653) to create vector representations of each entity, capturing implicit relationships in the graph structure. These complementary approaches let us understand both obvious connections through communities and subtle patterns through embeddings.

Combining all of this with our relationships gives us our final nodes.

In [80]:
nodes = pd.read_parquet('./ragtest/output/create_final_nodes.parquet')

nodes.head(10)

,id,human_readable_id,title,community,level,degree,x,y
0,e3a7f24b-88b6-4481-b3a7-c35075a9671f,0,GPT-3,8,0,12,-4.875545,4.017587
1,e3a7f24b-88b6-4481-b3a7-c35075a9671f,0,GPT-3,43,1,12,-4.875545,4.017587
2,f55cae4e-dd0d-47a2-912b-f7680147dd31,1,GPT-4,8,0,8,-4.561064,1.505724
3,f55cae4e-dd0d-47a2-912b-f7680147dd31,1,GPT-4,46,1,8,-4.561064,1.505724
4,f3e3e46b-6746-45a7-9a26-1432f14c45e4,2,BERT,8,0,6,-5.710580,3.546957
5,f3e3e46b-6746-45a7-9a26-1432f14c45e4,2,BERT,44,1,6,-5.710580,3.546957
6,0491a417-2e18-41c4-ae1e-3e39bf2eb98f,3,PALM,8,0,3,-5.309392,1.548029
7,0491a417-2e18-41c4-ae1e-3e39bf2eb98f,3,PALM,46,1,3,-5.309392,1.548029
8,2b7f14f5-d1d5-49f6-bace-46fd1767f99e,4,LLAMA,3,0,4,-6.644573,0.421999
9,2b7f14f5-d1d5-49f6-bace-46fd1767f99e,4,LLAMA,27,1,4,-6.644573,0.421999

At this step the graph is effectively created, however we can introduce a few extra steps that will allow us to do some advanced retrieval.

### Community Report Generation & Summarization

Now that we have clear community grouping, we can aggregate the main concepts across hierarchical node communities with another generation step, and a shorthand summary of that summary. Similar to the nodes, these summaries are also ran through an embedding model and stored in a vector store.

In [81]:
community_reports = pd.read_parquet('./ragtest/output/create_final_community_reports.parquet')

community_reports.head()

,id,human_readable_id,community,parent,level,title,summary,full_content,rank,rank_explanation,findings,full_content_json,period,size
0,a85d59a64a054114982b1ce6e1ced591,61,61,32,2,Amazon Bedrock and AI Model Providers,The community is centered around Amazon Bedroc...,# Amazon Bedrock and AI Model Providers\n\nThe...,8.5,The impact severity rating is high due to Amaz...,[{'explanation': 'Amazon Bedrock is a pivotal ...,"{\n ""title"": ""Amazon Bedrock and AI Model P...",2024-12-18,9
1,6aafc6eeddd848bc8ffbfb9177790c26,62,62,32,2,AWS and SageMaker JumpStart,The community is centered around Amazon Web Se...,# AWS and SageMaker JumpStart\n\nThe community...,8.5,The impact severity rating is high due to AWS'...,[{'explanation': 'Amazon Web Services (AWS) is...,"{\n ""title"": ""AWS and SageMaker JumpStart"",...",2024-12-18,2
2,e13e3ed0a0b74fd090319957ae9f3e1e,14,14,0,1,PPO for LLM Alignment and Reinforcement Learni...,The community centers around the study 'PPO fo...,# PPO for LLM Alignment and Reinforcement Lear...,7.5,The impact severity rating is high due to the ...,[{'explanation': 'The study 'PPO for LLM Align...,"{\n ""title"": ""PPO for LLM Alignment and Rei...",2024-12-18,7
3,828baab1461b439ea71203ad8fd0aae5,15,15,0,1,HuggingFace and Advanced NLP Tools,"The community is centered around HuggingFace, ...",# HuggingFace and Advanced NLP Tools\n\nThe co...,8.5,The impact severity rating is high due to Hugg...,[{'explanation': 'HuggingFace is a prominent e...,"{\n ""title"": ""HuggingFace and Advanced NLP ...",2024-12-18,7
4,791da6e7031e45228442b277e7d912c6,16,16,0,1,OpenAI and AI Development Platforms,"The community is centered around OpenAI, a lea...",# OpenAI and AI Development Platforms\n\nThe c...,8.5,The impact severity rating is high due to the ...,[{'explanation': 'OpenAI is a central entity i...,"{\n ""title"": ""OpenAI and AI Development Pla...",2024-12-18,7

In [83]:
print(community_reports["full_content"][0])

# Amazon Bedrock and AI Model Providers

The community is centered around Amazon Bedrock, a service by AWS that facilitates access to foundation models from various AI innovators. Key entities include AI21 Labs, Anthropic, Cohere, Mistral AI, and Stability AI, all of which provide models accessible through Amazon Bedrock. The service integrates with AWS infrastructure, including AWS Lambda and AWS SageMaker, to support scalable AI model deployment.

## Amazon Bedrock as a central service

Amazon Bedrock is a pivotal service within the AWS ecosystem, designed to simplify access to high-performing foundation models for generative AI applications. It integrates seamlessly with other AWS services, such as Amazon S3, AWS Lambda, and AWS SageMaker, to facilitate the fine-tuning and deployment of AI models. This integration underscores its importance in the AI landscape, providing a comprehensive suite of tools for scalable AI model deployment [Data: Entities (206); Relationships (281, 326, 327)].

## AI21 Labs' contribution to Amazon Bedrock

AI21 Labs is one of the key providers of foundation models available through Amazon Bedrock. The company's advanced AI models contribute significantly to the capabilities offered by Amazon Bedrock, enhancing its utility for natural language processing tasks. This partnership highlights the collaborative nature of the AI community in advancing technology through shared resources and expertise [Data: Entities (267); Relationships (318)].

## Anthropic's role in AI safety and research

Anthropic is an AI safety and research company that provides foundation models accessible through Amazon Bedrock. Its focus on AI safety is crucial in the development of responsible AI technologies, ensuring that the models deployed via Amazon Bedrock adhere to ethical standards. This relationship emphasizes the importance of integrating safety considerations into AI development [Data: Entities (268); Relationships (319)].

## Cohere's NLP models in Amazon Bedrock

Cohere offers natural language processing models that are part of the foundation models available through Amazon Bedrock. These models enhance the service's capabilities in processing and understanding human language, making it a valuable tool for businesses and developers seeking to implement NLP solutions. Cohere's involvement underscores the diversity of AI models supported by Amazon Bedrock [Data: Entities (269); Relationships (320)].

## Integration with AWS Lambda and AWS SageMaker

Amazon Bedrock's integration with AWS Lambda and AWS SageMaker is a key feature that supports the deployment and management of AI models. AWS Lambda provides serverless computing capabilities, allowing for efficient resource management, while AWS SageMaker offers tools for building, training, and deploying machine learning models. This integration facilitates a seamless workflow for AI model development and deployment, enhancing the overall efficiency and scalability of AI applications [Data: Entities (276, 277); Relationships (326, 327)].

In [82]:
print(community_reports["summary"][0])

The community is centered around Amazon Bedrock, a service by AWS that facilitates access to foundation models from various AI innovators. Key entities include AI21 Labs, Anthropic, Cohere, Mistral AI, and Stability AI, all of which provide models accessible through Amazon Bedrock. The service integrates with AWS infrastructure, including AWS Lambda and AWS SageMaker, to support scalable AI model deployment.

### The Final Graph!

<img src="./media/ghraphrag_viz.svg" width=800>

*[Full Size PDF](./ghraphrag_viz.pdf)*

---

## GraphRAG Retrieval

<img src="./media/kg_retrieval.png" width=600>

*[Unifying Large Language Models and Knowledge Graphs: A Roadmap](https://arxiv.org/pdf/2306.08302)*

With our knowledge graph constructed, and hierarchichal communities delineated, we can now perform multiple types of search that can both take advantage of the graph structure, and multiple levels of specificity across our communities. Specifically:

1. **Global Search**: Uses the LLM Generated community reports from a specified level of the graph's community hierarchy as context data to generate response.
2. **Local Search**: Combines structured data from the knowledge graph with unstructured data from the input document(s) to augment the LLM context with relevant entity information.
3. **Drift Search**: Dynamic Reasoning and Inference with Flexible Traversal, an approach to local search queries by including community information in the search process, thus combining global and local search.

**GraphRAG Retrieval Function**

*Note: Wrapping the [GraphRAG CLI tool](https://microsoft.github.io/graphrag/cli/) as a function here instead of using their [library](https://microsoft.github.io/graphrag/examples_notebooks/api_overview/) for an easier example. As such, notebook needs to be running in the same GraphRAG environment/kernal.*

In [84]:
import subprocess
import shlex
from typing import Optional

def query_graphrag(
    query: str,
    method: str = "global",
    root_path: str = "./ragtest",
    timeout: Optional[int] = None,
    community_level: int = 2,
    dynamic_community_selection: bool = False
) -> str:
    """
    Execute a GraphRAG query using the CLI tool.
    
    Args:
        query (str): The query string to process
        method (str): Query method (e.g., "global", "local", or "drift")
        root_path (str): Path to the root directory
        timeout (int, optional): Timeout in seconds for the command
        community_level (int): The community level in the Leiden community hierarchy (default: 2)
        dynamic_community_selection (bool): Whether to use global search with dynamic community selection (default: False)
    
    Returns:
        str: The output from GraphRAG
        
    Raises:
        subprocess.CalledProcessError: If the command fails
        subprocess.TimeoutExpired: If the command times out
        ValueError: If community_level is negative
    """
    # Validate community level
    if community_level < 0:
        raise ValueError("Community level must be non-negative")
    
    # Construct the base command
    command = [
        'graphrag', 'query',
        '--root', root_path,
        '--method', method,
        '--query', query,
        '--community-level', str(community_level)
    ]
    
    # Add dynamic community selection flag if enabled
    if dynamic_community_selection:
        command.append('--dynamic-community-selection')
    
    try:
        # Execute the command and capture output
        result = subprocess.run(
            command,
            capture_output=True,
            text=True,
            timeout=timeout
        )
        
        # Check if the command was successful
        result.check_returncode()
        
        return result.stdout.strip()
        
    except subprocess.CalledProcessError as e:
        error_message = f"Command failed with exit code {e.returncode}\nError: {e.stderr}"
        raise subprocess.CalledProcessError(
            e.returncode,
            e.cmd,
            output=e.output,
            stderr=error_message
        )

### Local Search

<img src="./media/local_search.png" width=900>

The GraphRAG approach to local search is the most similar to regular semantic RAG search. It combines structured data from the knowledge graph with unstructured data from the input documents to augment the LLM context with relevant entity information. In essence, we are going to first search for relevant entities to the query using semantic search. These become the entry points on our graph that we can now traverse. Starting at these points, we look at connected chunks of text, community reports, other entities, and relationships between them. All of the data retrieved is filtered and ranked to fit into a pre-defined context window.

In [88]:
result = query_graphrag(
    query="How does a company choose between RAG, fine-tuning, and different PEFT approaches?",
    method="local"
)
print("Query result:")
print(result)

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Query result:
INFO: Vector Store Args: {
    "type": "lancedb",
    "db_uri": "/Users/adamlucek/Desktop/github/GraphRAG/ragtest/output/lancedb",
    "container_name": "==== REDACTED ====",
    "overwrite": true
}
creating llm client with {'api_key': 'REDACTED,len=51', 'type': "openai_chat", 'encoding_model': 'cl100k_base', 'model': 'gpt-4o', 'max_tokens': 4000, 'temperature': 0.0, 'top_p': 1.0, 'n': 1, 'frequency_penalty': 0.0, 'presence_penalty': 0.0, 'request_timeout': 180.0, 'api_base': None, 'api_version': None, 'organization': None, 'proxy': None, 'audience': None, 'deployment_name': None, 'model_supports_json': True, 'tokens_per_minute': 0, 'requests_per_minute': 0, 'max_retries': 10, 'max_retry_wait': 10.0, 'sleep_on_rate_limit_recommendation': True, 'concurrent_requests': 25, 'responses': None}
creating embedding llm client with {'api_key': 'REDACTED,len=51', 'type': "openai_embedding", 'encoding_model': 'cl100k_base', 'model': 'text-embedding-3-small', 'max_tokens': 4000, 'temperature': 0, 'top_p': 1, 'n': 1, 'frequency_penalty': 0.0, 'presence_penalty': 0.0, 'request_timeout': 180.0, 'api_base': None, 'api_version': None, 'organization': None, 'proxy': None, 'audience': None, 'deployment_name': None, 'model_supports_json': None, 'tokens_per_minute': 0, 'requests_per_minute': 0, 'max_retries': 10, 'max_retry_wait': 10.0, 'sleep_on_rate_limit_recommendation': True, 'concurrent_requests': 25, 'responses': None}

SUCCESS: Local Search Response:
When a company is deciding between Retrieval-Augmented Generation (RAG), fine-tuning, and various Parameter-Efficient Fine-Tuning (PEFT) approaches, several factors must be considered, including the specific application requirements, available resources, and desired outcomes. Each method offers distinct advantages and is suited to different scenarios.

### Retrieval-Augmented Generation (RAG)

RAG is particularly beneficial for applications that require integrating external data to enhance the accuracy and relevance of generated content. It is ideal for scenarios where the model needs to access up-to-date or domain-specific information without extensive retraining. For instance, RAG is effectively used in question-and-answer systems, customer support automation, and summarization tasks, where the ability to retrieve and incorporate external data can significantly improve performance [Data: Reports (20); Entities (20); Relationships (14, 21, 22, 23)]. Companies might choose RAG when they need to maintain high precision and adaptability in dynamic environments, such as customer service or technical support, where the context and information are constantly evolving.

### Fine-Tuning

Fine-tuning involves adapting a pre-trained model to perform better on specific tasks by updating its parameters with domain-specific data. This approach is essential when a company needs to tailor a model to a particular application or domain, ensuring that it can handle specific tasks with high accuracy. Fine-tuning is a comprehensive process that includes stages such as dataset preparation, model initialization, and evaluation, making it suitable for applications where precise model adaptation is crucial [Data: Reports (19); Entities (17); Relationships (10, 12, 24, 27, 29, 274, 275, 276, 277); Sources (3, 12, 13)]. Companies might opt for fine-tuning when they have the resources to manage the computational demands and when the task requires a high degree of customization.

### Parameter-Efficient Fine-Tuning (PEFT)

PEFT methods, such as LoRA and QLoRA, offer a more resource-efficient alternative to traditional fine-tuning by updating only a small subset of model parameters. This approach is particularly advantageous in scenarios where computational resources are limited, as it reduces the memory and processing requirements while maintaining performance levels comparable to full fine-tuning [Data: Entities (25, 104, 110, 130); Relationships (24, 137, 140, 104); Sources (6, 15)]. PEFT is suitable for companies looking to optimize the financial and environmental costs associated with fine-tuning large language models, especially in low-data scenarios or when deploying models on less powerful hardware.

### Decision-Making Considerations

In choosing between these methods, companies should evaluate the specific needs of their application, the availability of computational resources, and the importance of model adaptability and precision. RAG is ideal for applications requiring real-time data integration, fine-tuning is best for highly customized tasks, and PEFT is suitable for resource-constrained environments. By aligning the choice of method with their strategic goals and operational constraints, companies can effectively enhance their AI capabilities and achieve desired outcomes.

### Global Search

<img src="./media/global_search.png" width=1000>

Through the semantic clustering of communities during the indexxing process outlined above we created community reports as summaries of high level themes across these groupings. Having this community summary data at various levels allows us to do something that traditional RAG performs poorly at, answering queries about broad themes and ideas across our unstructured data.

To capture as much broad information as possible in an efficient manner, GraphRAG implements a [map reduce](https://en.wikipedia.org/wiki/MapReduce) approach. Given a query, relevant community node reports at a specific hierarchical level are retrieved. These are shuffled and chunked, where each chunk is used to generate a list of points that each have their own "importance score". These intermediate points are ranked and filtered, attempting to maintain the most important points. These become the aggregate intermediary response, which is passed to the LLM as the context for the final response.

In [86]:
result = query_graphrag(
    query="How does a company choose between RAG, fine-tuning, and different PEFT approaches?",
    method="global"
)
print("Query result:")
print(result)

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Query result:
creating llm client with {'api_key': 'REDACTED,len=51', 'type': "openai_chat", 'encoding_model': 'cl100k_base', 'model': 'gpt-4o', 'max_tokens': 4000, 'temperature': 0.0, 'top_p': 1.0, 'n': 1, 'frequency_penalty': 0.0, 'presence_penalty': 0.0, 'request_timeout': 180.0, 'api_base': None, 'api_version': None, 'organization': None, 'proxy': None, 'audience': None, 'deployment_name': None, 'model_supports_json': True, 'tokens_per_minute': 0, 'requests_per_minute': 0, 'max_retries': 10, 'max_retry_wait': 10.0, 'sleep_on_rate_limit_recommendation': True, 'concurrent_requests': 25, 'responses': None}

SUCCESS: Global Search Response:
### Choosing Between RAG, Fine-Tuning, and PEFT Approaches

When a company is deciding between Retrieval-Augmented Generation (RAG), fine-tuning, and Parameter-Efficient Fine-Tuning (PEFT) approaches, several key factors must be considered. These factors include the specific requirements of the application, the need for external data integration, computational resource constraints, and the desired level of model adaptation and performance.

#### Application Requirements

The choice largely depends on the specific needs of the application. For instance, if the application requires high precision and adaptability, such as in customer support or information retrieval systems, RAG may be the preferred choice. RAG enhances large language models by integrating external data, allowing for more accurate and contextually relevant content generation without extensive fine-tuning [Data: Reports (19, 20, 35, 21, 36, 38, 60)].

#### Computational Resources

Computational resources are another critical consideration. Fine-tuning involves further training pre-trained models to improve their performance on specific tasks by updating the model's parameters using a smaller, domain-specific dataset. This process can be resource-intensive but is essential for adapting models to targeted applications and domains [Data: Reports (19, 45, 31, 60)].

In contrast, PEFT approaches, such as LoRA and QLoRA, are designed to enhance memory efficiency and reduce computational costs during the fine-tuning process. These techniques allow for fine-tuning on less powerful hardware while maintaining performance levels comparable to traditional methods. PEFT is particularly useful for fine-tuning multimodal models and deploying NLP models on mobile devices [Data: Reports (36, 38, 19, 35)].

#### Model Customization and Contextual Relevance

The desired level of model customization and contextual relevance also plays a significant role. Fine-tuning is crucial for enhancing the performance of large language models (LLMs) on specific tasks, addressing challenges such as scalability, memory requirements, and resource efficiency. It allows for the customization of models to meet specialized needs and ensures they perform optimally in their intended environments [Data: Reports (45, 31, 60)].

RAG systems, on the other hand, improve the accuracy and contextuality of the outputs produced by LLMs, making them suitable for applications where context is crucial [Data: Reports (20, 21, 53)].

### Conclusion

Ultimately, the decision between RAG, fine-tuning, and PEFT approaches should be guided by the specific needs and constraints of the company, such as the importance of context relevance, the need for task-specific optimization, and resource availability. By carefully evaluating these factors, companies can select the most appropriate method to achieve their desired outcomes [Data: Reports (19, 20, 35, 21, 36, 38, 60, 53, 45)].

### DRIFT Search

<img src="./media/drift_search.png" width=1000>

[Dynamic Reasoning and Inference with Flexible Traversal](https://www.microsoft.com/en-us/research/blog/introducing-drift-search-combining-global-and-local-search-methods-to-improve-quality-and-efficiency/), or DRIFT, is a novel GraphRAG concept introduced by Microsoft as an approach to local search queries that include community information in the search process.

The user's query is initially processed through [Hypothetical Document Embedding (HyDE)](https://arxiv.org/pdf/2212.10496), which creates a hypothetical document similar to those found in the graph already, but using the user's topic query. This document is embedded and used for semantic retrieval of the top-k relevant community reports. From these matches, we generate an initial answer along with several follow-up questions as a lightweight version of global search. They refer to this as the primer.

Once this primer phase is complete, we execute local searches for each follow-up question generated. Each local search produces both intermediate answers and new follow-up questions, creating a refinement loop. This loop runs for two iterations (noted future research planned to develop reward functions for smarter termination). An important note that makes these local searches unique is that they are informed by both community-level knowledge and detailed entity/relationship data. This allows the DRIFT process to find relevant information even when the initial query diverges from the indexing persona, and it can adapt its approach based on emerging information during the search.

The final output is structured as a hierarchy of questions and answers, ranked by their relevance to the original query. Map reduce is used again with an equal weighting on all intermediate answers, then passed to the language model for a final response. DRIFT cleverly combines global and local search with guided exploration to provide both broad context and specific details in responses.

In [89]:
result = query_graphrag(
    query="How does a company choose between RAG, fine-tuning, and different PEFT approaches?",
    method="drift"
)
print("Query result:")
print(result)

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Query result:
INFO: Vector Store Args: {
    "type": "lancedb",
    "db_uri": "/Users/adamlucek/Desktop/github/GraphRAG/ragtest/output/lancedb",
    "container_name": "==== REDACTED ====",
    "overwrite": true
}
creating llm client with {'api_key': 'REDACTED,len=51', 'type': "openai_chat", 'encoding_model': 'cl100k_base', 'model': 'gpt-4o', 'max_tokens': 4000, 'temperature': 0.0, 'top_p': 1.0, 'n': 1, 'frequency_penalty': 0.0, 'presence_penalty': 0.0, 'request_timeout': 180.0, 'api_base': None, 'api_version': None, 'organization': None, 'proxy': None, 'audience': None, 'deployment_name': None, 'model_supports_json': True, 'tokens_per_minute': 0, 'requests_per_minute': 0, 'max_retries': 10, 'max_retry_wait': 10.0, 'sleep_on_rate_limit_recommendation': True, 'concurrent_requests': 25, 'responses': None}
creating embedding llm client with {'api_key': 'REDACTED,len=51', 'type': "openai_embedding", 'encoding_model': 'cl100k_base', 'model': 'text-embedding-3-small', 'max_tokens': 4000, 'temperature': 0, 'top_p': 1, 'n': 1, 'frequency_penalty': 0.0, 'presence_penalty': 0.0, 'request_timeout': 180.0, 'api_base': None, 'api_version': None, 'organization': None, 'proxy': None, 'audience': None, 'deployment_name': None, 'model_supports_json': None, 'tokens_per_minute': 0, 'requests_per_minute': 0, 'max_retries': 10, 'max_retry_wait': 10.0, 'sleep_on_rate_limit_recommendation': True, 'concurrent_requests': 25, 'responses': None}

SUCCESS: DRIFT Search Response:
# Understanding the Choice Between RAG, Fine-Tuning, and PEFT Approaches

When a company is faced with the decision to choose between Retrieval-Augmented Generation (RAG), fine-tuning, and various Parameter-Efficient Fine-Tuning (PEFT) approaches, several factors must be taken into account, determined by the specific application requirements and resource availability.

## Retrieving Capabilities with RAG
RAG is particularly advantageous in scenarios where it is crucial to integrate external information into language models for enhanced accuracy and relevance. It is highly recommended for applications like question and answer systems, customer support, and summarization tasks, where real-time context retrieval from large datasets improves response precision without needing extensive and expensive model retraining. The strength of RAG lies in its ability to quickly adapt to various knowledge domains by leveraging existing data without modifying the underlying language model significantly.

## The Focus and Depth of Fine-Tuning
Traditional fine-tuning is the go-to choice when a clear, defined improvement in task performance is needed using domain-specific datasets. It involves re-calibrating a pre-trained model’s parameters to cater precisely to industry-specific or task-specific requirements. This approach can enhance performance metrics significantly but incurs high computational costs and demands substantial amounts of fine-tuning data, making it ideal for well-funded projects aiming for precise task optimization.

## Resource-Efficiency with PEFT Techniques
On the other end of the spectrum, PEFT approaches such as DORA and LoRA present themselves as highly resource-efficient alternatives to standard fine-tuning. They are suitable for companies with limited computational resources but still prioritize performance enhancements. By selectively adjusting additional smaller model parameters, PEFT methods allow substantial flexibility and significant model adaptability for various applications without the full overhead of conventional fine-tuning.

Ultimately, the decision for a company involves balancing resource availability (both in terms of data and computing power), desired performance efficiency, and the specific features of the task at hand. Companies with broad application needs across different domains might favor RAG's flexibility; domain-specific improvements would benefit more from deep fine-tuning, while constrained environments should consider PEFT methods for their adaptability and efficiency.

# Understanding the Choice Between RAG, Fine-Tuning, and PEFT Approaches

When choosing between Retrieval-Augmented Generation (RAG), fine-tuning, and Parameter-Efficient Fine-Tuning (PEFT) approaches, businesses must evaluate their specific needs in terms of model performance, resource constraints, and flexibility. Each approach involves distinct methods for optimally leveraging machine learning models and NLP systems.

**Retrieval-Augmented Generation (RAG):** RAG is a strategy combining retrieval and generative models to enhance the context provided to language models like GPT-3. This approach allows models to answer queries more accurately by accessing external knowledge bases. It is particularly beneficial when dealing with tasks requiring extensive context or up-to-date information. Companies would favor RAG when the model needs to maintain relevance in dynamic information environments or when the contextual accuracy is crucial.

**Fine-Tuning:** This traditional method involves adjusting the entire model's parameters to optimize performance on a specific task. Fine-tuning is often resource-intensive, requiring significant computational power and time, which can prove a bottleneck for large models or organizations with limited resources. It produces highly task-specific outcomes, making it an ideal choice when high accuracy is paramount and resources are abundant. Fine-tuning is suitable for specialized tasks where the nuances of data need careful embedding into the model.

**Parameter-Efficient Fine-Tuning (PEFT):** Techniques like QLoRA and LoRA are designed to address the resource constraints associated with fine-tuning. By adjusting only a subset of parameters, these methods provide a more efficient approach, maintaining model performance while requiring less computational power. Companies might choose PEFT when deploying large models on resource-constrained devices, like mobile platforms, or when exploring multiple tasks with shared resources. PEFT's importance is growing in real-world applications where cost and efficiency are central concerns.

In summary, choosing between these approaches depends on an organization’s priorities: RAG offers dynamic and contextual adaptability; fine-tuning promises high precision at the cost of resources; and PEFT balances resource demands with performance, making it suitable for scalable deployment. Organizations are encouraged to deeply understand their specific contextual and technical requirements to select the most appropriate approach.

## How Companies Choose Between RAG, Fine-Tuning, and PEFT Approaches

When deciding between Retrieval-Augmented Generation (RAG), fine-tuning, and Parameter-Efficient Fine-Tuning (PEFT) techniques, companies must consider a variety of factors related to their unique needs and resources. Each approach serves distinct purposes and offers specific advantages, making them suitable for different scenarios.

### Retrieval-Augmented Generation (RAG)
RAG is particularly beneficial when a company requires a model to access a vast external data set to create highly contextual and informed responses. This method is preferred when the task involves processing or retrieving large amounts of dynamic information. The power of RAG lies in its ability to provide more comprehensive answers by leveraging external data sources, enhancing the model's output quality. As such, organizations where information retrieval and integration are crucial components of the application, such as in customer support systems or knowledge-based industries, may find RAG an optimal choice.

### Fine-Tuning
Fine-tuning a large language model involves adjusting its parameters based on specific tasks or domain data to improve its performance on said tasks. This method is ideal for companies aiming to develop a bespoke solution tailored to precise needs or niche applications. Fine-tuning a model can significantly increase its utility in specialized fields such as legal research or medical analysis, where the accuracy and specificity of information are critical. Though resource-intensive, the specificity in outcome makes traditional fine-tuning valuable for businesses that require high degrees of customization.

### Parameter-Efficient Fine-Tuning (PEFT)
PEFT techniques, such as LoRA and adapter-based methods, offer a way to enhance large language models without the typical computational cost associated with traditional fine-tuning. This strategy updates only a small subset of a model's parameters, thus making it a cost-effective alternative for companies with limited resources or those that need to frequently update models with new data. PEFT is advantageous for businesses that need flexibility without a significant investment in computational power, popular among startups or organizations exploring new avenues without extensive AI infrastructure.

In summary, a company's choice between RAG, fine-tuning, and PEFT depends on their specific requirements, the nature and volume of data they interact with, and the computational resources at their disposal. By aligning their strategy with the strengths of each approach, businesses can optimize their use of AI technologies to meet their unique operational goals.

# Evaluating Company Choices Among RAG, Fine-Tuning, and PEFT Approaches

When a company considers enhancing its machine learning models, particularly large language models (LLMs), it encounters a range of techniques, including Retrieval-Augmented Generation (RAG), fine-tuning, and Parameter-Efficient Fine-Tuning (PEFT) methods like Half Fine-Tuning (HFT). Each of these techniques offers unique benefits and is suitable for different objectives and scenarios. Understanding the distinction and potential applications is crucial for making an informed decision.

RAG is highly effective in situations where models need to provide accurate responses based on external information not inherently within the model's parameters. By integrating information retrieval techniques, RAG allows models to access a database or document store to augment their generated text, making it ideal for applications where dynamic content access and up-to-date information are critical, such as live customer service or research queries.

In contrast, fine-tuning broadly involves adjusting an already pre-trained model to suit new, specific tasks or datasets. Traditional supervised fine-tuning is useful when the primary goal is to improve a model’s performance on specific tasks while leveraging existing knowledge. For example, in supervised fine-tuning, Half Fine-Tuning (HFT) offers an innovative balance by freezing a portion of the model's parameters, thus maintaining foundational knowledge while developing new competencies. This efficiency is especially important when handling models like the LLAMA 2-7B, where sustaining knowledge over several iterations is vital.

PEFT techniques, such as HFT, provide a focused approach to fine-tuning by optimizing resource usage and reducing computational demands. They ensure that changes to the model preserve core functionalities while adapting to new requirements, which is critically important in environments where computational resources and model interpretability are constrained.

The choice among RAG, fine-tuning, and PEFT approaches depends on factors such as the company's resource availability, existing model performance, specific use-cases, and the need for adaptability versus resource conservation. Companies prioritizing task-specific improvements with limited computational power might lean toward PEFT or HFT, whereas RAG would be preferable for scenarios needing comprehensive and current information access capabilities.

Ultimately, the decision must align with strategic objectives, model lifecycle considerations, and the specific complexities of the data and questions the model is expected to handle.

# Factors in Choosing Between RAG, Fine-Tuning, and PEFT Approaches

When a company is deciding between Retrieval-Augmented Generation (RAG), fine-tuning, and Parameter-Efficient Fine-Tuning (PEFT) methods for large language models (LLMs), several important factors must be considered. These methods each have unique advantages and challenges that make them suitable for different scenarios.

Retrieval-Augmented Generation (RAG) enhances the performance of LLMs by integrating retrieval mechanisms that bring relevant information into the context before generating results. This approach is particularly useful when the task requires the contextually relevant retrieval of information from extensive databases or when the generation task is highly dependent on external knowledge. RAG systems improve both the accuracy and the contextual relevance of LLM outputs, making them valuable for applications where precision in response to contextual queries is critical.

Fine-tuning involves adjusting the LLM using a carefully prepared dataset tailored to a specific task. This process includes essential stages such as dataset preparation, instruction tuning, and topic mapping. Fine-tuning is especially advantageous when the intention is to specialize a model for a specific application, ensuring nuanced comprehension and performance improvement for the target task. It provides more control over the model's behavior, as specific datasets align the model with intended outcomes, offering enhanced reliability.

Parameter-Efficient Fine-Tuning (PEFT) approaches are designed to fine-tune LLMs with fewer resource requirements compared to traditional fine-tuning. Methods like LoRA (Low-Rank Adaptation), Adapter modules, and prefix tuning are examples of PEFT techniques. They focus on adapting a small set of parameters while maintaining the majority of the LLM fixed, thus reducing computational costs and the necessary dataset size. PEFT is particularly beneficial for scenarios with constrained computational resources or when rapidly deploying updates or adaptations is necessary without retraining the entire model.

Ultimately, the choice between these approaches depends on the specific requirements and constraints of the task at hand, including the need for real-time retrieval capabilities (favoring RAG), the specificity and quality of output (favoring fine-tuning), or capacity and resource efficiency (favoring PEFT).

---

## Comparing to Regular Vector Database Retrieval

<img src="./media/basic_retrieval.png" width=600>
 
To give some comparison, let's look back at traditional chunking, embedding, and similarity retrieval RAG

**Instantiate our Database**

For this we'll be using [ChromaDB](https://www.trychroma.com) with the same chunks as were loaded into our graph.

In [ ]:
import chromadb

chroma_client = chromadb.PersistentClient(path="./notebook/chromadb")
paper_collection = chroma_client.get_or_create_collection(name="paper_collection")

**Embed Chunks Into Collection**

In [ ]:
i = 0
for text in texts:
    paper_collection.add(
        documents=[text],
        ids=f"chunk_{i}"
    )
    i += 1

**Retrieval Function**

In [ ]:
def chroma_retrieval(query, num_results=5):
    results = paper_collection.query(
        query_texts=[query],
        n_results=num_results
    )
    return results

**RAG Prompt & Chain**

In [90]:
rag_prompt_template = """
Generate a response of the target length and format that responds to the user's question, summarizing all information in the input data tables appropriate for the response length and format, and incorporating any relevant general knowledge.

If you don't know the answer, just say so. Do not make anything up.

Do not include information where the supporting evidence for it is not provided.

Context: {retrieved_docs}

User Question: {query}

"""

rag_prompt = ChatPromptTemplate.from_template(rag_prompt_template)

rag_chain = rag_prompt | llm | StrOutputParser()

**RAG Function**

In [91]:
def chroma_rag(query):
    retrieved_docs = chroma_retrieval(query)["documents"][0]
    response = rag_chain.invoke({"retrieved_docs": retrieved_docs, "query": query})
    return response

**RAG Response**

In [92]:
response = chroma_rag("How does a company choose between RAG, fine-tuning, and different PEFT approaches?")
print(response)

HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

When choosing between Retrieval-Augmented Generation (RAG), fine-tuning, and different Parameter-Efficient Fine-Tuning (PEFT) approaches, a company should consider several factors:

1. **Data Access and Updates**: RAG is preferable for applications requiring access to external data sources or environments where data frequently updates. It provides dynamic data retrieval capabilities and is less prone to generating incorrect information.

2. **Model Behavior and Domain-Specific Knowledge**: Fine-tuning is suitable when the model needs to adjust its behavior, writing style, or incorporate domain-specific knowledge. It is effective if there is ample domain-specific, labeled training data available.

3. **Resource Constraints and Efficiency**: PEFT approaches like LoRA and DEFT are designed to reduce computational and resource requirements. LoRA focuses on low-rank matrices to reduce memory usage and computational load, while DEFT optimizes the fine-tuning process by focusing on the most critical data samples.

4. **Task-Specific Adaptation**: If the goal is to adapt a model for specific tasks with minimal data, PEFT methods like DEFT and adapter-based techniques can be beneficial. They allow for efficient fine-tuning with fewer resources.

5. **Transparency and Interpretability**: RAG systems offer more transparency and interpretability in the model’s decision-making process compared to solely fine-tuned models.

6. **Scalability and Deployment**: For large-scale deployments, PEFT methods can significantly reduce computational costs by focusing on influential data samples and using surrogate models.

In summary, the choice depends on the specific needs of the application, such as data access, model behavior, resource availability, and the importance of transparency and scalability.

---
## Discussion

**Traditional/Naive RAG:**

Benefits:
- Simpler implementation and deployment
- Works well for straightforward information retrieval tasks
- Good at handling unstructured text data
- Lower computational overhead

Drawbacks:
- Loses structural information when chunking documents
- Can break up related content during text segmentation
- Limited ability to capture relationships between different pieces of information
- May struggle with complex reasoning tasks requiring connecting multiple facts
- Potential for incomplete or fragmented answers due to chunking boundaries

**GraphRAG:**

Benefits:
- Preserves structural relationships and hierarchies in the knowledge
- Better at capturing connections between related information
- Can provide more complete and contextual answers
- Improved retrieval accuracy by leveraging graph structure
- Better supports complex reasoning across multiple facts
- Can maintain document coherence better than chunk-based approaches
- More interpretable due to explicit knowledge representation

Drawbacks:
- More complex to implement and maintain
- Requires additional processing to construct and update knowledge graphs
- Higher computational overhead for graph operations
- May require domain expertise to define graph schema/structure
- More challenging to scale to very large datasets
- Additional storage requirements for graph structure

**Key Differentiators:**
1. Knowledge Representation: Traditional RAG treats everything as flat text chunks, while GraphRAG maintains structured relationships in a graph format

2. Context Preservation: GraphRAG better preserves context and relationships between different pieces of information compared to the chunking approach of traditional RAG

3. Reasoning Capability: GraphRAG enables better multi-hop reasoning and connection of related facts through graph traversal, while traditional RAG is more limited to direct retrieval

4. Answer Quality: GraphRAG tends to produce more complete and coherent answers since it can access related information through graph connections rather than being limited by chunk boundaries

The choice between traditional RAG and GraphRAG often depends on the specific use case, with GraphRAG being particularly valuable when maintaining relationships between information is important or when complex reasoning is required. An important note as well, GraphRAG approaches still rely on regular embedding and retrieval methods themselves. They compliment eahcother!